In [35]:
import pandas as pd
from IPython.display import display

df_hist = pd.read_excel(r'C:\Users\a.vorona\Desktop\Work\Dingli\Отчет остатки-обороты по складу ПО ЗЧ.xlsx', skiprows=[0, 2], usecols=[0, 4, 7, 8, 9, 10])
df_hist.info()

<class 'pandas.DataFrame'>
RangeIndex: 2116 entries, 0 to 2115
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Номенклатура       2116 non-null   str
 1   Артикул            2114 non-null   object
 2   Начальный остаток  793 non-null    float64
 3   Приход             1543 non-null   float64
 4   Расход             1201 non-null   float64
 5   Конечный остаток   1540 non-null   float64
dtypes: float64(4), object(1), str(1)
memory usage: 99.3+ KB

In [52]:
def join_ordered(series):
    vals = series.dropna().astype(str).str.strip()
    vals = [v for v in vals if v]
    seen = set()
    result = []
    for v in vals:
        if v not in seen:
            seen.add(v)
            result.append(v)
    return "; ".join(result) if result else None

def merge_parts(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["Артикул "] = df["Артикул "].astype(str) 

    agg_map = {
        "Расход": "sum",
    }

    df_agg = df.groupby("Артикул ", as_index=False).agg(agg_map)
    df_agg['Расход'] = df_agg['Расход'].astype(int)


    return df_agg

In [53]:
df_merged = merge_parts(df_hist)

In [55]:
df_merged

            Артикул   Расход
0      GN526-42021HY       3
1      RT230*48K*93       18
2          00000267A       0
3          00000364A       0
4          00000368A       0
...              ...     ...
1955     Я0405053          4
1956     Я0405740          0
1957     Я0406806          0
1958     Я0407527          0
1959        Я0409699       0

[1960 rows x 2 columns]

In [ ]:
df = pd.read_excel('final_модели.xlsx')
df

,Part Number,Description,Models
0,00002362B,Ground control assembly; Ground control assemb...,JCPT0708DCS
1,00000020,895-24055 Pin,JCPT1523RTB; JCPT1823RTB
2,00000023,895-25060 Pin,JCPT1523RTB; JCPT1823RTB
3,00000045,"897-30243 Pin, Pivot",BA16NE; BA18NE
4,00000046,"897-30300 Pin, Pivot",BA16NE; BA18NE
...,...,...,...
7246,93305316,Spring Washer Ф16.4,BA36RT; BA41RT; BA44RT
7247,93305785,Spring Washer Ф8.2,BA36RT; BA41RT; BA44RT
7248,93305786,Spring Washer Ф10.2,BA36RT; BA41RT; BA44RT
7249,93305787,Spring Washer Ф12.4,BA36RT; BA41RT; BA44RT
7250,93306303,Bolt,BA44RT

In [ ]:
df_filtered = df_merged[df_merged["Артикул "].isin(df['Part Number'])]

In [61]:
df_filtered['Артикул '].values.tolist()

['10000038',
 '10000041',
 '10000264',
 '10000486',
 '10001892',
 '10002547',
 '10002659',
 '10002749',
 '10002788',
 '10002798',
 '10002910',
 '10002978',
 '10003117',
 '10007103',
 '10011884',
 '10025520',
 '10025643',
 '10026123',
 '50000822',
 '50007738',
 '50008020',
 '50008315',
 '50008319',
 '50008343',
 '50008471',
 '50008820',
 '50009032',
 '50009033',
 '50009322',
 '50009323',
 '50010197',
 '50010317',
 '50011823',
 '85000137',
 '90003907',
 '90008236',
 '90023094',
 '90029476',
 '90031601',
 '90031602',
 '92000050',
 '92000051',
 '92000073',
 '92000236',
 '92000239',
 '92046502',
 '92047710',
 '92047788',
 '92047789',
 '92048883',
 '92048979',
 '92049050',
 '92049154',
 '92049294',
 '92049371',
 '92100229',
 '92100269',
 '92100287',
 '92100316',
 '92100559',
 '92101000',
 '92101610',
 '93000253',
 '93000393',
 '93000395',
 '93000597',
 '93000598',
 '93000600',
 '93000601',
 '93200031',
 '93200128',
 '93200129',
 '93300023',
 '93300224',
 '93300424',
 '93300432',
 '93300721',
 '93301069']