In [2]:
import os
import camelot
import pandas as pd
from tqdm import tqdm
from IPython.display import display
import warnings
import re
import numpy as np
import pdfplumber

warnings.filterwarnings("ignore")

folder = os.getcwd()
pdf_files = [os.path.join(folder, f) for f in os.listdir(folder) if f.lower().endswith(".pdf")]


def extract_numbers(name):

    nums = re.findall(r'\d+', name)
    return tuple(map(int, nums))

replacements = {
    'Ⅰ': 'I',
    'Ⅱ': 'II',
    'Ⅲ': 'III',
    'Ⅳ': 'IV',
    'Ⅴ': 'V',
    'Ⅵ': 'VI',
    'Ⅶ': 'VII',
    'Ⅷ': 'VIII',
    'Ⅸ': 'IX',
    'Ⅹ': 'X'
}

def extract_tables_camelot(pdf_path: str, out_dir="tables", pages="all", title_height=120):

    os.makedirs(out_dir, exist_ok=True)

    tables_lattice = camelot.read_pdf(
        pdf_path,
        pages=pages,
        flavor="lattice",
        line_scale=80
    )

    lattice_pages = set()
    text_pages = set()

    with pdfplumber.open(pdf_path) as pdf:

        for i, t in enumerate(tables_lattice):

            page_num = int(t.page)          
            page_idx = page_num - 1        
            lattice_pages.add(page_num)

            t.to_csv(
                os.path.join(out_dir, f"lattice_p{page_num}_{i}.csv"),
                index=False
            )

            page = pdf.pages[page_idx]

            x1, y1, x2, y2 = t._bbox
            page_w = page.width
            page_h = page.height

            table_top = page_h - y2

            left   = max(0, min(x1, page_w))
            right  = max(0, min(x2, page_w))
            top    = max(0, min(table_top - title_height, page_h))
            bottom = max(0, min(table_top, page_h))

            if right > left and bottom > top:
                title_box = (left, top, right, bottom)
                title_text = page.crop(title_box, strict=False).extract_text(
                    x_tolerance=2,
                    y_tolerance=2
                ) or ""

                if title_text.strip():
                    text_pages.add(page_num)
            else:
                title_text = ""

            with open(
                os.path.join(out_dir, f"text_p{page_num}_{i}.txt"),
                "w",
                encoding="utf-8"
            ) as f:
                f.write(title_text.strip())

    return None       


def join_ordered(series):
    vals = series.dropna().astype(str).str.strip()
    vals = [v for v in vals if v]
    seen = set()
    result = []
    for v in vals:
        if v not in seen:
            seen.add(v)
            result.append(v)
    return "; ".join(result) if result else None

def merge_parts(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if 'Qty' in df.columns:
        agg_map = {
            "Qty": "sum",
        }
    elif 'Код материалов' in df.columns:
        agg_map = {
            "Кол-во": "sum",
        }
    elif '件数' in df.columns:
        agg_map = {
            '件数': 'sum'
        }
    elif 'Units' in df.columns:
        agg_map = {
            'Units': 'sum'
        }

    if "Item and Spec" in df.columns:

        agg_map["Item and Spec"] = join_ordered
    if "Remark" in df.columns:
        agg_map["Remark"] = join_ordered

    if 'Наименование и спецификация' in df.columns:
        agg_map['Наименование и спецификация'] = join_ordered

    if 'Примечание' in df.columns:
        agg_map['Примечание'] = join_ordered

    if 'Версия' in df.columns:
        agg_map['Версия'] = join_ordered

    if 'Rev.' in df.columns:
        agg_map['Rev.'] = join_ordered

    if "名称及规格" in df.columns:
        agg_map["名称及规格"] = join_ordered

    if "备注" in df.columns:
        agg_map["备注"] = join_ordered

    if "Section" in df.columns:
        agg_map["Section"] = join_ordered

    if 'Material No.' in df.columns:
        df_agg = df.groupby("Material No.", as_index=False).agg(agg_map)
    elif 'Код материалов' in df.columns:
        df_agg = df.groupby("Код материалов", as_index=False).agg(agg_map)
    elif '物料编码' in df.columns:
        df_agg = df.groupby("物料编码", as_index=False).agg(agg_map)


    return df_agg

In [36]:
b = 14
e = b+1

for i, pth in enumerate(tqdm(pdf_files[b:e])):
    
    filename = os.path.basename(pth)          
    filename = os.path.splitext(filename)[0]
    print(f'Обработка файла: {filename}')

    # extract_tables_camelot(pth, filename, pages="all", title_height=800)

    dfs = []

    for file in sorted(os.listdir(filename), key=extract_numbers):

        if not file.startswith("lattice_") or not file.lower().endswith(".csv"):
            continue

        path = os.path.join(filename, file)

        if os.path.getsize(path) == 0:  
            continue
        df_i = pd.read_csv(path, converters={1: str})

        if (
            df_i.empty
            or df_i.shape[1] < 4
            or not any(col in df_i.columns for col in ['NO.', 'Код материалов', 'No.', 'Код мат-ла', 'Serial No.', 'Part No.', '物料编码', 'п/п  Код материалов', 'Код', 'Material No.', 'Material  Code'])
            ):
            continue

        # если китаец насрал пробел в начале таблицы
        if 'NO.' in df_i.iloc[0].values or 'Material No.' in df_i.iloc[0].values:
            df_i.columns = df_i.iloc[0]  
            df_i = df_i[1:].reset_index(drop=True) 

        for col in ['NO.', 'No.', '№ п/п', '№ \nп/п', 'Serial No.', '序号', '№ \n\nп/п', '№ \r\nп/п', '№', 'N\r\no.', 'No\r\n.', 'Serial  number']:
            if col in df_i.columns:
                df_i = df_i.drop(col, axis=1)

        idx = file.replace("lattice_", "").rsplit(".", 1)[0]
        section_val = os.path.join(filename, f"text_{idx}.txt")
        
        with open(section_val, "r", encoding="utf-8") as f:
            lines = f.read().splitlines()

        skip_titles = [
            'Руководство по деталъная структура',
            'Альбом чертежей деталей и узлов коленчатого подъемника для высотных работ',
            'Альбом чертежей деталей и компонентов',
            'Parts Manual',
            '零部件图册',
            'Translated by Google',
            'anslated by Google'
        ]

        if lines and lines[0] in skip_titles:
            lines = lines[1:]
                
        if lines and lines[0] in ['Альбом чертежей деталей и узлов коленчатого', 'Альбом чертежей деталей и узлов коленчатого подъемника для']:
            lines = lines[2:]

        lines_joined = " ".join(lines)
            
        df_i["Section"] = lines_joined
        
        df_i = df_i[df_i.iloc[:, 0].replace('', pd.NA).notna()]
        display(df_i)
        df_i = df_i[df_i.iloc[:, 0] != '/']
        dfs.append(df_i)

    df_all = pd.concat(dfs, ignore_index=True)
    display(df_all)
    df_all.to_excel('dfs.xlsx', index=False)

    for old_col in ['во', 'Кол-\nво', 'Кол-\r\nво', 'Кол-в\nо \nштук', 'Кол-\nво \nшту\nк', 'Кол-во \nштук', 'Cantidad', 'Кол-во\n\nштук', 'Кол-во\r\nштук', 'Кол-\n\nво \n\nшту\n\nк', 'Кол-во \r\nштук', 'Кол-в\r\nо \r\nштук', 'Кол-\r\nво \r\nшту\r\nк', 'Кол-во штук', 'Кол-в', 'Колич\r\nество', 'Кол-в\r\nо\r\nштук', 'Колич ество', 'Кол-во Примечание', 'Number  of  pieces']:
        if old_col in df_all.columns.tolist():
            if 'Кол-во' in df_all.columns.tolist():
                df_all['Кол-во'] = df_all.loc[:, old_col].combine_first(df_all['Кол-во'])
            else:
                df_all['Кол-во'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Кол-во' in df_all.columns:
        col = df_all.pop("Кол-во")  
        df_all.insert(2, "Кол-во", col) 

    for old_col in ['Наименование и \nспецификация', 'Наименование и \r\nспецификация', 'Наименование и\n\nспецификация', 'Nombre y especificación', 'Наименование и \r\nспецификация', 'Наименование и\r\nспецификация', 'Наименование и', 'Наименование\r\nи', 'Наименование']:
        if old_col in df_all.columns.tolist():
            if 'Наименование и спецификация' in df_all.columns:
                df_all['Наименование и спецификация'] = df_all.loc[:, old_col].combine_first(df_all['Наименование и спецификация'])
            else:
                df_all['Наименование и спецификация'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Наименование и спецификация' in df_all.columns:
        col = df_all.pop("Наименование и спецификация")  
        df_all.insert(1, "Наименование и спецификация", col) 

    for old_col in ['Name and Spec.', 'Spec and Item', 'Name  and  specifications']:
        if old_col in df_all.columns:
            if 'Item and Spec' in df_all.columns:
                df_all['Item and Spec'] = df_all.loc[:, old_col].combine_first(df_all['Item and Spec'])
            else:
                df_all['Item and Spec'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Item and Spec' in df_all.columns:
        col = df_all.pop('Item and Spec')  
        df_all.insert(1, 'Item and Spec', col) 

    for old_col in ['Примечани\nе', 'Observaciones', 'Примечани\n\nе', 'Примечани\r\nе', '№ позиции', 'Примеч\r\nание']:
        if old_col in df_all.columns:
            if 'Примечание' in df_all.columns:
                df_all['Примечание'] = df_all.loc[:, old_col].combine_first(df_all['Примечание'])
            else:
                df_all['Примечание'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Примечание' in df_all.columns:
        col = df_all.pop('Примечание')  
        df_all.insert(3, 'Примечание', col) 

    for old_col in ['Qty.', 'Unit', 'Qt\r\ny']:
        if old_col in df_all.columns:
            if 'Qty' in df_all.columns:
                df_all['Qty'] = df_all.loc[:, old_col].combine_first(df_all['Qty'])
            else:
                df_all['Qty'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Qty' in df_all.columns:
        col = df_all.pop('Qty')  
        df_all.insert(2, 'Qty', col) 
        
    for old_col in ['Código de material', 'Код мат-ла', 'п/п  Код материалов', 'Код']:
        if old_col in df_all.columns:
            if 'Код материалов' in df_all.columns:
                df_all['Код материалов'] = df_all.loc[:, old_col].combine_first(df_all['Код материалов'])
            else:
                df_all['Код материалов'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Код материалов' in df_all.columns:
        col = df_all.pop('Код материалов')  
        df_all.insert(0, 'Код материалов', col) 

    for old_col in ['"Версия"', 'Версия  Кол-']:
        if old_col in df_all.columns:
            if 'Версия' in df_all.columns:
                df_all['Версия'] = df_all.loc[:, old_col].combine_first(df_all['Версия'])
            else:
                df_all['Версия'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)

    for old_col in ['Part No.', 'Material Code', 'Material  Code']:
        if old_col in df_all.columns:
            if 'Material No.' in df_all.columns:
                df_all['Material No.'] = df_all.loc[:, old_col].combine_first(df_all['Material No.'])
            else:
                df_all['Material No.'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Material No.' in df_all.columns:
        col = df_all.pop('Material No.')  
        df_all.insert(0, 'Material No.', col) 

    for old_col in ['Note']:
        if old_col in df_all.columns:
            if 'Remark' in df_all.columns:
                df_all['Remark'] = df_all.loc[:, old_col].combine_first(df_all['Remark'])
            else:
                df_all['Remark'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Remark' in df_all.columns:
        col = df_all.pop('Remark')  
        df_all.insert(3, 'Remark', col) 

    for col in ['Кол-во', 'Qty', '件数']:
        if col in df_all.columns:
            df_all[col] = df_all[col].replace({'/': 0, '、': 0, 'A': 0, '-': 0})
            df_all[col] = df_all[col].fillna(0)
            df_all[col] = df_all[col].astype(str).str.replace(',', '.', regex=False)
            df_all[col] = pd.to_numeric(df_all[col], errors='coerce').fillna(0)
            df_all[col] = df_all[col].apply(lambda x: int(x) if x.is_integer() else x)
    
    if 'Код материалов' in df_all.columns:
        df_all['Код материалов'] = df_all['Код материалов'].astype(str).str.replace('\xa0', ' ', regex=False).str.strip()
        extracted = df_all['Код материалов'].str.extract(r'^(\S+)\s+(.*)$')
        mask = extracted[0].notna()
        df_all.loc[mask, 'Наименование и спецификация'] = extracted.loc[mask, 1]
        df_all.loc[mask, 'Код материалов'] = extracted.loc[mask, 0]

    df_all.to_excel('df_all.xlsx', index=False)
    df_all = pd.read_excel('df_all.xlsx')
    test_1 = pd.read_excel('dfs.xlsx')
    assert test_1.shape[0] == df_all.shape[0]

    for col in ['Material No.', 'Код материалов', '物料编码']:
        if col in df_all.columns:
            df_all = df_all[df_all[col] != '']
            df_all = df_all[~df_all[col].astype(str).str.startswith('/')]
            df_all = df_all[~df_all[col].isna()]

    display(df_all.head())

    if 'Material No.' in df_all.columns and df_all['Material No.'].astype(str).str.contains('NO-NUMBER').any():
        df_all['Material No.'] = df_all['Material No.'].str.split('\n').str[0]
        df_all = df_all[~df_all['Material No.'].astype(str).str.startswith('NO-NUMBER')]

    if 'Код материалов' in df_all.columns and df_all['Код материалов'].astype(str).str.contains('NO-NUMBER').any():
        df_all = df_all[~df_all['Код материалов'].astype(str).str.startswith('NO-NUMBER')]

    cols = df_all.select_dtypes(include='object').columns
    df_all[cols] = (df_all[cols].replace(r'\s*\n\s*', ' ', regex=True))
    df_all[cols] = df_all[cols].replace(replacements, regex=True)

    if 'Item and Spec' in df_all.columns:
        df_all['Item and Spec'] = df_all['Item and Spec'].replace('/', np.nan)
    
    if '物料编码' in df_all.columns:
        mask = df_all['物料编码'].str.contains(r'^\d+\s+\D', na=False)
        extracted = df_all.loc[mask, '物料编码'].str.extract(r'^(\d+)\s+(.*)$')
        df_all.loc[mask, '物料编码'] = extracted[0]
        df_all.loc[mask, '名称及规格'] = extracted[1]
        
    df_merged = merge_parts(df_all) 
   
    assert (df_all.shape[0] - df_all.iloc[:, 0].duplicated().sum() - df_merged.shape[0]) == 0

    lst = ['ZS1623RT', 'ZA10RJE', 'ZA14J', 'ZA14JE-Li', 'ZA14NJE', 'ZA16J', 'ZA16JERT', 'ZA18J', 'ZA20J', 'ZA20JE', 'ZA20JERT', 'ZA22J-V' ,'ZA22J', 'ZA24J', 'ZA32J(H-образ.)', 'ZA32J(X-образ.)', 'ZT42J-V', 'ZA42J', '', '', '', '', '', '', '', '', '' ,'', '', 'ZT20J', 'ZT22J-V', 'ZT26J', 'ZT26JS-V', 'ZT30J', 'ZT32J-V', 'ZT32J', 'ZT34J', 'ZT38J', 'ZT42J', 'ZT51J', 'ZT58J', 'ZT72J-V', 'ZT82J', 'ZTH3507', 'ZTH3513', 'ZTH3513', 'ZX23AE']
    df_merged['Models'] = lst[b]

    df_merged.to_excel(f'{filename}.xlsx', index=False)

  0%|          | 0/1 [00:00<?, ?it/s]

Обработка файла: ZA32J ( H -образ.)

,Код материалов,Наименование и \r\nспецификация,Кол-\r\nво,Примечание,Section
0,1040200503,Гайка,2,JB/T889.1,Рабочая платформа 00774000100000000
1,1040302480,Шайба 8-200HV,4,JB/T96.1,Рабочая платформа 00774000100000000
2,00773400100261050,Подшипник,2,NaN,Рабочая платформа 00774000100000000
3,00773400100261060,Болт φ22,2,NaN,Рабочая платформа 00774000100000000
4,00773400100260020,Защитный кожух,1,NaN,Рабочая платформа 00774000100000000
5,1040005844,Болт M6×10-A2-70,4,JB/T5783,Рабочая платформа 00774000100000000
6,1040300771,Шайба 6-200HV,8,JB/T97.1,Рабочая платформа 00774000100000000
7,00773400100261030,Пластина II,1,NaN,Рабочая платформа 00774000100000000
8,00773400100261080,Упорная планка,2,NaN,Рабочая платформа 00774000100000000
9,00773406200210000,Электрический шкаф \r\nуправления платформой в...,1,NaN,Рабочая платформа 00774000100000000
10,1040006017,Винт M6×25-A2-70,4,JB/T70.1,Рабочая платформа 00774000100000000
11,00773400100261110,Упор,2,NaN,Рабочая платформа 00774000100000000
12,1040201896,Гайка M6-8,4,JB/T889.1,Рабочая платформа 00774000100000000
13,1040201902,Гайка M6-6,12,JB/T802,Рабочая платформа 00774000100000000
14,1040300771,Шайба 6-200HV,14,JB/T97.1,Рабочая платформа 00774000100000000
15,1040300735,Шайба 6-200HV,10,JB/T96.1,Рабочая платформа 00774000100000000
16,1040102773,Винт M6×40-8.8,6,JB/T70.1,Рабочая платформа 00774000100000000
17,1040102774,Винт M6×15-8.8,6,JB/T70.1,Рабочая платформа 00774000100000000
18,00773400100201010,Упорная планка I,1,NaN,Рабочая платформа 00774000100000000
19,1999904986,Коробка для файлов,1,NaN,Рабочая платформа 00774000100000000
20,1040200504,Гайка M10-8,4,JB/T889.1,Рабочая платформа 00774000100000000
21,1040302512,Шайба 10-200HV,8,JB/T96.1,Рабочая платформа 00774000100000000
22,00773406300201030,Каучуковая прокладка,2,NaN,Рабочая платформа 00774000100000000
23,1040004508,Болт M10×45-8.8,4,JB/T5783,Рабочая платформа 00774000100000000
24,00771600100210000,Свариваемые изделия \r\nплатформы,1,NaN,Рабочая платформа 00774000100000000
25,1040004522,"Болт M8×50-8,8",1,JB/T5783,Рабочая платформа 00774000100000000
26,1040301515,Шайба 8-200HV,2,JB/T97.1,Рабочая платформа 00774000100000000
27,00775600101801010,Личинка замка,1,NaN,Рабочая платформа 00774000100000000
28,1040201880,Гайка M8-6,1,JB/T802,Рабочая платформа 00774000100000000
29,00775600101801020,Пружина,1,NaN,Рабочая платформа 00774000100000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1159901036,Пружинная петля,2,NaN,Рабочая платформа 00774000100000000
1,1040300514,Шайба 5-200HV,12,JB/T97.1,Рабочая платформа 00774000100000000
2,1029904911,Пружинящая шайба,12,GB93-304,Рабочая платформа 00774000100000000
3,1040004672,"Болт M5×10-8,8",12,JB/T5783,Рабочая платформа 00774000100000000
4,1040001640,Болт M6×25-A2-70,2,JB/T5783,Рабочая платформа 00774000100000000
5,1040300771,Шайба 6-200HV,2,JB/T97.1,Рабочая платформа 00774000100000000
6,00774000101000000,Сварной элемент кронштейна \r\nфильтра,1,NaN,Рабочая платформа 00774000100000000
7,1040201896,Гайка M6-8,2,JB/T889.1,Рабочая платформа 00774000100000000
8,00774000100810001,Переходный держатель,1,NaN,Рабочая платформа 00774000100000000
9,1040004619,"Болт M8×35-8,8",4,JB/T5783,Рабочая платформа 00774000100000000
10,1040301515,Шайба 8-200HV,24,JB/T97.1,Рабочая платформа 00774000100000000
11,00773400100401020,Прижимная планка,2,NaN,Рабочая платформа 00774000100000000
12,1040004654,"Болт M16×1,5×40-10,9",8,JB/T5787,Рабочая платформа 00774000100000000
13,1021404016,Датчик веса,1,NaN,Рабочая платформа 00774000100000000
14,00774000100400000,Защитная крышка \r\nгидровлического клапана \r...,1,NaN,Рабочая платформа 00774000100000000
15,1040004505,"Болт M24×280-10,9",1,JB/T5782,Рабочая платформа 00774000100000000
16,1040004033,Болт M10×25-10.9,8,JB/T5783,Рабочая платформа 00774000100000000
17,1040301511,Шайба 24-200HV,1,JB/T97.1,Рабочая платформа 00774000100000000
18,1040201111,Гайка M24 -10,1,JB/T889,Рабочая платформа 00774000100000000
19,00774000100600000,Сварной элемент кронштейна \r\nгидравлического...,1,NaN,Рабочая платформа 00774000100000000
20,1040004556,"Болт M12×35-8,8",10,JB/T16674.1,Рабочая платформа 00774000100000000
21,1040302490,Шайба 12-200HV,2,JB/T97.1,Рабочая платформа 00774000100000000
22,1040201089,Гайка M8-8,6,JB/T6170,Рабочая платформа 00774000100000000
23,1040004570,"Болт M16×30-8,8",4,JB/T5783,Рабочая платформа 00774000100000000
24,1040302513,Шайба 16-200HV,4,NaN,Рабочая платформа 00774000100000000
25,00773400110401010,Анкерная плита Ⅱ,2,JB/T96.1,Рабочая платформа 00774000100000000
26,00773700100420000,Сварная деталь кронштейна,1,NaN,Рабочая платформа 00774000100000000
27,1040301510,Шайба 8,6,JB/T93,Рабочая платформа 00774000100000000
28,00773400100401040,Вкладыш,2,NaN,Рабочая платформа 00774000100000000
29,1040103118,Винт,6,JB/T70.1,Рабочая платформа 00774000100000000

,Код материалов,Наименование и \r\nспецификация,Кол-во,Примечание,Section
0,00774100200400000,Верхний шатун,1,NaN,Консоль 00774100200000000
1,00774000200001300,Плита трубопровода,2,NaN,Консоль 00774100200000000
2,00773700200001100,Зажимная планка \r\nтрубопровода,2,NaN,Консоль 00774100200000000
3,1040103262,Винт M6×45-8.8,8,NaN,Консоль 00774100200000000
4,00774100200001010,Щиток трубы,1,NaN,Консоль 00774100200000000
5,1040004522,"Болт M8×50-8,8",4,JB/T5783,Консоль 00774100200000000
6,00773400200001010,Подшипник,12,NaN,Консоль 00774100200000000
7,1040301515,Шайба 8-200HV,10,JB/T97.1,Консоль 00774100200000000
8,1040004590,"Болт M8×14-8,8",4,JB/T5783,Консоль 00774100200000000
9,00771400211200000,Подвижный трубный хомут,2,NaN,Консоль 00774100200000000
10,00773400300001200,Стопорный штифт,8,NaN,Консоль 00774100200000000
11,00773700200001060,Штифт,2,NaN,Консоль 00774100200000000
12,1040002433,Болт M10×20-8.8,8,JB/T5783,Консоль 00774100200000000
13,00774100201200000,Защитный кожух датчика,1,NaN,Консоль 00774100200000000
14,1040103110,Винт M8×10-8.8,2,JB/T70.1,Консоль 00774100200000000
15,1010201471,Качающийся цилиндр,1,NaN,Консоль 00774100200000000
16,00774000200001010,Распорная втулка качающегося \r\nцилиндра,1,NaN,Консоль 00774100200000000
17,00774100200600000,Нижний шатун,2,NaN,Консоль 00774100200000000
18,00774100200001040,Прокладочное кольцо I,1,NaN,Консоль 00774100200000000
19,00773700200001050,Штифт,3,NaN,Консоль 00774100200000000
20,00774100200001050,Прокладочное кольцо II,1,NaN,Консоль 00774100200000000
21,00774100201800000,Гидроцилиндр консоли,1,NaN,Консоль 00774100200000000
22,00774000200001030,Штифт выравнивающего \r\nцилиндра подпоры,1,NaN,Консоль 00774100200000000
23,00774000200200000,Опора,1,NaN,Консоль 00774100200000000
24,00773400200001020,Подшипник,2,NaN,Консоль 00774100200000000

,Код материалов,Наименование и спецификация,Кол-во,Примечани\r\nе,Section
0,1040002433,"Болт M10×20-8,8",14,JB/T5783,Верхняя стрела в сборе 00774100300000000
1,1040302489,Шайба 10-200HV,38,JB/T97.1,Верхняя стрела в сборе 00774100300000000
2,00774000302400000,Узлы ползуна,4,NaN,Верхняя стрела в сборе 00774100300000000
3,1040004565,"Болт M10×30-8,8-DKL",14,JB/T5783,Верхняя стрела в сборе 00774100300000000
4,00773400300001131,Регулировочная шайба (2 мм),10,NaN,Верхняя стрела в сборе 00774100300000000
5,00773400300001140,Регулировочная шайба Ⅴ,10,NaN,Верхняя стрела в сборе 00774100300000000
6,00774000302600001,Узлы ползуна,8,NaN,Верхняя стрела в сборе 00774100300000000
7,1040004519,"Болт M8×25-8,8",6,JB/T5783,Верхняя стрела в сборе 00774100300000000
8,1040301515,Шайба 8-200HV,40,JB/T97.1,Верхняя стрела в сборе 00774100300000000
9,00773700300001181,Регулировочная шайба цилиндра II,2,NaN,Верхняя стрела в сборе 00774100300000000
10,00773700300001171,Регулировочная шайба цилиндра I,4,NaN,Верхняя стрела в сборе 00774100300000000
11,00773700302001020,Ушко,2,NaN,Верхняя стрела в сборе 00774100300000000
12,00774000302001010,Вкладка,2,NaN,Верхняя стрела в сборе 00774100300000000
13,1040002434,"Болт M10×25-8,8",7,JB/T5783,Верхняя стрела в сборе 00774100300000000
14,00771100301500000,Ползун,4,NaN,Верхняя стрела в сборе 00774100300000000
15,00771100301601071,Регулировочная шайба,2,NaN,Верхняя стрела в сборе 00774100300000000
16,00771100301601061,Регулировочная шайба,4,NaN,Верхняя стрела в сборе 00774100300000000
17,00774000300001080,Правая контактная плата,1,NaN,Верхняя стрела в сборе 00774100300000000
18,1040004507,"Болт M10×40-8,8",3,JB/T5783,Верхняя стрела в сборе 00774100300000000
19,00774000300001040,Штифт выравнивающего цилиндра на \r\nосновной ...,1,NaN,Верхняя стрела в сборе 00774100300000000
20,00773700400001290,Скоба,2,NaN,Верхняя стрела в сборе 00774100300000000
21,1040103076,"Винт M8×16-8,8",4,JB/T70.3,Верхняя стрела в сборе 00774100300000000
22,1040004511,"Болт M12×30-8,8",1,JB/T5783,Верхняя стрела в сборе 00774100300000000
23,00773400200001070,Стопорный штифт,1,NaN,Верхняя стрела в сборе 00774100300000000
24,00773700300001020,Шкворень II,1,NaN,Верхняя стрела в сборе 00774100300000000
25,00773400300001210,Подшипник,4,NaN,Верхняя стрела в сборе 00774100300000000
26,00774100300001070,Прокладочное кольцо III,1,NaN,Верхняя стрела в сборе 00774100300000000
27,00774100301000000,Верхний гидроцилиндр выравнивания,1,NaN,Верхняя стрела в сборе 00774100300000000
28,00774100300001080,Прокладочное кольцо IV,1,NaN,Верхняя стрела в сборе 00774100300000000
29,1040200503,Гайка M8-8,9,JB/T889.1,Верхняя стрела в сборе 00774100300000000
30,00774000300001060,Крепительная планка,2,NaN,Верхняя стрела в сборе 00774100300000000
31,00771600700001030,Ползун,2,NaN,Верхняя стрела в сборе 00774100300000000

,Код материалов,Наименование и спецификация,Количество,Примечание,Section
0,00773400400001250,Стопорный штифт,1,NaN,Верхняя стрела в сборе 00774100300000000
1,00773400400001250,Стопорный штифт,1,NaN,Верхняя стрела в сборе 00774100300000000
2,1040004590,"Болт M8×14-8,8",18,JB/T5783,Верхняя стрела в сборе 00774100300000000
3,00774100300001030,Штифт телескопического \r\nцилиндра,2,NaN,Верхняя стрела в сборе 00774100300000000
4,00773400300001200,Стопорный штифт,2,NaN,Верхняя стрела в сборе 00774100300000000
5,00774100300001020,Хвостовая панель заглушки,1,NaN,Верхняя стрела в сборе 00774100300000000
6,1040006017,Винт M6×25-A2-70,2,NaN,Верхняя стрела в сборе 00774100300000000
7,00774000300001140,Регулирующий щиток путевого \r\nвыключателя,1,NaN,Верхняя стрела в сборе 00774100300000000
8,00773700300001210,Панель заглушки основной \r\nстрелы,2,NaN,Верхняя стрела в сборе 00774100300000000
9,00774100300400001,Стрела выдвижения-втягивания,1,NaN,Верхняя стрела в сборе 00774100300000000
10,00774100301200000,Гидроцилиндр \r\nвыдвижения-втягивания,1,NaN,Верхняя стрела в сборе 00774100300000000
11,00774100300200002,Основная стрела,1,NaN,Верхняя стрела в сборе 00774100300000000
12,00773400400001250,Стопорный штифт,1,NaN,Верхняя стрела в сборе 00774100300000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00774100700201030,Прямоугольная труба,1,NaN,Система буксирной цепи верхней стрелы007741007...
1,00774100700201120,Механизм буксируемой цепи,1,NaN,Система буксирной цепи верхней стрелы007741007...
2,1040201896,Гайка,8,JB/T889.1,Система буксирной цепи верхней стрелы007741007...
3,00774100700201130,Переходная плита,1,NaN,Система буксирной цепи верхней стрелы007741007...
4,1040103076,Винт,4,JB/T70.3,Система буксирной цепи верхней стрелы007741007...
5,1040101643,Винт,8,JB/T70.1,Система буксирной цепи верхней стрелы007741007...
6,00773700700001100,Подкладка,1,NaN,Система буксирной цепи верхней стрелы007741007...
7,1040300514,Шайба,16,JB/T97.1,Система буксирной цепи верхней стрелы007741007...
8,1040200503,Гайка,14,JB/T889.1,Система буксирной цепи верхней стрелы007741007...
9,1040004522,Болт,2,JB/T5783,Система буксирной цепи верхней стрелы007741007...
10,1040301515,Шайба,22,JB/T97.1,Система буксирной цепи верхней стрелы007741007...
11,00774000700001120,Трубный хомут III,1,NaN,Система буксирной цепи верхней стрелы007741007...
12,00774000700201070,Трубный хомут I,1,NaN,Система буксирной цепи верхней стрелы007741007...
13,00773700700001030,Изогнута пластинка,1,NaN,Система буксирной цепи верхней стрелы007741007...
14,00774000700001110,Прокладка,1,NaN,Система буксирной цепи верхней стрелы007741007...
15,1040004675,Болт,2,JB/T5782,Система буксирной цепи верхней стрелы007741007...
16,1040004519,Болт,10,JB/T5783,Система буксирной цепи верхней стрелы007741007...
17,00774000700201040,Прижимная планка трубопровода,1,NaN,Система буксирной цепи верхней стрелы007741007...
18,00774000700201080,Трубный хомут II,1,NaN,Система буксирной цепи верхней стрелы007741007...
19,00774000700201060,Прокладка,1,NaN,Система буксирной цепи верхней стрелы007741007...
20,00774100700210000,Кронштейн I,1,NaN,Система буксирной цепи верхней стрелы007741007...

,Код материалов,Наименование и спецификация,Кол-во Примечание,Unnamed: 4,Section
0,1040103119,"Винт M8×110-8,8",2.0,JB/T70.1,Башенная стрела в сборе 00774100400000000
1,1040301515,Шайба 8-200HV,20.0,JB/T97.1,Башенная стрела в сборе 00774100400000000
2,00774100700401120 Прижимная планка трубопрово...,NaN,NaN,NaN,Башенная стрела в сборе 00774100400000000
4,00774100700401090 Трубный хомут II,NaN,1.0,NaN,Башенная стрела в сборе 00774100400000000
5,00774100700401080 Трубный хомут I,NaN,1.0,NaN,Башенная стрела в сборе 00774100400000000
6,00774100700401160 Прокладка IV,NaN,NaN,NaN,Башенная стрела в сборе 00774100400000000
8,1040200503,Гайка M8-8,2.0,JB/T889.1,Башенная стрела в сборе 00774100400000000
9,00774000400001350 Подшипник,NaN,NaN,NaN,Башенная стрела в сборе 00774100400000000
11,1040103110,"Винт M8×10-8,8",2.0,JB/T70.1,Башенная стрела в сборе 00774100400000000
12,1040302480,Шайба 8-200HV,8.0,JB/T96.1,Башенная стрела в сборе 00774100400000000
13,00774100400001101 Монтажная планка,NaN,1.0,NaN,Башенная стрела в сборе 00774100400000000
14,00774100400001230 Распорная втулка,NaN,2.0,NaN,Башенная стрела в сборе 00774100400000000
16,1040004499,"Болт M20×45-8,8",1.0,JB/T5783,Башенная стрела в сборе 00774100400000000
17,00773400400001170 Стопорный штифт φ20×120*,NaN,4.0,NaN,Башенная стрела в сборе 00774100400000000
18,00774100400001040 Штырь III,NaN,1.0,NaN,Башенная стрела в сборе 00774100400000000
19,00774100402600000 Ползун,NaN,NaN,NaN,Башенная стрела в сборе 00774100400000000
21,00773400300001130 Регулирующая прокладка Ⅳ,NaN,40.0,NaN,Башенная стрела в сборе 00774100400000000
22,1040302489,Шайба 10-200HV,71.0,JB/T97.1,Башенная стрела в сборе 00774100400000000
23,1040002434,"Болт M10×25-8,8",52.0,JB/T5783,Башенная стрела в сборе 00774100400000000
24,1040201896,Гайка M6-8,20.0,JB/T889.1,Башенная стрела в сборе 00774100400000000
25,00774100403400000 Пылезащитная щетка II,NaN,NaN,NaN,Башенная стрела в сборе 00774100400000000
27,1040300771,Шайба 6-200HV,28.0,JB/T97.1,Башенная стрела в сборе 00774100400000000
28,1040004601,"Болт M6×40-8,8",20.0,JB/T5782,Башенная стрела в сборе 00774100400000000
29,00774100400001180 Прокладка,NaN,NaN,NaN,Башенная стрела в сборе 00774100400000000
31,00774100403800000 Пылезащитная щетка IV,NaN,NaN,NaN,Башенная стрела в сборе 00774100400000000
33,00773400300001140 Регулировочная шайба Ⅴ,NaN,16.0,NaN,Башенная стрела в сборе 00774100400000000
34,00774000302600001 Узлы ползуна,NaN,16.0,NaN,Башенная стрела в сборе 00774100400000000
35,1040004565,"Болт M10×30-8,8-DKL",20.0,JB/T5783,Башенная стрела в сборе 00774100400000000
36,00774100400001130 Длинная регулирующая прокла...,NaN,12.0,NaN,Башенная стрела в сборе 00774100400000000
37,00774100400001120 Длинная регулирующая прокла...,NaN,6.0,NaN,Башенная стрела в сборе 00774100400000000
38,00774100402800000 Длинный сухарь,NaN,8.0,NaN,Башенная стрела в сборе 00774100400000000
39,00774100400200000 Сварной элемент первой секц...,NaN,1.0,NaN,Башенная стрела в сборе 00774100400000000
40,00774100400001240 Монтажная планка путевого в...,NaN,1.0,NaN,Башенная стрела в сборе 00774100400000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00774100400001210,Фиксированная ось,1,NaN,Башенная стрела в сборе 00774100400000000
1,1040101995,Винт M10×30-8.8-DKL,4,JB/T70.1,Башенная стрела в сборе 00774100400000000
2,00771400800001080,Прокладка нейлоновая,2,NaN,Башенная стрела в сборе 00774100400000000
3,1040004598,"Болт M8×65-8,8",16,JB/T5782,Башенная стрела в сборе 00774100400000000
4,00774100400001061,Прижимная планка,8,NaN,Башенная стрела в сборе 00774100400000000
5,00774100401200000,Телескопическая система,1,NaN,Башенная стрела в сборе 00774100400000000
6,00774100400400000,Сварной элемент второй секции \r\nбашенной стрелы,1,NaN,Башенная стрела в сборе 00774100400000000
7,00774100403000000,Пылезащитная щетка I,2,NaN,Башенная стрела в сборе 00774100400000000
8,00774100403600000,Пылезащитная щетка III,2,NaN,Башенная стрела в сборе 00774100400000000
9,00774100400001091,Контактная панель,1,NaN,Башенная стрела в сборе 00774100400000000
10,1040302512,Шайба 10-200HV,2,JB/T96.1,Башенная стрела в сборе 00774100400000000
11,1040005844,Болт M10×10-A2-70,8,JB/T5783,Башенная стрела в сборе 00774100400000000
12,00774100400001200,Боковая крышка,2,NaN,Башенная стрела в сборе 00774100400000000
13,00774100400001080,Крышка,1,NaN,Башенная стрела в сборе 00774100400000000
14,1040004590,"Болт M8×14-8,8",6,JB/T5783,Башенная стрела в сборе 00774100400000000
15,1040003572,"Болт M16×55-10,9-DKL",3,JB/T5783,Башенная стрела в сборе 00774100400000000
16,00774100400001030,Штырь II,1,NaN,Башенная стрела в сборе 00774100400000000
17,00774100400001020,Штырь I,1,NaN,Башенная стрела в сборе 00774100400000000
18,00774100400001050,Штырь IV,1,NaN,Башенная стрела в сборе 00774100400000000
19,00774100401000000,Сварной элемент шатуна II,1,NaN,Башенная стрела в сборе 00774100400000000
20,00771400301201030,"Подшипник, не требующий \r\nсмазывания Ⅱ",4,NaN,Башенная стрела в сборе 00774100400000000
21,00771100600001060,"Подшипник, не требующий \r\nсмазывания",2,NaN,Башенная стрела в сборе 00774100400000000
22,00774100400800000,Сварной элемент шатуна I,1,NaN,Башенная стрела в сборе 00774100400000000
23,00774100400600000,Сварной элемент третьей секции \r\nбашенной ст...,1,NaN,Башенная стрела в сборе 00774100400000000

,Код материалов,Наименование и спецификация,Unnamed: 3,Кол-во Примечание,Section
0,1040102738,Винт \r\n M8×55-8.8,6.0,JB/T70.1,Система буксирной цепи башенной стрелы 0077410...
1,1040301515,Шайба 8-200HV,24.0,JB/T97.1,Система буксирной цепи башенной стрелы 0077410...
2,00774100700401240 Замыкающий блокII,NaN,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
3,00774100700401180 Направляющая прямоугольная ...,NaN,2.0,NaN,Система буксирной цепи башенной стрелы 0077410...
4,1040103112,Винт \r\n M8×25-8.8,2.0,JB/T70.1,Система буксирной цепи башенной стрелы 0077410...
5,1040102717,Винт \r\n M8×40-8.8,4.0,JB/T70.3,Система буксирной цепи башенной стрелы 0077410...
6,00774100700401200 ПрокладкаV,NaN,NaN,NaN,Система буксирной цепи башенной стрелы 0077410...
8,1040200503,Гайка M8-8,8.0,JB/T889.1,Система буксирной цепи башенной стрелы 0077410...
9,00774100700401100 Монтажная планка,NaN,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
10,00774100700401010 Прямоугольная труба,NaN,NaN,NaN,Система буксирной цепи башенной стрелы 0077410...
12,1040004632,Болт M8×100-8.8,2.0,JB/T5782,Система буксирной цепи башенной стрелы 0077410...
13,00774100700401160 ПрокладкаIV,NaN,NaN,NaN,Система буксирной цепи башенной стрелы 0077410...
15,00774100700401090 Трубный хомутII,NaN,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
16,00774100700401080 Трубный хомутI,NaN,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
17,00774100700401120 Прижимная планка трубопроводаI,NaN,NaN,NaN,Система буксирной цепи башенной стрелы 0077410...
19,1040103076,Винт M8×16-8.8,4.0,JB/T70.3,Система буксирной цепи башенной стрелы 0077410...
20,1040103111,Винт M8×16-8.8,8.0,JB/T70.1,Система буксирной цепи башенной стрелы 0077410...
21,00774100700401260 Нейлоновый блок,NaN,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
22,00774100700401052 Механизм буксируемой цепи,NaN,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
23,1109901007,NaN,NaN,NaN,Система буксирной цепи башенной стрелы 0077410...
25,1109901008,Распорка буксирной цепи,94.0,NaN,Система буксирной цепи башенной стрелы 0077410...
26,1109901009,Муфта буксирной цепи 450×108,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
27,1109901010,Соединитель подвижного конца буксирной \r\nцеп...,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
28,1109901011,Скобка буксирной цепи,94.0,NaN,Система буксирной цепи башенной стрелы 0077410...
29,1109901012,Разделитель буксирной цепи,12.0,NaN,Система буксирной цепи башенной стрелы 0077410...
30,1040004517,Болт M8×16-8.8,8.0,JB/T5783,Система буксирной цепи башенной стрелы 0077410...
31,00774100700401270 Противоударный блокI,NaN,NaN,NaN,Система буксирной цепи башенной стрелы 0077410...
33,00774100700401280 Упорный блокII,NaN,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...
34,1040004523,Болт M8×70-8.8,4.0,JB/T5783,Система буксирной цепи башенной стрелы 0077410...
35,00773400700001050 Изогнутая монтажная пластина,NaN,2.0,NaN,Система буксирной цепи башенной стрелы 0077410...

,Код материалов,Наименование и спецификация,Unnamed: 3,Кол-во Примечание,Section
0,00774100700401171 Трубный хомутIV,NaN,3.0,NaN,Система буксирной цепи башенной стрелы 0077410...
1,00774100700401231 Прижимная планка трубопрово...,NaN,NaN,NaN,Система буксирной цепи башенной стрелы 0077410...
3,1040004675,Болт M8×85-8.8,2.0,NaN,Система буксирной цепи башенной стрелы 0077410...
4,00774100700410001,Сварной элемент прямоугольной трубы сварная \r...,1.0,NaN,Система буксирной цепи башенной стрелы 0077410...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00774100800001090,Переходная плита I,2,NaN,Поворотная платформа 00774100800000000
1,1040302821,Шайба 12-200HV,27,JB/T96.1,Поворотная платформа 00774100800000000
2,1040004644,"Болт M12×45-10,9",22,JB/T5783,Поворотная платформа 00774100800000000
3,1040004507,Болт M10×40-8.8,2,JB/T5783,Поворотная платформа 00774100800000000
4,00771400800001030 Штифт,NaN,1,NaN,Поворотная платформа 00774100800000000
5,00773400300001200,Стопорный штифт,1,NaN,Поворотная платформа 00774100800000000
6,00771400801800000 Штифт в сборе,NaN,1,NaN,Поворотная платформа 00774100800000000
7,00774000800400000,Кронштейн двигателя,1,NaN,Поворотная платформа 00774100800000000
8,00771400800001140,Гнутая пластина,1,NaN,Поворотная платформа 00774100800000000
9,1040200504,Гайка M10-8,2,JB/T889.1,Поворотная платформа 00774100800000000
10,1040201381,Гайка M12-8,1,JB/T6170,Поворотная платформа 00774100800000000
11,00773400800001221,Регулировочная шайба,1,NaN,Поворотная платформа 00774100800000000
12,1040102741,"Винт M10×40-8,8",2,JB/T70.1,Поворотная платформа 00774100800000000
13,00773400800001210,Вкладыш для поддона,1,NaN,Поворотная платформа 00774100800000000
14,00773400800001311,Регулировочная шайба,3,NaN,Поворотная платформа 00774100800000000
15,1040002555,Болт M6×16-A2-70,1,JB/T5783,Поворотная платформа 00774100800000000
16,1040300735,Шайба 6-200HV,1,JB/T96.1,Поворотная платформа 00774100800000000
17,00771400800001020,Самосмазывающийся подшипник,2,NaN,Поворотная платформа 00774100800000000
18,00773400800001150,Фрикционная накладка,1,NaN,Поворотная платформа 00774100800000000
19,1040002434,Болт M10×25-8.8,16,JB/T5783,Поворотная платформа 00774100800000000
20,00773400800001200,Опора переключателя,1,NaN,Поворотная платформа 00774100800000000
21,1040001631,Болт M6×20-A2-70,2,JB/T5783,Поворотная платформа 00774100800000000
22,1040300771,Шайба 6-200HV,6,JB/T97.1,Поворотная платформа 00774100800000000
23,1040005846,"Болт M12×20-8,8",4,JB/T5783,Поворотная платформа 00774100800000000
24,1040201896,Гайка M6-8,6,JB/T889.1,Поворотная платформа 00774100800000000
25,00774000800001610,Нажимная плита аккумулятора,2,NaN,Поворотная платформа 00774100800000000
26,00774000800001600,Перегородка для аккумулятора,1,NaN,Поворотная платформа 00774100800000000
27,00773400800001131,Тяга аккумулятора,4,NaN,Поворотная платформа 00774100800000000
28,00774000802100000,Поддон аккумулятора,1,NaN,Поворотная платформа 00774100800000000
29,00774000800001360,Упорная планка II,1,NaN,Поворотная платформа 00774100800000000
30,00774100800200000,Сварной элемент поворотной платформы,1,NaN,Поворотная платформа 00774100800000000
31,00774100801200000,Защитный кожух датчика,1,NaN,Поворотная платформа 00774100800000000
32,1040302489,Шайба 10-200HV,23,JB/T97.1,Поворотная платформа 00774100800000000
33,00771100800001080,Стопорный штифт,1,1,Поворотная платформа 00774100800000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040103205,Винт M12×100-8.8,1,JB/T70.1,Поворотная платформа 00774100800000000
1,00774100800001050,Капот III,1,NaN,Поворотная платформа 00774100800000000
2,1040302480,Шайба 8-200HV,43,JB/T96.1,Поворотная платформа 00774100800000000
3,1040004518,"Болт M8×20-8,8",39,JB/T5783,Поворотная платформа 00774100800000000
4,00774100800001130,Антифрикционная плита,2,NaN,Поворотная платформа 00774100800000000
5,1040101494,Винт M12×40-8.8,4,JB/T70.1,Поворотная платформа 00774100800000000
6,00774100800001190,Прокладка II,1,NaN,Поворотная платформа 00774100800000000
7,00774100800001180,Регулировочная шайба,6,NaN,Поворотная платформа 00774100800000000
8,00774001000001030,Защитная планка I,2,NaN,Поворотная платформа 00774100800000000
9,1040100087,Винт M12×25-8.8,8,JB/T70.1,Поворотная платформа 00774100800000000
10,00774000800001060,Монтажная планка датчика,1,NaN,Поворотная платформа 00774100800000000
11,00774100800001100,Скоба вращающегося соединения,1,NaN,Поворотная платформа 00774100800000000
12,00774100800001060,Штырь башенной стрелы,1,NaN,Поворотная платформа 00774100800000000
13,00773400400001170,Стопорный штифт,2,NaN,Поворотная платформа 00774100800000000
14,00774100800001160,Штырь башенной стрелы II,1,NaN,Поворотная платформа 00774100800000000
15,1040004499,"Болт M16×45-8,8",2,JB/T5783,Поворотная платформа 00774100800000000
16,00774000800001010,Упорная планка I,1,NaN,Поворотная платформа 00774100800000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00774000801200000,Опора бака топлива,1,NaN,Поворотная платформа 00774100800000000
1,00774100800600000,Монтажный \r\nкронштейн \r\nосновного \r\nклапана,1,NaN,Поворотная платформа 00774100800000000
2,00774100800001010,Капот I,1,NaN,Поворотная платформа 00774100800000000
3,00774100801000000,Монтажный \r\nкронштейн \r\nподставки \r\nзамка,1,NaN,Поворотная платформа 00774100800000000
4,1040004519,"Болт M8×25-8,8",3,JB/T5783,Поворотная платформа 00774100800000000
5,1040301515,Шайба 8-200HV,3,JB/T97.1,Поворотная платформа 00774100800000000
6,00774000801600000,Опора бандажа,1,NaN,Поворотная платформа 00774100800000000
7,00774100800900000,Монтажная опора аварийного насоса,1,NaN,Поворотная платформа 00774100800000000
8,1040004520,"Болт M8×30-8,8",4,JB/T5783,Поворотная платформа 00774100800000000
9,00774100800001120,Скоба пучка проводов,1,NaN,Поворотная платформа 00774100800000000
10,1040200503,Гайка M8-8,4,JB/T889.1,Поворотная платформа 00774100800000000
11,00774100800001140,Резиновая \r\nпрокладка \r\nящика \r\nэлектрич...,2,NaN,Поворотная платформа 00774100800000000
12,00774100800001080,Опора \r\nшкафа \r\nэлектрического \r\nуправления,1,NaN,Поворотная платформа 00774100800000000
13,1040005840,"Болт M16×110-10,9-DKL",1,JB/T1228,Поворотная платформа 00774100800000000
14,1040201382,Гайка M16 -8,1,JB/T6170,Поворотная платформа 00774100800000000
15,00771400800001170,Кожух шестерни,1,NaN,Поворотная платформа 00774100800000000
16,00774100800001040,Капот II,1,NaN,Поворотная платформа 00774100800000000
17,00774100800001070,Вкладыш,1,NaN,Поворотная платформа 00774100800000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040002458,Болт M8×40-8.8,12,JB/T5783,Капот 00774101100000000
1,1040301515,Шайба 8-200HV,28,JB/T97.1,Капот 00774101100000000
2,1040004518,"Болт M8×20-8,8",18,JB/T5783,Капот 00774101100000000
3,1040301510,Шайба 8,42,JB/T93,Капот 00774101100000000
4,1040302480,Шайба 8-200HV,30,JB/T96.1,Капот 00774101100000000
5,00773601100001020,Регулирующая шайбаTp20,6,NaN,Капот 00774101100000000
6,1040201089,Гайка M8-8,12,JB/T6170,Капот 00774101100000000
7,1040004678,Болт для ограничителя открывания \r\nдвери M10×70,4,NaN,Капот 00774101100000000
8,1040200113,Гайка M10-8,26,JB/T6170,Капот 00774101100000000
9,00774000800800000,Кронштейн дверного упора Ⅰ,1,NaN,Капот 00774101100000000
10,1040302529,Шайба 5-200HV,2,JB/T96.1,Капот 00774101100000000
11,1040001122,"Болт M5×16-8,8",2,JB/T5783,Капот 00774101100000000
12,1040004519,"Болт M8×25-8,8",12,JB/T5783,Капот 00774101100000000
13,1040100105,"Винт с внутренним шестигранником \r\nM6 × 25-8,8",1,JB/T70.1,Капот 00774101100000000
14,00774001100601010,Круглая сталь Φ10,2,NaN,Капот 00774101100000000
15,1040002435,Болт M10×35-8.8,2,JB/T5783,Капот 00774101100000000
16,1040302512,Шайба 10-200HV,4,JB/T96.1,Капот 00774101100000000
17,00774001100601020,Левая стопорная пластина TP5,1,NaN,Капот 00774101100000000
18,1040300771,Шайба 6-200HV,6,JB/T97.1,Капот 00774101100000000
19,00774001100001020,Правая шарнира замка,1,000815,Капот 00774101100000000
20,1109900765,Гидравлический дверной замок,1,50075-C37K,Капот 00774101100000000
21,1020605390,"Удлинение пневматической пружины \r\n435mm,S=1...",8,000815,Капот 00774101100000000
22,1100700163,Дверная ручка,2,26983-09,Капот 00774101100000000
23,00774101100400000,Сварка правого капота,1,NaN,Капот 00774101100000000
24,00774101100200000,Сварка левого капота,1,NaN,Капот 00774101100000000
25,1040200504,Гайка M10-8,6,JB/T889.1,Капот 00774101100000000
26,00771401111801020,Круглая сталь Φ10,1,NaN,Капот 00774101100000000
27,00771401112401010,Опорная плита замка Tp6,1,NaN,Капот 00774101100000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00771401110001071,Регулирующая шайбаTp2,4,NaN,Капот 00774101100000000
1,1040004509,Болт M10×50-8.8,2,JB/T5783,Капот 00774101100000000
2,1109900766,Дверной замок аккумулятора,1,50076-C38K,Капот 00774101100000000
3,00774001100001010,Левая подставка замкаTp6,1,NaN,Капот 00774101100000000
4,00774000801000000,Кронштейн останова двери II,1,NaN,Капот 00774101100000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00774101000001011,Блок противовеса,1,NaN,Балансир 00774101000000000
1,00774101000001021,Блок противовеса,2,NaN,Балансир 00774101000000000
2,1040302483,Шайба 24-200HV,4,JB/T96.1,Балансир 00774101000000000
3,1040004613,Болт M24×60-10.9,4,JB/T5782,Балансир 00774101000000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1031500371,Поворотная опораm=8，z=130,1,NaN,Поворотный механизм 00771600900000000
1,1040005853,Болт M20×140-10.9,60,JB/T1228,Поворотный механизм 00771600900000000
2,1040302502,Шайба 20,65,JB/T1230,Поворотный механизм 00771600900000000
3,1040004501,Болт M20×60-10.9,5,JB/T5783,Поворотный механизм 00771600900000000
4,1030202324,Поворотный редуктор,1,NaN,Поворотный механизм 00771600900000000
5,1040301503,m=8，z=17，×=+0.5,2,JB/T93,Поворотный механизм 00771600900000000
6,1040004029,Болт M12×35-10.9,2,JB/T5783,Поворотный механизм 00771600900000000
7,1010101004,Поворотный мотор,1,NaN,Поворотный механизм 00771600900000000
8,00771400900001010,Фиксирующий штифт,1,NaN,Поворотный механизм 00771600900000000

,Код материалов,Наименование и спецификация,Unnamed: 3,Кол-во Примечание,Section
0,1040100421,"Винт M8×20-8,8",8.0,JB/T70.3,Шасси в сборе 00774102800000000
1,00771602802200000,Внутренний палец цилиндра рулевого \r\nуправления,4.0,NaN,Шасси в сборе 00774102800000000
2,00773400300001070,NaN,NaN,NaN,Шасси в сборе 00774102800000000
4,00771602800001450,Втулка цилиндра рулевого управления,4.0,NaN,Шасси в сборе 00774102800000000
5,00771602801000000,Гидроцилиндр рулевого управления,4.0,NaN,Шасси в сборе 00774102800000000
6,00771602800601050,Направляющий блок,8.0,NaN,Шасси в сборе 00774102800000000
7,1040102761,Винт,16.0,JB/T70.1,Шасси в сборе 00774102800000000
8,00771602800001390,Крышка выносной опоры,4.0,NaN,Шасси в сборе 00774102800000000
9,00774002800001270,Скоба штыря,8.0,NaN,Шасси в сборе 00774102800000000
10,00771602800001120,Нижний шкворень поворотного управления,4.0,NaN,Шасси в сборе 00774102800000000
11,00771602800001130,Нижняя крышка,4.0,NaN,Шасси в сборе 00774102800000000
12,1040002434,"Болт M10×25-8,8",64.0,JB/T5783,Шасси в сборе 00774102800000000
13,1030800680,Шина,2.0,NaN,Шасси в сборе 00774102800000000
14,1040201907,"Шестигранная фланцевая гайка M22 × 1,5-10",40.0,JB/T6177.2,Шасси в сборе 00774102800000000
15,1030202306,Ходовой редуктор,4.0,NaN,Шасси в сборе 00774102800000000
16,1040302492,Шайба 16-200HV,72.0,JB/T97.1,Шасси в сборе 00774102800000000
17,1040101980,Винт M16×50-10.9-DKL,72.0,JB/T70.1,Шасси в сборе 00774102800000000
18,00771602802000001,Сварной элемент поворотной тележки,4.0,NaN,Шасси в сборе 00774102800000000
19,00771602800001020,Износостойкая прокладка,8.0,NaN,Шасси в сборе 00774102800000000
20,00771602800001470,NaN,NaN,NaN,Шасси в сборе 00774102800000000
22,00771602800001010,Верхний шкворень поворотного управления,4.0,NaN,Шасси в сборе 00774102800000000
23,00771602800001190,NaN,NaN,NaN,Шасси в сборе 00774102800000000
25,1040302489,Шайба 10-200HV,146.0,JB/T97.1,Шасси в сборе 00774102800000000
26,00773400200001070,Стопорный штифт,4.0,NaN,Шасси в сборе 00774102800000000
27,00771602800001180,Монтажная подставка датчика,4.0,NaN,Шасси в сборе 00774102800000000
28,00771602800001201,Крышка,4.0,NaN,Шасси в сборе 00774102800000000
29,1040100857,"Винт M6×15-8,8",20.0,JB/T70.1,Шасси в сборе 00774102800000000
30,00772102800600000,Защитный кожух,4.0,NaN,Шасси в сборе 00774102800000000
31,1040300771,Шайба 6-200HV,68.0,JB/T97.1,Шасси в сборе 00774102800000000
32,1040002555,Болт M10×16-A2-70,12.0,JB/T5783,Шасси в сборе 00774102800000000
33,00771602800001080 Штифт цилиндра рулевого упр...,NaN,4.0,NaN,Шасси в сборе 00774102800000000
34,1040004511,"Болт M12×30-8,8",4.0,JB/T5783,Шасси в сборе 00774102800000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040002464,"Болт M16×50-8,8",4.0,JB/T5782,Шасси в сборе 00774102800000000
1,00773400400001250,Стопорный штифт,4.0,NaN,Шасси в сборе 00774102800000000
2,00771602800001460,Втулка плавающего цилиндра,2.0,NaN,Шасси в сборе 00774102800000000
3,00771602800001410,Износостойкая прокладка вала качания,2.0,NaN,Шасси в сборе 00774102800000000
4,1040004499,"Болт M20×45-8,8",1.0,JB/T5783,Шасси в сборе 00774102800000000
5,00773400400001170,Стопорный штифт,1.0,NaN,Шасси в сборе 00774102800000000
6,00771602801400000,Плавающий цилиндр,2.0,NaN,Шасси в сборе 00774102800000000
7,00771602800001350,"Подшипник, не требующий смазывания III",2.0,NaN,Шасси в сборе 00774102800000000
8,00771602800001140,Штырь качания,1.0,NaN,Шасси в сборе 00774102800000000
9,00771602800001241,Регулировочная прокладка на опоре II,12.0,NaN,Шасси в сборе 00774102800000000
10,00771602804000000,Узел сухаря качающейся рамы,2.0,NaN,Шасси в сборе 00774102800000000
11,00771602800001260,Кожух шасси II,1.0,NaN,Шасси в сборе 00774102800000000
12,00774102800001010,Кожух шасси I,1.0,NaN,Шасси в сборе 00774102800000000
13,00774102800001020,Штифт плавающего цилиндра,2.0,NaN,Шасси в сборе 00774102800000000
14,1040004517,"Болт M8×16-8,8",90.0,JB/T5783,Шасси в сборе 00774102800000000
15,00771602800001290,Кожух шасси V,1.0,NaN,Шасси в сборе 00774102800000000
16,00771602800001431,Регулирующая \r\nпрокладка \r\nсухаря \r\nкача...,4.0,NaN,Шасси в сборе 00774102800000000
17,00771602800001400,Крышка рамы III,1.0,NaN,Шасси в сборе 00774102800000000
18,00774102800200000,Сварная деталь рамы,1.0,NaN,Шасси в сборе 00774102800000000
19,1030800681,Шина,2.0,NaN,Шасси в сборе 00774102800000000
20,00774102800400000,Вертикальное подъемное устройство,1.0,NaN,Шасси в сборе 00774102800000000
21,00771602800001380,Крышка рамы II,4.0,NaN,Шасси в сборе 00774102800000000
22,1040004508,"Болт M10×45-8,8",6.0,JB/T5783,Шасси в сборе 00774102800000000
23,00771602800001370,Крышка рамы I,4.0,NaN,Шасси в сборе 00774102800000000
24,204050239,Синтетическое трансмиссионное масло \r\nMobil ...,NaN,NaN,Шасси в сборе 00774102800000000
25,00771602800001440,Опорная рама клапана IV,1.0,NaN,Шасси в сборе 00774102800000000
26,1040002178,Болт M10×30-A2-70,4.0,JB/T70.1,Шасси в сборе 00774102800000000
27,00771602800201530,Прокладка износостойкой плиты,2.0,NaN,Шасси в сборе 00774102800000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1000000735,Дизельный двигатель,1,NaN,Двигатель（Камминз）00774107100200000
1,1040201896,Гайка M6-8,4,JB/T889,Двигатель（Камминз）00774107100200000
2,1040002178,Болт M6×30-A2-70,4,JB/T5783,Двигатель（Камминз）00774107100200000
3,00774007100201060,Монтажная планка ЭБУ,1,NaN,Двигатель（Камминз）00774107100200000
4,1040301515,Шайба 8-200HV,4,JB/T97.1,Двигатель（Камминз）00774107100200000
5,1040004518,"Болт M8×20-8,8",4,JB/T5783,Двигатель（Камминз）00774107100200000
6,00771407120201030,Изогнута пластинка III,1,NaN,Двигатель（Камминз）00774107100200000
7,00771407120201020,Гнутая пластина II,1,NaN,Двигатель（Камминз）00774107100200000
8,1030400480,Пружинная муфта в сборе,1,NaN,Двигатель（Камминз）00774107100200000
9,1040004033,Болт M10×25-10.9,8,JB/T5783,Двигатель（Камминз）00774107100200000
10,00771407120201050,Крышка муфты,1,NaN,Двигатель（Камминз）00774107100200000
11,1040302489,Шайба 10-200HV,12,JB/T97.1,Двигатель（Камминз）00774107100200000
12,1040002435,Болт M10×35-8.8,12,JB/T5783,Двигатель（Камминз）00774107100200000
13,00774000800400000,Кронштейн двигателя,1,NaN,Двигатель（Камминз）00774107100200000
14,1040200161,Гайка M16 -8,4,JB/T889,Двигатель（Камминз）00774107100200000
15,00773407100201050,Подкладка,4,NaN,Двигатель（Камминз）00774107100200000
16,1009900942,Амортизатор двигателя,8,NaN,Двигатель（Камминз）00774107100200000
17,00774007100201010,Гнутая пластина I,1,NaN,Двигатель（Камминз）00774107100200000
18,00774007100201040,Гнутая пластина IV,1,NaN,Двигатель（Камминз）00774107100200000
19,1040004653,"Болт M12×30-10,9",16,JB/T5783,Двигатель（Камминз）00774107100200000
20,1040302490,Шайба 12-200HV,16,JB/T97.1,Двигатель（Камминз）00774107100200000
21,1040302492,Шайба 16-200HV,4,JB/T97.1,Двигатель（Камминз）00774107100200000
22,1040003912,"Болт M16×120-10,9-DKL",4,JB/T5783,Двигатель（Камминз）00774107100200000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040200503,Гайка M8-8,8,JB/T889.1,Система топлива00774107100400000
1,00774007100401010,Гнутая пластина I,1,NaN,Система топлива00774107100400000
2,1040301515,Шайба 8-200HV,7,JB/T97.1,Система топлива00774107100400000
3,1040004619,"Болт M8×35-8,8",2,JB/T5783,Система топлива00774107100400000
4,1140114594,Быстросъемная муфта,2,NaN,Система топлива00774107100400000
5,00773407100401060,"Болт пустотелый М16 × 1,5 × 35",2,NaN,Система топлива00774107100400000
6,00774107100401030,Труба топлива II,1,NaN,Система топлива00774107100400000
7,00773407100401050,Штуцер II,2,NaN,Система топлива00774107100400000
8,1081000673,Сложная уплотнительная шайба,4,NaN,Система топлива00774107100400000
9,00773607100401010,Бак топлива в сборе,1,NaN,Система топлива00774107100400000
10,1040302512,Шайба 10-200HV,4,JB/T96.1,Система топлива00774107100400000
11,1040002434,Болт M10×25-8.8,4,JB/T5783,Система топлива00774107100400000
12,1040302480,Шайба 8-200HV,4,JB/T96.1,Система топлива00774107100400000
13,1029902994,Бандажная лента,5,CHS-4*200(че\r\nрный),Система топлива00774107100400000
14,1990200692,Резиновая \r\nлента \r\nс \r\nпластическим \r\...,3,NaN,Система топлива00774107100400000
15,1040300771,Шайба 6-200HV,3,JB/T97.1,Система топлива00774107100400000
16,1040005844,Болт M6×10-A2-70,3,JB/T5783,Система топлива00774107100400000
17,00774107100401042,Труба топлива III,1,NaN,Система топлива00774107100400000
18,1140114596,Быстросъемная муфта,1,NaN,Система топлива00774107100400000
19,1140114593,Быстросъемная муфта,1,NaN,Система топлива00774107100400000
20,1990202279,Хомут спирального червяка,8,NaN,Система топлива00774107100400000
21,00774107100401081,Труба топлива V,1,NaN,Система топлива00774107100400000
22,00774107100401062,Труба топлива IV,1,NaN,Система топлива00774107100400000
23,1040004518,"Болт M8×20-8,8",3,JB/T5783,Система топлива00774107100400000
24,1040002458,"Болт M8×40-8,8",2,JB/T5783,Система топлива00774107100400000

,№\r\n п/п,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1,00771407120601180,Пластина II,2,NaN,Cистема отвода тепла 00774107100600000
1,2,00771407120601170,Планка I,2,NaN,Cистема отвода тепла 00774107100600000
2,3,00774107100601150,Ветроотбойник,1,NaN,Cистема отвода тепла 00774107100600000
3,4,00771407120601140,Гнутая пластина IV,2,NaN,Cистема отвода тепла 00774107100600000
4,5,00771407120601190,Планка III,2,NaN,Cистема отвода тепла 00774107100600000
5,6,1040004619,"Болт M8×35-8,8",4,JB/T5783,Cистема отвода тепла 00774107100600000
6,7,1040004517,"Болт M8×16-8,8",11,JB/T5783,Cистема отвода тепла 00774107100600000
7,8,00771407120601110,Гнутая пластина I,2,NaN,Cистема отвода тепла 00774107100600000
8,9,1000300735,Расширительный бак,1,NaN,Cистема отвода тепла 00774107100600000
9,10,1040200398,Гайка M8-8,22,JB/T6177.1,Cистема отвода тепла 00774107100600000
10,11,1000300776,Радиатор в сборе,1,NaN,Cистема отвода тепла 00774107100600000
11,12,1990202279,Хомут спирального червяка,4,NaN,Cистема отвода тепла 00774107100600000
12,13,00771607120601050,Паровой рукав I,1,NaN,Cистема отвода тепла 00774107100600000
13,14,00771607120601060,Паровой рукав II,1,NaN,Cистема отвода тепла 00774107100600000
14,15,00771407120601020,Шланг II,1,NaN,Cистема отвода тепла 00774107100600000
15,16,1000300809,Вентилятор в сборе,1,NaN,Cистема отвода тепла 00774107100600000
16,17,00771607120601040,Труба подпиточной воды,1,NaN,Cистема отвода тепла 00774107100600000
17,18,1040002435,Болт M10×35-8.8,4,JB/T5783,Cистема отвода тепла 00774107100600000
18,19,00771407120601080,Прокладка вентилятора,1,NaN,Cистема отвода тепла 00774107100600000
19,20,1040200504,Гайка M10-8,4,JB/T889.1,Cистема отвода тепла 00774107100600000
20,21,1040302489,Шайба 10-200HV,8,JB/T97.1,Cистема отвода тепла 00774107100600000
21,22,1040004508,Болт M10×45-8.8,4,JB/T5783,Cистема отвода тепла 00774107100600000
22,23,00771407120601100,Соединитель шланга II,1,NaN,Cистема отвода тепла 00774107100600000
23,24,00771407120601010,Обратный водовод,1,NaN,Cистема отвода тепла 00774107100600000
24,25,1990202288,Хомут спирального червяка,3,NaN,Cистема отвода тепла 00774107100600000
25,26,1990202282,Хомут спирального червяка,2,NaN,Cистема отвода тепла 00774107100600000
26,27,00771407120601090,Соединитель шланга I,1,NaN,Cистема отвода тепла 00774107100600000
27,28,1990202287,Хомут спирального червяка,3,NaN,Cистема отвода тепла 00774107100600000
28,29,00771407100601170,Подкладка,6,NaN,Cистема отвода тепла 00774107100600000
29,30,1040002262,"Болт M12×55-10,9",4,JB/T5783,Cистема отвода тепла 00774107100600000
30,31,1040301031,Шайба 12-300HV,4,JB/T96.1,Cистема отвода тепла 00774107100600000
31,32,1040200507,Гайка M12-8,4,JB/T889.1,Cистема отвода тепла 00774107100600000
32,33,00771407120601120,Гнутая пластина II,1,NaN,Cистема отвода тепла 00774107100600000
33,34,00771407120601130,Изогнута пластинка III,1,NaN,Cистема отвода тепла 00774107100600000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040004520,"Болт M8×30-8,8",2,JB/T5783,Cистема отвода тепла 00774007100600000
1,00771407120601160,Гнутая пластина V,1,NaN,Cистема отвода тепла 00774007100600000
2,1040301515,Шайба 8-200HV,33,JB/T97.1,Cистема отвода тепла 00774007100600000
3,1040004519,"Болт M8×25-8,8",16,JB/T5783,Cистема отвода тепла 00774007100600000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00771407120801060,Впускная труба III,1,NaN,Впускная система 00774107100800000
1,1990202290,Хомут спирального червяка,2,NaN,Впускная система 00774107100800000
2,1000100391,Фильтр воздуха в сборе,1,NaN,Впускная система 00774107100800000
3,00771407120801030,Впускная труба II,1,NaN,Впускная система 00774107100800000
4,00771407120801020,Впускная стальная труба,1,NaN,Впускная система 00774107100800000
5,1040004519,"Болт M8×25-8,8",4,JB/T5783,Впускная система 00774107100800000
6,00771407120801050,Гнутая пластина II,1,NaN,Впускная система 00774107100800000
7,00771407120801010,Впускная труба I,1,NaN,Впускная система 00774107100800000
8,1990202289,Хомут спирального червяка,3,NaN,Впускная система 00774107100800000
9,00771407120801040,Гнутая пластина I,1,NaN,Впускная система 00774107100800000
10,1040004619,"Болт M8×35-8,8",2,JB/T5783,Впускная система 00774107100800000
11,1040301515,Шайба 8-200HV,6,JB/T97.1,Впускная система 00774107100800000
12,1040200398,Гайка M8-8,4,JB/T6177.1,Впускная система 00774107100800000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00771407101001020,Выхлопной хвост,1,NaN,Вытяжная система 00774107101000000
1,00774107101001030,Выхлопная втулка,1,NaN,Вытяжная система 00774107101000000
2,00774107101001020,Выхлопная труба II,1,NaN,Вытяжная система 00774107101000000
3,00771407121001060,Герметизирующая прокладка II,1,NaN,Вытяжная система 00774107101000000
4,00771407181001010,Выхлопная труба I,1,NaN,Вытяжная система 00774107101000000
5,00773407151001060,Герметизирующая прокладка,2,NaN,Вытяжная система 00774107101000000
6,00771407181001020,Шумотушитель,1,NaN,Вытяжная система 00774107101000000
7,1040004520,"Болт M8×30-8,8",4,JB/T5783,Вытяжная система 00774107101000000
8,1040302480,Шайба 8-200HV,8,JB/T96.1,Вытяжная система 00774107101000000
9,00770500601001050,Регулировочная шайба,1,NaN,Вытяжная система 00774107101000000
10,00770500601001060,Опора,1,NaN,Вытяжная система 00774107101000000
11,1040004033,Болт M10×25-8.8,6,JB/T5783,Вытяжная система 00774107101000000
12,1040302489,Шайба 10-200HV,6,JB/T97.1,Вытяжная система 00774107101000000
13,1040200398,Гайка M8-8,12,JB/T889.1,Вытяжная система 00774107101000000
14,1040301515,Шайба 8-200HV,12,JB/T97.1,Вытяжная система 00774107101000000
15,1040004619,"Болт M8×35-8,8",8,JB/T5783,Вытяжная система 00774107101000000
16,1040200503,Гайка M8-8,4,JB/T889.1,Вытяжная система 00774107101000000
17,1040004519,"Болт M8×25-8,8",4,JB/T5783,Вытяжная система 00774107101000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040101492,"Винт M10×25-8,8",2,JB/T70.1,Гидравлический бак в сборе 00774105206200000
1,1040302489,Шайба 10-200HV,2,JB/T97.1,Гидравлический бак в сборе 00774105206200000
2,1010601139,Обратный масляный фильтр,1,NaN,Гидравлический бак в сборе 00774105206200000
3,00774105200210000,Корпус масляного бака,1,NaN,Гидравлический бак в сборе 00774105206200000
4,1040002441,"Болт M12×50-8,8",4,JB/T5783,Гидравлический бак в сборе 00774105206200000
5,1140101628,Резьбовая заглушка,1,NaN,Гидравлический бак в сборе 00774105206200000
6,1040302821,Шайба 12-200HV,4,JB/T96.1,Гидравлический бак в сборе 00774105206200000
7,1040004511,"Болт M12×30-8,8",2,JB/T5783,Гидравлический бак в сборе 00774105206200000
8,1149901683,Прямой соединитель,1,NaN,Гидравлический бак в сборе 00774105206200000
9,1140111237,Прямой соединитель,1,NaN,Гидравлический бак в сборе 00774105206200000
10,1140101464,Прямой соединитель,2,NaN,Гидравлический бак в сборе 00774105206200000
11,1140101462,Прямой соединитель,1,NaN,Гидравлический бак в сборе 00774105206200000
12,1140101629,Резьбовая заглушка,1,NaN,Гидравлический бак в сборе 00774105206200000
13,1140105928,Прямой соединитель,1,NaN,Гидравлический бак в сборе 00774105206200000
14,1019901354,Уровнемер-термометр,1,NaN,Гидравлический бак в сборе 00774105206200000
15,00773405200230000,Уплотняющая пластина,1,NaN,Гидравлический бак в сборе 00774105206200000
16,00773405200220001,Крышка люка,1,NaN,Гидравлический бак в сборе 00774105206200000
17,1040103111,Винт M8×16-8.8,8,JB/T70.1,Гидравлический бак в сборе 00774105206200000
18,1040301515,Шайба 8-200HV,8,JB/T97.1,Гидравлический бак в сборе 00774105206200000
19,1010500489,Воздушный фильтр,1,NaN,Гидравлический бак в сборе 00774105206200000
20,1140103362,Прямой соединитель,3,NaN,Гидравлический бак в сборе 00774105206200000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140105072,Прямой соединитель,2,NaN,Гидравлический насос в сборе 00774105203000000
1,1040302490,Шайба 12-200HV,6,JB/T97.1,Гидравлический насос в сборе 00774105203000000
2,1040000575,"Болт M12×35-10,9",6,JB/T5783,Гидравлический насос в сборе 00774105203000000
3,1140103280,Прямой соединитель,1,NaN,Гидравлический насос в сборе 00774105203000000
4,1140101489,Тройной композитный штуцер,2,NaN,Гидравлический насос в сборе 00774105203000000
5,1010002210,Закрытый насос,1,NaN,Гидравлический насос в сборе 00774105203000000
6,1140107814,Штуцер,1,NaN,Гидравлический насос в сборе 00774105203000000
7,1040102730,Винт 1/2×11/2-10.9,4,NaN,Гидравлический насос в сборе 00774105203000000
8,1140101630,Полуфланец,1,NaN,Гидравлический насос в сборе 00774105203000000
9,1010002207,Открытый насос,1,NaN,Гидравлический насос в сборе 00774105203000000
10,1140101564,Полуфланец,1,NaN,Гидравлический насос в сборе 00774105203000000
11,1040102742,Винт 3/8×11/4-10.9,4,NaN,Гидравлический насос в сборе 00774105203000000
12,1140105246,Прямой соединитель,1,NaN,Гидравлический насос в сборе 00774105203000000
13,1140101478,"Прямоугольный композитный \r\nштуцер M22×1,5",1,NaN,Гидравлический насос в сборе 00774105203000000
14,1140114914,Прямой соединитель,2,NaN,Гидравлический насос в сборе 00774105203000000
15,1140101632,"Прямоугольный композитный \r\nштуцер M22×1,5",4,NaN,Гидравлический насос в сборе 00774105203000000
16,1140114915,Прямой удлиненный соединитель,2,NaN,Гидравлический насос в сборе 00774105203000000
17,1010002209,Закрытый насос,1,NaN,Гидравлический насос в сборе 00774105203000000
18,1149901795,Прямой соединитель,2,NaN,Гидравлический насос в сборе 00774105203000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1010100630,Ходовой мотор,1,NaN,Сборка ходового мотора 00774105202000000
1,1140113353,Прямой соединитель,1,NaN,Сборка ходового мотора 00774105202000000
2,1140101478,"Прямоугольный композитный \r\nштуцер M22×1,5",1,NaN,Сборка ходового мотора 00774105202000000
3,1149901795,Прямой соединитель,1,NaN,Сборка ходового мотора 00774105202000000
4,1040302490,Шайба 12-200HV,2,JB/T97.1,Сборка ходового мотора 00774105202000000
5,1040000575,"Болт M12×35-10,9",2,JB/T5783,Сборка ходового мотора 00774105202000000
6,1140101475,"Прямоугольный композитный \r\nштуцер M22×1,5",1,NaN,Сборка ходового мотора 00774105202000000
7,1140108149,Штуцер,1,NaN,Сборка ходового мотора 00774105202000000
8,1140108034,Регулируемый конец \r\nамериканской резьбы 90 ...,1,NaN,Сборка ходового мотора 00774105202000000
9,1149902023,Проходной соединитель \r\nудлинительного конца,1,NaN,Сборка ходового мотора 00774105202000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140101464,Прямой соединитель,10,NaN,Сборка ходового делительного клапана 007741052...
1,1010306669,Ходовой делительный клапан,1,NaN,Сборка ходового делительного клапана 007741052...
2,1040301515,Шайба 8-200HV,4,JB/T97.1,Сборка ходового делительного клапана 007741052...
3,1040004518,"Болт M8×20-8,8",4,JB/T5783,Сборка ходового делительного клапана 007741052...
4,1040301510,Шайба 8,1,JB/T93,Сборка ходового делительного клапана 007741052...
5,1060300302,Комбинированное проходное \r\nпереходное соеди...,1,NaN,Сборка ходового делительного клапана 007741052...
6,1140101489,"Композитный тройник M16×1,5",2,NaN,Сборка ходового делительного клапана 007741052...
7,1140101478,"Прямоугольный композитный штуцер \r\nM22×1,5",1,NaN,Сборка ходового делительного клапана 007741052...
8,1140101470,Торцевой проходной соединитель \r\nG3/4/M24×1.5,4,NaN,Сборка ходового делительного клапана 007741052...
9,1140111237,Прямой соединитель,1,NaN,Сборка ходового делительного клапана 007741052...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140102959,Горизонтально-вертикальное \r\nсоединение,4,NaN,Сборка клапан ходового управления 007741052024...
1,1140107801,Штуцер,2,NaN,Сборка клапан ходового управления 007741052024...
2,1149900295,Переходное соединение,2,NaN,Сборка клапан ходового управления 007741052024...
3,1010306670,Клапан ходового управления,1,NaN,Сборка клапан ходового управления 007741052024...
4,1040301515,Шайба 8-200HV,4,JB/T97.1,Сборка клапан ходового управления 007741052024...
5,1040004518,"Болт M8×20-8,8",4,JB/T5783,Сборка клапан ходового управления 007741052024...
6,1040301510,Шайба 8,4,JB/T93,Сборка клапан ходового управления 007741052024...
7,1140114187,Манометрический штуцер,1,NaN,Сборка клапан ходового управления 007741052024...
8,1140111237,Прямой соединитель,5,NaN,Сборка клапан ходового управления 007741052024...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1010306667,Расширительный клапан \r\nрулевого управления,1,NaN,Сборка расширительного клапана рулевого управл...
1,1040301515,Шайба 8-200HV,8,JB/T97.1,Сборка расширительного клапана рулевого управл...
2,1040004518,"Болт M8×20-8,8",8,JB/T5783,Сборка расширительного клапана рулевого управл...
3,1140111237,Прямой соединитель,2,NaN,Сборка расширительного клапана рулевого управл...
4,1010306668,Расширительный клапан \r\nрулевого управления,1,NaN,Сборка расширительного клапана рулевого управл...
5,1140102936,Торцевой проходной соединитель \r\nG3/2/M16×1.5,2,NaN,Сборка расширительного клапана рулевого управл...
6,1140114187,Соединитель для измерения \r\nдавления,1,NaN,Сборка расширительного клапана рулевого управл...
7,1140101463,Торцевой проходной соединитель \r\nG3/2/M18×1.5,2,NaN,Сборка расширительного клапана рулевого управл...
8,1140101477,"Прямоугольный композитный \r\nштуцер M18×1,5",1,NaN,Сборка расширительного клапана рулевого управл...
9,1140102959,Горизонтально-вертикальное \r\nсоединение,1,NaN,Сборка расширительного клапана рулевого управл...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040301515,Шайба 8-200HV,4,JB/T97.1,Балансировочный клапан цилиндра00774105204400000
1,1040301510,Шайба 8,4,JB/T93,Балансировочный клапан цилиндра00774105204400000
2,1040004521,"Болт M8×45-8,8",4,JB/T5783,Балансировочный клапан цилиндра00774105204400000
3,1140108469,Штуцер,2,NaN,Балансировочный клапан цилиндра00774105204400000
4,1140101475,"Прямоугольный композитный \r\nштуцер M22×1,5",2,NaN,Балансировочный клапан цилиндра00774105204400000
5,1010306020,Балансировочный клапан,1,NaN,Балансировочный клапан цилиндра00774105204400000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140101534,Прямоугольный композитный \r\nштуцер M22×2,2,NaN,Сборка фильтра00774105203600000
1,1010305956,Обратный клапан с прямым \r\nсоединителем,1,NaN,Сборка фильтра00774105203600000
2,1040302489,Шайба 10-200HV,4,JB/T97.1,Сборка фильтра00774105203600000
3,1040002433,Болт M10×20-8.8,4,JB/T5783,Сборка фильтра00774105203600000
4,1040004518,"Болт M8×20-8,8",4,JB/T5783,Сборка фильтра00774105203600000
5,1040301515,Шайба 8-200HV,4,JB/T97.1,Сборка фильтра00774105203600000
6,1140101523,Торцевой проходной соединитель \r\nG3/4/M30×2,1,NaN,Сборка фильтра00774105203600000
7,1140101478,"Прямоугольный композитный \r\nштуцер M22×1,5",2,NaN,Сборка фильтра00774105203600000
8,1140114045,Гидравлический штуцер \r\nM22×1.5-G3/4,2,NaN,Сборка фильтра00774105203600000
9,1010601137,Фильтр высокого давления,1,NaN,Сборка фильтра00774105203600000
10,1010601369,Подпиточный фильтр,1,NaN,Сборка фильтра00774105203600000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040302489,Шайба 10-200HV,2,JB/T97.1,Сборка аварийного насоса с приводом от электро...
1,1040004646,Болт M10×15-8.8,2,JB/T5783,Сборка аварийного насоса с приводом от электро...
2,1140101901,Прямой соединитель,1,NaN,Сборка аварийного насоса с приводом от электро...
3,1010002361,Аварийный насос,1,NaN,Сборка аварийного насоса с приводом от электро...
4,1140103135,"Прямоугольный композитный \r\nштуцер M22×1,5",1,NaN,Сборка аварийного насоса с приводом от электро...
5,1140103405,Прямой соединитель,2,JB/T15783,Сборка аварийного насоса с приводом от электро...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1010307142,Регулирующий и \r\nбалансировочный клапан,1,NaN,Балансировочный клапан верхнего гидроцилиндра ...
1,1140114700,Прямой удлиненный соединитель,2,NaN,Балансировочный клапан верхнего гидроцилиндра ...
2,1040103114,Винт M8×45-8.8,4,JB/T70.1,Балансировочный клапан верхнего гидроцилиндра ...
3,1040301510,Шайба 8,4,JB/T93,Балансировочный клапан верхнего гидроцилиндра ...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1010307623,Электромагнитный клапан,1.0,NaN,Сборка электромагнитного клапана00774105206000000
1,1140101478,"Прямоугольный композитный \r\nштуцер M22×1,5",3.0,NaN,Сборка электромагнитного клапана00774105206000000
2,1010307624,Электромагнитный клапан,3.0,NaN,Сборка электромагнитного клапана00774105206000000
3,1040200506,Гайка M6-8,8.0,JB/T889.1,Сборка электромагнитного клапана00774105206000000
4,1140101477,"Прямоугольный композитный \r\nштуцер M18×1,5",1.0,NaN,Сборка электромагнитного клапана00774105206000000
5,1140101463,Концевое проходное соединение \r\nM8×70-8.8,2.0,NaN,Сборка электромагнитного клапана00774105206000000
6,1040002803,"Болт M6×50-8,8",NaN,JB/T5782,Сборка электромагнитного клапана00774105206000000
7,1140101464,Торцевой проходной соединитель \r\nG3/2/M22×1.5,5.0,NaN,Сборка электромагнитного клапана00774105206000000
8,1140102812,Прямой соединитель,1.0,NaN,Сборка электромагнитного клапана00774105206000000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140101477,"Прямоугольный композитный \r\nштуцер M18×1,5",1.0,NaN,Монтаж гидравлических частей платформы00774105...
1,1140101463,Торцевой проходной соединитель \r\nG3/2/M18×1.5,2.0,NaN,Монтаж гидравлических частей платформы00774105...
2,1040004516,"Болт M8×15-8,8",4.0,JB/T5783,Монтаж гидравлических частей платформы00774105...
3,1040301510,Шайба 8,8.0,JB/T93,Монтаж гидравлических частей платформы00774105...
4,1010601138,Фильтр высокого давления,1.0,NaN,Монтаж гидравлических частей платформы00774105...
5,1140113796,Композитный штуцер,1.0,NaN,Монтаж гидравлических частей платформы00774105...
6,1010307141,Клапан управления платформой,1.0,NaN,Монтаж гидравлических частей платформы00774105...
7,1140111237,Прямой соединитель,4.0,NaN,Монтаж гидравлических частей платформы00774105...
8,1140101465,Торцевой проходной соединитель \r\nG3/8/M22×1.5,1.0,NaN,Монтаж гидравлических частей платформы00774105...
9,1140101462,Торцевой проходной соединитель \r\nG3/8/M18×1.5,1.0,NaN,Монтаж гидравлических частей платформы00774105...
10,1140101461,Торцевой проходной соединитель \r\nG3/4/M16×1.5,2.0,NaN,Монтаж гидравлических частей платформы00774105...
11,1040301515,Шайба 8-200HV,NaN,JB/T97.1,Монтаж гидравлических частей платформы00774105...
12,1040004518,"Болт M8×20-8,8",NaN,JB/T5783,Монтаж гидравлических частей платформы00774105...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040004599,"Болт M8×60-8,8",4,JB/T5782,Сборка плавающего балансировочного клапана0077...
1,1040301510,Шайба 8,4,JB/T93,Сборка плавающего балансировочного клапана0077...
2,1040301515,Шайба 8-200HV,4,JB/T97.1,Сборка плавающего балансировочного клапана0077...
3,1010306736,Плывущий балансировочный \r\nклапан,1,NaN,Сборка плавающего балансировочного клапана0077...
4,1140101475,"Прямоугольный композитный \r\nштуцер M22×1,5",1,NaN,Сборка плавающего балансировочного клапана0077...
5,1140111237,Прямой соединитель,1,NaN,Сборка плавающего балансировочного клапана0077...
6,1140101465,Торцевой проходной соединитель \r\nG3/8/M22×1.5,1,NaN,Сборка плавающего балансировочного клапана0077...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040100148,Винт M8×45-8.8,4,JB/T5783,Сборка балансировочного клапана цилиндра007741...
1,1040301510,Шайба 8,4,JB/T93,Сборка балансировочного клапана цилиндра007741...
2,1010306020,Балансировочный клапан,1,NaN,Сборка балансировочного клапана цилиндра007741...
3,1140114839,Шарнирное соединение,2,NaN,Сборка балансировочного клапана цилиндра007741...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140101479,"Прямоугольный \r\nкомпозитный \r\nштуцер M22×1,5",1,NaN,Сборка балансировочного клапана выдвижения и в...
1,1140101478,"Прямоугольный \r\nкомпозитный \r\nштуцер M22×1,5",1,NaN,Сборка балансировочного клапана выдвижения и в...
2,1140102812,Прямой соединитель,1,NaN,Сборка балансировочного клапана выдвижения и в...
3,1140101464,Торцевой проходной соединитель \r\nG3/2/M22×1.5,1,NaN,Сборка балансировочного клапана выдвижения и в...
4,1040102739,Винт M8×60-8.8,4,JB/T70.1,Сборка балансировочного клапана выдвижения и в...
5,1010306995,Балансировочный \r\nклапан \r\nвыдвижения-втяг...,1,NaN,Сборка балансировочного клапана выдвижения и в...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040102739,Винт M8×60-8.8,4,JB/T70.1,Сборка уравновешивающего клапана изменения выл...
1,1140101464,Торцевой проходной соединитель \r\nG3/2/M22×1.5,2,NaN,Сборка уравновешивающего клапана изменения выл...
2,1010308099,Амплитудный \r\nбалансировочный \r\nклапан,1,NaN,Сборка уравновешивающего клапана изменения выл...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040004521,"Болт M8×45-8,8",4,JB/T5783,Балансировочный клапан гидроцилиндра башенной ...
1,1040301510,Шайба 8,4,JB/T93,Балансировочный клапан гидроцилиндра башенной ...
2,1040301515,Шайба 8-200HV,4,JB/T97.1,Балансировочный клапан гидроцилиндра башенной ...
3,1140101465,Торцевой проходной соединитель \r\nG3/8/M22×1.5,2,NaN,Балансировочный клапан гидроцилиндра башенной ...
4,1010306020,Балансировочный клапан,1,NaN,Балансировочный клапан гидроцилиндра башенной ...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140101464,Торцевой проходной соединитель \r\nG3/2/M22×1.5,2,NaN,Сборка одностороннего балансировочного клапана...
1,1140101478,"Прямоугольный композитный \r\nштуцер M22×1,5",2,NaN,Сборка одностороннего балансировочного клапана...
2,1040102738,Винт M8×55-8.8,4,JB/T70.1,Сборка одностороннего балансировочного клапана...
3,1010307434,Балансировочный клапан,1,NaN,Сборка одностороннего балансировочного клапана...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1040004644,"Болт M12×45-10,9",4,JB/T5783,Центрально-вращающееся соединение в сборе 0077...
1,1140101527,Торцевой проходной соединитель \r\nG3/2/M24×1.5,8,NaN,Центрально-вращающееся соединение в сборе 0077...
2,1040302490,Шайба 12-200HV,4,JB/T97.1,Центрально-вращающееся соединение в сборе 0077...
3,1011200183,Центрально-вращающееся \r\nсоединение,1,NaN,Центрально-вращающееся соединение в сборе 0077...
4,1140101464,Торцевой проходной соединитель \r\nG3/2/M22×1.5,4,NaN,Центрально-вращающееся соединение в сборе 0077...
5,1140101484,"Композитный тройник M16×1,5",1,NaN,Центрально-вращающееся соединение в сборе 0077...
6,1140101793,"Композитный тройник M16×1,5",1,NaN,Центрально-вращающееся соединение в сборе 0077...
7,1140101941,Торцевой проходной соединитель \r\nG3/8/M16×1.5,2,NaN,Центрально-вращающееся соединение в сборе 0077...
8,1140111291,Тройной композитный штуцер,1,NaN,Центрально-вращающееся соединение в сборе 0077...
9,1140101463,Торцевой проходной соединитель \r\nG3/2/M18×1.5,1,NaN,Центрально-вращающееся соединение в сборе 0077...
10,1140111237,Прямой соединитель,1,NaN,Центрально-вращающееся соединение в сборе 0077...
11,1040300054,Шайба 12,4,JB/T93,Центрально-вращающееся соединение в сборе 0077...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140103283,Тройной композитный штуцер,1,NaN,Масляный радиатор 00774105203200000
1,1140105928,Концевое проходное соединение \r\nφ22-G1/2A,2,NaN,Масляный радиатор 00774105203200000
2,1010400309,Радиатор,1,NaN,Масляный радиатор 00774105203200000
3,1040004517,"Болт M8×16-8,8",4,JB/T5783,Масляный радиатор 00774105203200000
4,1040301515,Шайба 8-200HV,4,JB/T97.1,Масляный радиатор 00774105203200000

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1140111237,Прямой соединитель,1,NaN,Сборка поворотного балансировочного клапана007...
1,1010306674,Поворотный \r\nбалансировочный \r\nклапан,1,NaN,Сборка поворотного балансировочного клапана007...
2,1140101475,Прямоугольный \r\nкомпозитный \r\nштуцер,1,NaN,Сборка поворотного балансировочного клапана007...
3,1140101813,Прямой соединитель,1,NaN,Сборка поворотного балансировочного клапана007...
4,1140101463,Торцевой проходной соединитель \r\nG3/2/M18×1.5,2,JB/T97.1,Сборка поворотного балансировочного клапана007...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1029906298,Правой концевой выключатель втягивания \r\nбаш...,1,NaN,Пучок кабеля поворотной платформы 007741062002...
1,1021404019,Датчик наклона кузова,1,NaN,Пучок кабеля поворотной платформы 007741062002...
2,1029906298,Положительный полюс аккумулятора,1,NaN,Пучок кабеля поворотной платформы 007741062002...
3,00774006200230020,Болт металлизации,1,NaN,Пучок кабеля поворотной платформы 007741062002...
6,1029906298,Реле насоса вспомогательной силовой установки,1,NaN,Пучок кабеля поворотной платформы 007741062002...
7,/,Реле насоса вспомогательной силовой установки,1,NaN,Пучок кабеля поворотной платформы 007741062002...
8,/,Штепсель скользящего кольца 1,1,NaN,Пучок кабеля поворотной платформы 007741062002...
9,/,Штепсель скользящего кольца 2,1,NaN,Пучок кабеля поворотной платформы 007741062002...
10,/,Предохранительный клапан поворота поворотной \...,1,NaN,Пучок кабеля поворотной платформы 007741062002...
11,/,Концевой выключатель угла поворотной \r\nплатф...,1,NaN,Пучок кабеля поворотной платформы 007741062002...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00774106200230010,Пучок кабеля поворотной \r\nплатформы,1,NaN,Пучок кабелей ECU 00774106200230020
3,/,Реле подогревателя,/,NaN,Пучок кабелей ECU 00774106200230020
4,/,Реле подогревателя,/,NaN,Пучок кабелей ECU 00774106200230020
5,/,Диагностика двигателя,/,NaN,Пучок кабелей ECU 00774106200230020
6,/,Оконечное сопротивление,/,NaN,Пучок кабелей ECU 00774106200230020
7,/,Клапан движения вперед 1,/,NaN,Пучок кабелей ECU 00774106200230020
8,/,Клапан движения назад 1,/,NaN,Пучок кабелей ECU 00774106200230020
9,/,Реле пускового мотора,/,NaN,Пучок кабелей ECU 00774106200230020
10,/,Вставка ЭБУ,/,NaN,Пучок кабелей ECU 00774106200230020
11,/,Возбуждение двигателя,/,NaN,Пучок кабелей ECU 00774106200230020
13,/,Уровень охлаждающей жидкости,/,NaN,Пучок кабелей ECU 00774106200230020

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,/,Верхняя вставка кабеля буксирной \r\nцепи баше...,/,NaN,Пучок кабеля стрелы 00774106200230030
1,1029906298,Концевой выключатель контроля \r\nполного втяг...,1,NaN,Пучок кабеля стрелы 00774106200230030
2,1021404018,Двухугольный датчик угла наклона,1,NaN,Пучок кабеля стрелы 00774106200230030
3,1029906298,Концевой выключатель контроля \r\nполного втяг...,1,NaN,Пучок кабеля стрелы 00774106200230030
4,1029906298,Концевой выключатель контроля \r\nполного выдв...,1,NaN,Пучок кабеля стрелы 00774106200230030
5,/,Нижняя вставка кабеля буксирной \r\nцепи башен...,/,NaN,Пучок кабеля стрелы 00774106200230030

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,00774006200210000,Электрический шкаф управления \r\nплатформой,1,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
1,00773406200210000,Электрический шкаф управления \r\nплатформой,0,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
2,1020521022,Переключатель защиты от \r\nсдавливания,1,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
3,/,Клапан подъема маховой стрелы,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
4,/,Клапан левого качания платформы,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
5,/,Клапан опускания при \r\nвыравнивании,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
6,/,Клапан опускания телескопической \r\nстрелы,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
7,/,Клапан правого качания платформы,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
8,/,Клапан повышения при \r\nвыравнивании,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
9,1021404016,Педальный переключатель \r\nплатформы,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...
13,/,Кабель буксирной цепи основной \r\nстрелы,/,NaN,Пучок кабеля платформы 00774106200230040 Модиф...

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section
0,1020903397,Аккумулятор,1,NaN,Питательный провод 00774106200230050
1,1020605356,Кольцевой предохранитель,2,NaN,Питательный провод 00774106200230050
2,0067220632181001A-c,Опора кольцевого предохранителя,2,NaN,Питательный провод 00774106200230050
3,1020402443,Изоляционная гайка,2,NaN,Питательный провод 00774106200230050
4,00774106200234040,Соединительная линия между \r\nвспомогательным...,1,NaN,Питательный провод 00774106200230050
5,00774106200234050,Провод от положительного полюса \r\nаккумулято...,1,NaN,Питательный провод 00774106200230050
6,00774006200234020,Соединительный провод от \r\nотрицательного по...,1,NaN,Питательный провод 00774106200230050
7,1029900667,Ручной переключатель,1,NaN,Питательный провод 00774106200230050
8,00774106200234030,Соединительный провод от ручного \r\nпереключа...,1,NaN,Питательный провод 00774106200230050
9,00774106200234070,Соединительный провод между \r\nдвигателем и м...,1,NaN,Питательный провод 00774106200230050
10,/,Болт металлизации,1,NaN,Питательный провод 00774106200230050
11,00774006200234090,Соединительный провод между реле \r\nи подогре...,/,NaN,Питательный провод 00774106200230050
12,1020005456,Контактор постоянного тока,1,NaN,Питательный провод 00774106200230050
13,00774006200234060,Пусковой мотор соединяется с \r\nгенератором,1,NaN,Питательный провод 00774106200230050
14,00774106200234010,Соединительный провод между \r\nаккумулятором ...,1,NaN,Питательный провод 00774106200230050

,Код материалов,Наименование и \r\nспецификация,Кол-\r\nво,Примечание,Section,Наименование и спецификация,Кол-во,Примечани\r\nе,Количество,Кол-во Примечание,Unnamed: 4,Unnamed: 3,Кол-во Примечание,№\r\n п/п
0,1040200503,Гайка,2.0,JB/T889.1,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1040302480,Шайба 8-200HV,4.0,JB/T96.1,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00773400100261050,Подшипник,2.0,NaN,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00773400100261060,Болт φ22,2.0,NaN,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00773400100260020,Защитный кожух,1.0,NaN,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,00774106200234070,NaN,NaN,NaN,Питательный провод 00774106200230050,Соединительный провод между \r\nдвигателем и м...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
737,00774006200234090,NaN,NaN,NaN,Питательный провод 00774106200230050,Соединительный провод между реле \r\nи подогре...,/,NaN,NaN,NaN,NaN,NaN,NaN,NaN
738,1020005456,NaN,NaN,NaN,Питательный провод 00774106200230050,Контактор постоянного тока,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
739,00774006200234060,NaN,NaN,NaN,Питательный провод 00774106200230050,Пусковой мотор соединяется с \r\nгенератором,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
740,00774106200234010,NaN,NaN,NaN,Питательный провод 00774106200230050,Соединительный провод между \r\nаккумулятором ...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Код материалов,Наименование и спецификация,Кол-во,Примечание,Section,Количество,Кол-во Примечание,Unnamed: 4,Unnamed: 3,№\n\n п/п
0,1040200503,Гайка,2,JB/T889.1,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN
1,1040302480,Шайба 8-200HV,4,JB/T96.1,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN
2,00773400100261050,Подшипник,2,NaN,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN
3,00773400100261060,Болт φ22,2,NaN,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN
4,00773400100260020,Защитный кожух,1,NaN,Рабочая платформа 00774000100000000,NaN,NaN,NaN,NaN,NaN

100%|██████████| 1/1 [00:01<00:00,  1.88s/it]

- Спросить у Миши про запчасти, в описании которых встречается ещё одна модель, помимо основной, в которой они встречаются
- Что делать с такими в описании (Cubota): ZT138J-ZT24JE-V Turntable Decal Assembly - что значит тире?

In [38]:
df_all = pd.read_excel('dfs_2.xlsx')
display(df_all.info())
for old_col in ['во', 'Кол-\nво', 'Кол-\r\nво', 'Кол-в\nо \nштук', 'Кол-\nво \nшту\nк', 'Кол-во \nштук', 'Cantidad', 'Кол-во\n\nштук', 'Кол-во\r\nштук', 'Кол-\n\nво \n\nшту\n\nк', 'Кол-во \r\nштук', 'Кол-в\r\nо \r\nштук', 'Кол-\r\nво \r\nшту\r\nк', 'Кол-во штук', 'Кол-в', 'Колич\r\nество', 'Кол-в\r\nо\r\nштук', 'Колич ество', 'Кол-во Примечание', 'Number  of  pieces']:
    if old_col in df_all.columns.tolist():
        if 'Кол-во' in df_all.columns.tolist():
            df_all['Кол-во'] = df_all.loc[:, old_col].combine_first(df_all['Кол-во'])
        else:
            df_all['Кол-во'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Кол-во' in df_all.columns:
    col = df_all.pop("Кол-во")  
    df_all.insert(2, "Кол-во", col) 

for old_col in ['Наименование и \nспецификация', 'Наименование и \r\nспецификация', 'Наименование и\n\nспецификация', 'Nombre y especificación', 'Наименование и \r\nспецификация', 'Наименование и\r\nспецификация', 'Наименование и', 'Наименование\r\nи', 'Наименование']:
    if old_col in df_all.columns.tolist():
        if 'Наименование и спецификация' in df_all.columns:
            df_all['Наименование и спецификация'] = df_all.loc[:, old_col].combine_first(df_all['Наименование и спецификация'])
        else:
            df_all['Наименование и спецификация'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Наименование и спецификация' in df_all.columns:
    col = df_all.pop("Наименование и спецификация")  
    df_all.insert(1, "Наименование и спецификация", col) 

for old_col in ['Name and Spec.', 'Spec and Item', 'Name  and  specifications']:
    if old_col in df_all.columns:
        if 'Item and Spec' in df_all.columns:
            df_all['Item and Spec'] = df_all.loc[:, old_col].combine_first(df_all['Item and Spec'])
        else:
            df_all['Item and Spec'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Item and Spec' in df_all.columns:
    col = df_all.pop('Item and Spec')  
    df_all.insert(1, 'Item and Spec', col) 

for old_col in ['Примечани\nе', 'Observaciones', 'Примечани\n\nе', 'Примечани\r\nе', '№ позиции', 'Примеч\r\nание']:
    if old_col in df_all.columns:
        if 'Примечание' in df_all.columns:
            df_all['Примечание'] = df_all.loc[:, old_col].combine_first(df_all['Примечание'])
        else:
            df_all['Примечание'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Примечание' in df_all.columns:
    col = df_all.pop('Примечание')  
    df_all.insert(3, 'Примечание', col) 

for old_col in ['Qty.', 'Unit', 'Qt\r\ny']:
    if old_col in df_all.columns:
        if 'Qty' in df_all.columns:
            df_all['Qty'] = df_all.loc[:, old_col].combine_first(df_all['Qty'])
        else:
            df_all['Qty'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Qty' in df_all.columns:
    col = df_all.pop('Qty')  
    df_all.insert(2, 'Qty', col) 
    
for old_col in ['Código de material', 'Код мат-ла', 'п/п  Код материалов', 'Код']:
    if old_col in df_all.columns:
        if 'Код материалов' in df_all.columns:
            df_all['Код материалов'] = df_all.loc[:, old_col].combine_first(df_all['Код материалов'])
        else:
            df_all['Код материалов'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Код материалов' in df_all.columns:
    col = df_all.pop('Код материалов')  
    df_all.insert(0, 'Код материалов', col) 

for old_col in ['"Версия"', 'Версия  Кол-']:
    if old_col in df_all.columns:
        if 'Версия' in df_all.columns:
            df_all['Версия'] = df_all.loc[:, old_col].combine_first(df_all['Версия'])
        else:
            df_all['Версия'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)

for old_col in ['Part No.', 'Material Code', 'Material  Code']:
    if old_col in df_all.columns:
        if 'Material No.' in df_all.columns:
            df_all['Material No.'] = df_all.loc[:, old_col].combine_first(df_all['Material No.'])
        else:
            df_all['Material No.'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Material No.' in df_all.columns:
    col = df_all.pop('Material No.')  
    df_all.insert(0, 'Material No.', col) 

for old_col in ['Note']:
    if old_col in df_all.columns:
        if 'Remark' in df_all.columns:
            df_all['Remark'] = df_all.loc[:, old_col].combine_first(df_all['Remark'])
        else:
            df_all['Remark'] = df_all[old_col]
        df_all = df_all.drop(columns=old_col)
if 'Remark' in df_all.columns:
    col = df_all.pop('Remark')  
    df_all.insert(3, 'Remark', col) 

for col in ['Кол-во', 'Qty', '件数']:
    if col in df_all.columns:
        df_all[col] = df_all[col].replace({'/': 0, '、': 0, 'A': 0, '-': 0})
        df_all[col] = df_all[col].fillna(0)
        df_all[col] = df_all[col].astype(str).str.replace(',', '.', regex=False)
        df_all[col] = pd.to_numeric(df_all[col], errors='coerce').fillna(0)
        df_all[col] = df_all[col].apply(lambda x: int(x) if x.is_integer() else x)

if 'Код материалов' in df_all.columns:
    df_all['Код материалов'] = df_all['Код материалов'].astype(str).str.replace('\xa0', ' ', regex=False).str.strip()
    extracted = df_all['Код материалов'].str.extract(r'^(\S+)\s+(.*)$')
    mask = extracted[0].notna()
    df_all.loc[mask, 'Наименование и спецификация'] = extracted.loc[mask, 1]
    df_all.loc[mask, 'Код материалов'] = extracted.loc[mask, 0]

df_all.to_excel('df_all.xlsx', index=False)
df_all = pd.read_excel('df_all.xlsx')
test_1 = pd.read_excel('dfs.xlsx')
assert test_1.shape[0] == df_all.shape[0]

for col in ['Material No.', 'Код материалов', '物料编码']:
    if col in df_all.columns:
        df_all = df_all[df_all[col] != '']
        df_all = df_all[~df_all[col].astype(str).str.startswith('/')]
        df_all = df_all[~df_all[col].isna()]

display(df_all.head())

if 'Material No.' in df_all.columns and df_all['Material No.'].astype(str).str.contains('NO-NUMBER').any():
    df_all['Material No.'] = df_all['Material No.'].str.split('\n').str[0]
    df_all = df_all[~df_all['Material No.'].astype(str).str.startswith('NO-NUMBER')]

if 'Код материалов' in df_all.columns and df_all['Код материалов'].astype(str).str.contains('NO-NUMBER').any():
    df_all = df_all[~df_all['Код материалов'].astype(str).str.startswith('NO-NUMBER')]

cols = df_all.select_dtypes(include='object').columns
df_all[cols] = (df_all[cols].replace(r'\s*\n\s*', ' ', regex=True))
df_all[cols] = df_all[cols].replace(replacements, regex=True)

if 'Item and Spec' in df_all.columns:
    df_all['Item and Spec'] = df_all['Item and Spec'].replace('/', np.nan)

if '物料编码' in df_all.columns:
    mask = df_all['物料编码'].str.contains(r'^\d+\s+\D', na=False)
    extracted = df_all.loc[mask, '物料编码'].str.extract(r'^(\d+)\s+(.*)$')
    df_all.loc[mask, '物料编码'] = extracted[0]
    df_all.loc[mask, '名称及规格'] = extracted[1]
    
df_merged = merge_parts(df_all) 

assert (df_all.shape[0] - df_all.iloc[:, 0].duplicated().sum() - df_merged.shape[0]) == 0

lst = ['ZS1623RT', 'ZA10RJE', 'ZA14J', 'ZA14JE-Li', 'ZA14NJE', 'ZA16J', 'ZA16JERT', 'ZA18J', 'ZA20J', 'ZA20JE', 'ZA20JERT', 'ZA22J-V' ,'ZA22J', 'ZA24J', 'ZA32J(H-образ.)', 'ZA32J(X-образ.)', 'ZT42J-V', 'ZA42J', '', '', '', '', '', '', '', '', '' ,'', '', 'ZT20J', 'ZT22J-V', 'ZT26J', 'ZT26JS-V', 'ZT30J', 'ZT32J-V', 'ZT32J', 'ZT34J', 'ZT38J', 'ZT42J', 'ZT51J', 'ZT58J', 'ZT72J-V', 'ZT82J', 'ZTH3507', 'ZTH3513', 'ZTH3513', 'ZX23AE']
df_merged['Models'] = lst[b]

df_merged.to_excel(f'{filename}.xlsx', index=False)

<class 'pandas.DataFrame'>
RangeIndex: 741 entries, 0 to 740
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Код материалов                 741 non-null    object
 1   Наименование и

спецификация  697 non-null    str
 2   Кол-

во                       736 non-null    object
 3   Примечание                     264 non-null    str
 4   Section                        741 non-null    str
 5   Наименование и спецификация    0 non-null      float64
 6   Кол-во                         0 non-null      float64
 7   Примечани

е                   0 non-null      float64
 8   Количество                     0 non-null      float64
 9   Кол-во  Примечание             0 non-null      float64
 10  Unnamed: 4                     0 non-null      float64
 11  Unnamed: 3                     0 non-null      float64
 12  Кол-во Примечание              0 non-null      float64
 13  №

 п/п                        34 non-null     float64
dtypes: float64(9), object(2), str(3)
memory usage: 81.2+ KB

None

TypeError: Invalid value '<StringArray>
[              'Прижимная планка трубопровода I',
                              'Трубный хомут II',
                               'Трубный хомут I',
                                  'Прокладка IV',
                                     'Подшипник',
                              'Монтажная планка',
                              'Распорная втулка',
                      'Стопорный штифт φ20×120*',
                                     'Штырь III',
                                        'Ползун',
                      'Регулирующая прокладка Ⅳ',
                      'Пылезащитная    щетка II',
                                     'Прокладка',
                      'Пылезащитная    щетка IV',
                        'Регулировочная шайба Ⅴ',
                                  'Узлы ползуна',
             'Длинная регулирующая прокладка II',
              'Длинная регулирующая прокладка I',
                                'Длинный сухарь',
 'Сварной элемент первой секции башенной стрелы',
         'Монтажная планка путевого выключателя',
                             'Замыкающий блокII',
              'Направляющая прямоугольная труба',
                                    'ПрокладкаV',
                              'Монтажная планка',
                           'Прямоугольная труба',
                                   'ПрокладкаIV',
                               'Трубный хомутII',
                                'Трубный хомутI',
                'Прижимная планка трубопроводаI',
                               'Нейлоновый блок',
                     'Механизм буксируемой цепи',
                          'Противоударный блокI',
                                'Упорный блокII',
                  'Изогнутая монтажная пластина',
                               'Трубный хомутIV',
              'Прижимная планка трубопроводаIII',
                                         'Штифт',
                                 'Штифт в сборе',
            'Штифт цилиндра рулевого управления']
Length: 40, dtype: str' for dtype 'float64'

In [ ]:
df.