In [ ]:
import os
import camelot
import pandas as pd
from tqdm import tqdm
from IPython.display import display
import warnings
import re
import numpy as np
import pdfplumber

warnings.filterwarnings("ignore")

folder = os.getcwd()
pdf_files = [os.path.join(folder, f) for f in os.listdir(folder) if f.lower().endswith(".pdf")]


def extract_numbers(name):

    nums = re.findall(r'\d+', name)
    return tuple(map(int, nums))

replacements = {
    'Ⅰ': 'I',
    'Ⅱ': 'II',
    'Ⅲ': 'III',
    'Ⅳ': 'IV',
    'Ⅴ': 'V',
    'Ⅵ': 'VI',
    'Ⅶ': 'VII',
    'Ⅷ': 'VIII',
    'Ⅸ': 'IX',
    'Ⅹ': 'X'
}

def extract_tables_camelot(pdf_path: str, out_dir="tables", pages="all", title_height=120):

    os.makedirs(out_dir, exist_ok=True)

    tables_lattice = camelot.read_pdf(
        pdf_path,
        pages=pages,
        flavor="lattice",
        line_scale=80
    )

    lattice_pages = set()
    text_pages = set()

    with pdfplumber.open(pdf_path) as pdf:

        for i, t in enumerate(tables_lattice):

            page_num = int(t.page)          
            page_idx = page_num - 1        
            lattice_pages.add(page_num)

            t.to_csv(
                os.path.join(out_dir, f"lattice_p{page_num}_{i}.csv"),
                index=False
            )

            page = pdf.pages[page_idx]

            x1, y1, x2, y2 = t._bbox
            page_w = page.width
            page_h = page.height

            table_top = page_h - y2

            left   = max(0, min(x1, page_w))
            right  = max(0, min(x2, page_w))
            top    = max(0, min(table_top - title_height, page_h))
            bottom = max(0, min(table_top, page_h))

            if right > left and bottom > top:
                title_box = (left, top, right, bottom)
                title_text = page.crop(title_box, strict=False).extract_text(
                    x_tolerance=2,
                    y_tolerance=2
                ) or ""

                if title_text.strip():
                    text_pages.add(page_num)
            else:
                title_text = ""

            with open(
                os.path.join(out_dir, f"text_p{page_num}_{i}.txt"),
                "w",
                encoding="utf-8"
            ) as f:
                f.write(title_text.strip())

    return None       


def join_ordered(series):
    vals = series.dropna().astype(str).str.strip()
    vals = [v for v in vals if v]
    seen = set()
    result = []
    for v in vals:
        if v not in seen:
            seen.add(v)
            result.append(v)
    return "; ".join(result) if result else None

DEFAULT_MODELS_1_2_4_5 = ['ZS1414', 'ZS1212', 'ZS1012', 'ZS0812', 'ZS0808', 'ZS0608', 'ZS0607', 'ZS0407'] #для 4 и 5 нужно менять df_all
DEFAULT_MODELS3_8 = ['ZS1414', 'ZS1212', 'ZS1012', 'ZS0808', 'ZS0608', 'ZS0607', 'ZS0407']
DEFAULT_MODELS6_7 = ['ZS0508', 'ZS0610', 'ZS1216']
DEFAULT_MODELS9_10 = ['ZS1023', 'ZS1323', 'ZS1623']
DEFAULT_MODELS11 = ['ZS1623']

def extract_zs_models_checked(row):
    def extract_from_text(text):
        if pd.isna(text):
            return []
        parts = re.split(r'[;/]', str(text).upper())
        result = []
        last_zs_number = None
        
        for part in parts:
            part = part.strip()
            
            match_zs = re.search(r'ZS(\d{4})', part)

            match_digits = re.search(r'(\d{4})', part)
            
            candidate = None
            if match_zs:
                candidate = match_zs.group(0)
            elif match_digits:
                candidate = "ZS" + match_digits.group(1)
            
            if candidate and candidate in DEFAULT_MODELS11:
                result.append(candidate)
        
        return result

    models = extract_from_text(row.get("Item and Spec"))
    
    if not models:
        models = extract_from_text(row.get("Section"))

    if not models:
        return None
    
    return "; ".join(dict.fromkeys(models))

def merge_models_strict(series: pd.Series) -> str:
    if series.isna().any():
        return "; ".join(DEFAULT_MODELS11)

    uniq = []
    seen = set()
    for val in series:
        if val:
            for m in str(val).split(";"):
                m = m.strip()
                if m and m not in seen:
                    seen.add(m)
                    uniq.append(m)

    return "; ".join(uniq) if uniq else None


def merge_parts(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    
    df["Models"] = df.apply(extract_zs_models_checked, axis=1)

    group_col = None
    for col in ['Material No.', 'Код материалов', '物料编码']:
        if col in df.columns:
            group_col = col
            break
    
    if not group_col:
        return df 

    agg_map = {}
    qty_cols = ['Qty', 'Кол-во', '件数', 'Units']
    for col in qty_cols:
        if col in df.columns:
            agg_map[col] = "sum"

    text_cols = ["Item and Spec", "Remark", 'Наименование и спецификация', 
                 'Примечание', 'Версия', 'Rev.', "名称及规格", "备注", "Section"]
    for col in text_cols:
        if col in df.columns:
            agg_map[col] = join_ordered

    df_agg = df.groupby(group_col, as_index=False).agg(agg_map)
    
    models_series = df.groupby(group_col)["Models"].apply(merge_models_strict).reset_index()
    
    df_agg = df_agg.merge(models_series, on=group_col, how='left')

    return df_agg

In [ ]:
# TODO подправить Section в ZA22J-V, посчитать количества таблиц, объеденить все таблицы
pdf_files[11]

'c:\\Users\\Normc\\OneDrive\\Рабочий стол\\Python\\Работа\\Zoomlion\\ZA22J-V.pdf'

In [147]:
b = 11
e = b+1

for i, pth in enumerate(tqdm(pdf_files[b:e])):
    
    filename = os.path.basename(pth)          
    filename = os.path.splitext(filename)[0]
    print(f'Обработка файла: {filename}')

    # extract_tables_camelot(pth, filename, pages="all", title_height=800)

    dfs = []

    for file in sorted(os.listdir(filename), key=extract_numbers):

        if not file.startswith("lattice_") or not file.lower().endswith(".csv"):
            continue

        path = os.path.join(filename, file)

        if os.path.getsize(path) == 0:  
            continue
        df_i = pd.read_csv(path, converters={1: str})

        if (
            df_i.empty
            or df_i.shape[1] < 4
            or not any(col in df_i.columns for col in ['NO.', 'Код материалов', 'No.', 'Код мат-ла', 'Serial No.', 'Part No.', '物料编码', 'п/п  Код материалов', 'Код', 'Material No.', 'Material  Code', '№  материала'])
            ):
            continue

        # если китаец насрал пробел в начале таблицы
        if 'NO.' in df_i.iloc[0].values or 'Material No.' in df_i.iloc[0].values:
            df_i.columns = df_i.iloc[0]  
            df_i = df_i[1:].reset_index(drop=True) 

        for col in ['NO.', 'No.', '№ п/п', '№ \nп/п', 'Serial No.', '序号', '№ \n\nп/п', '№ \r\nп/п', '№', 'N\r\no.', 'No\r\n.', 'Serial  number', 'НЕТ.']:
            if col in df_i.columns:
                df_i = df_i.drop(col, axis=1)

        idx = file.replace("lattice_", "").rsplit(".", 1)[0]
        section_val = os.path.join(filename, f"text_{idx}.txt")
        
        with open(section_val, "r", encoding="utf-8") as f:
            lines = f.read().splitlines()

        skip_titles = [
            'Руководство по деталъная структура',
            'Альбом чертежей деталей и узлов коленчатого подъемника для высотных работ',
            'Альбом чертежей деталей и компонентов',
            'Parts Manual',
            '零部件图册',
            'Translated by Google',
            'anslated by Google'
        ]

        if lines and lines[0] in skip_titles:
            lines = lines[1:]
                
        if lines and lines[0] in ['Альбом чертежей деталей и узлов коленчатого', 'Альбом чертежей деталей и узлов коленчатого подъемника для', 'slated by Google']:
            lines = lines[2:]

        lines_joined = " ".join(lines)
            
        df_i["Section"] = lines_joined
        
        df_i = df_i[df_i.iloc[:, 0].replace('', pd.NA).notna()]
        display(df_i)
        df_i = df_i[df_i.iloc[:, 0] != '/']
        dfs.append(df_i)

    df_all = pd.concat(dfs, ignore_index=True)
    display(df_all)
    df_all.to_excel('dfs.xlsx', index=False)

    for old_col in ['во', 'Кол-\nво', 'Кол-\r\nво', 'Кол-в\nо \nштук', 'Кол-\nво \nшту\nк', 'Кол-во \nштук', 'Cantidad', 'Кол-во\n\nштук', 'Кол-во\r\nштук', 'Кол-\n\nво \n\nшту\n\nк', 'Кол-во \r\nштук', 'Кол-в\r\nо \r\nштук', 'Кол-\r\nво \r\nшту\r\nк', 'Кол-во штук', 'Кол-в', 'Колич\r\nество', 'Кол-в\r\nо\r\nштук', 'Колич ество', 'Кол-во Примечание', 'Number  of  pieces', 'Единицы', 'Единицы ']:
        if old_col in df_all.columns.tolist():
            if 'Кол-во' in df_all.columns.tolist():
                df_all['Кол-во'] = df_all.loc[:, old_col].combine_first(df_all['Кол-во'])
            else:
                df_all['Кол-во'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Кол-во' in df_all.columns:
        col = df_all.pop("Кол-во")  
        df_all.insert(2, "Кол-во", col) 

    for old_col in ['Наименование и \nспецификация', 'Наименование и \r\nспецификация', 'Наименование и\n\nспецификация', 'Nombre y especificación', 'Наименование и \r\nспецификация', 'Наименование и\r\nспецификация', 'Наименование и', 'Наименование\r\nи', 'Наименование', 'Товар и спецификация ', 'Товар  и спецификация', 'Товар  и  спецификация', 'Товар и  спецификация']:
        if old_col in df_all.columns.tolist():
            if 'Наименование и спецификация' in df_all.columns:
                df_all['Наименование и спецификация'] = df_all.loc[:, old_col].combine_first(df_all['Наименование и спецификация'])
            else:
                df_all['Наименование и спецификация'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Наименование и спецификация' in df_all.columns:
        col = df_all.pop("Наименование и спецификация")  
        df_all.insert(1, "Наименование и спецификация", col) 

    for old_col in ['Name and Spec.', 'Spec and Item', 'Name  and  specifications', 'Item  and  Spec', 'Name  and  specifications', 'Name and specifications']:
        if old_col in df_all.columns:
            if 'Item and Spec' in df_all.columns:
                df_all['Item and Spec'] = df_all.loc[:, old_col].combine_first(df_all['Item and Spec'])
            else:
                df_all['Item and Spec'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Item and Spec' in df_all.columns:
        col = df_all.pop('Item and Spec')  
        df_all.insert(1, 'Item and Spec', col) 

    for old_col in ['Примечани\nе', 'Observaciones', 'Примечани\n\nе', 'Примечани\r\nе', '№ позиции', 'Примеч\r\nание']:
        if old_col in df_all.columns:
            if 'Примечание' in df_all.columns:
                df_all['Примечание'] = df_all.loc[:, old_col].combine_first(df_all['Примечание'])
            else:
                df_all['Примечание'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Примечание' in df_all.columns:
        col = df_all.pop('Примечание')  
        df_all.insert(3, 'Примечание', col) 

    for old_col in ['Qty.', 'Unit', 'Qt\r\ny', 'Units', 'Number  of  pieces']:
        if old_col in df_all.columns:
            if 'Qty' in df_all.columns:
                df_all['Qty'] = df_all.loc[:, old_col].combine_first(df_all['Qty'])
            else:
                df_all['Qty'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Qty' in df_all.columns:
        col = df_all.pop('Qty')  
        df_all.insert(2, 'Qty', col) 
        
    for old_col in ['Código de material', 'Код мат-ла', 'п/п  Код материалов', 'Код', '№ материала	', '№ материала', '№  материала']:
        if old_col in df_all.columns:
            if 'Код материалов' in df_all.columns:
                df_all['Код материалов'] = df_all.loc[:, old_col].combine_first(df_all['Код материалов'])
            else:
                df_all['Код материалов'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Код материалов' in df_all.columns:
        col = df_all.pop('Код материалов')  
        df_all.insert(0, 'Код материалов', col) 

    for old_col in ['"Версия"', 'Версия  Кол-']:
        if old_col in df_all.columns:
            if 'Версия' in df_all.columns:
                df_all['Версия'] = df_all.loc[:, old_col].combine_first(df_all['Версия'])
            else:
                df_all['Версия'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)

    for old_col in ['Part No.', 'Material Code', 'Material  Code', 'Material  No.', 'Material  Code']:
        if old_col in df_all.columns:
            if 'Material No.' in df_all.columns:
                df_all['Material No.'] = df_all.loc[:, old_col].combine_first(df_all['Material No.'])
            else:
                df_all['Material No.'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Material No.' in df_all.columns:
        col = df_all.pop('Material No.')  
        df_all.insert(0, 'Material No.', col) 

    for old_col in ['Note']:
        if old_col in df_all.columns:
            if 'Remark' in df_all.columns:
                df_all['Remark'] = df_all.loc[:, old_col].combine_first(df_all['Remark'])
            else:
                df_all['Remark'] = df_all[old_col]
            df_all = df_all.drop(columns=old_col)
    if 'Remark' in df_all.columns:
        col = df_all.pop('Remark')  
        df_all.insert(3, 'Remark', col) 

    for col in ['Кол-во', 'Qty', '件数']:
        if col in df_all.columns:
            df_all[col] = df_all[col].replace({'/': 0, '、': 0, 'A': 0, '-': 0})
            df_all[col] = df_all[col].fillna(0)
            df_all[col] = df_all[col].astype(str).str.replace(',', '.', regex=False)
            df_all[col] = pd.to_numeric(df_all[col], errors='coerce').fillna(0)
            df_all[col] = df_all[col].astype(float).apply(lambda x: int(x) if x.is_integer() else x)
    
    if 'Код материалов' in df_all.columns:
        df_all['Код материалов'] = df_all['Код материалов'].astype(str).str.replace('\xa0', ' ', regex=False).str.strip()
        extracted = df_all['Код материалов'].str.extract(r'^(\S+)\s+(.*)$')
        mask = extracted[0].notna()
        df_all.loc[mask, 'Наименование и спецификация'] = extracted.loc[mask, 1]
        df_all.loc[mask, 'Код материалов'] = extracted.loc[mask, 0]

    if 'Material No.' in df_all.columns:
        df_all['Material No.'] = df_all['Material No.'].astype(str).str.replace('\xa0', ' ', regex=False).str.strip()
        extracted = df_all['Material No.'].str.extract(r'^(\S+)\s+(.*)$')
        mask = extracted[0].notna()
        df_all.loc[mask, 'Item and Spec'] = extracted.loc[mask, 1]
        df_all.loc[mask, 'Material No.'] = extracted.loc[mask, 0]

    df_all.to_excel('df_all.xlsx', index=False)
    df_all = pd.read_excel('df_all.xlsx')
    test_1 = pd.read_excel('dfs.xlsx')
    assert test_1.shape[0] == df_all.shape[0]

    for col in ['Material No.', 'Код материалов', '物料编码']:
        if col in df_all.columns:
            df_all = df_all[df_all[col] != '']
            df_all = df_all[~df_all[col].astype(str).str.startswith('/')]
            df_all = df_all[~df_all[col].isna()]

    display(df_all.head())

    if 'Material No.' in df_all.columns and df_all['Material No.'].astype(str).str.contains('NO-NUMBER').any():
        df_all['Material No.'] = df_all['Material No.'].str.split('\n').str[0]
        df_all = df_all[~df_all['Material No.'].astype(str).str.startswith('NO-NUMBER')]

    if 'Код материалов' in df_all.columns and df_all['Код материалов'].astype(str).str.contains('NO-NUMBER').any():
        df_all = df_all[~df_all['Код материалов'].astype(str).str.startswith('NO-NUMBER')]

    cols = df_all.select_dtypes(include='object').columns
    df_all[cols] = (df_all[cols].replace(r'\s*\n\s*', ' ', regex=True))
    df_all[cols] = df_all[cols].replace(replacements, regex=True)

    if 'Item and Spec' in df_all.columns:
        df_all['Item and Spec'] = df_all['Item and Spec'].replace('/', np.nan)
    
    if '物料编码' in df_all.columns:
        mask = df_all['物料编码'].str.contains(r'^\d+\s+\D', na=False)
        extracted = df_all.loc[mask, '物料编码'].str.extract(r'^(\d+)\s+(.*)$')
        df_all.loc[mask, '物料编码'] = extracted[0]
        df_all.loc[mask, '名称及规格'] = extracted[1]
        
    df_merged = merge_parts(df_all) 
   
    assert (df_all.shape[0] - df_all.iloc[:, 0].duplicated().sum() - df_merged.shape[0]) == 0

    lst = ['ZS1623RT', 'ZA10RJE', 'ZA14J', 'ZA14JE-Li', 'ZA14NJE', 'ZA16J', 'ZA16JERT', 'ZA18J', 'ZA20J', 'ZA20JE', 'ZA20JERT', 'ZA22J-V' ,'ZA22J', 'ZA24J', 'ZA32J(H-образ.)', 'ZA32J(X-образ.)', 'ZT42J-V', 'ZA42J', '', '', '', '', '', '', '', '', '' ,'', '', 'ZT20J', 'ZT22J-V', 'ZT26J', 'ZT26JS-V', 'ZT30J', 'ZT32J-V', 'ZT32J', 'ZT34J', 'ZT38J', 'ZT42J', 'ZT51J', 'ZT58J', 'ZT72J-V', 'ZT82J', 'ZTH3507', 'ZTH3513', 'ZTH3513', 'ZX23AE']
    df_merged['Models'] = lst[b]
    df_merged

    df_merged.to_excel(f'{filename}.xlsx', index=False)

  0%|          | 0/1 [00:00<?, ?it/s]

Обработка файла: ZA22J-V

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773400100261030,Plate II,1,NaN,Work platform 00773600130000000
1,1040005844,bolt,4,NaN,Work platform 00773600130000000
2,1040300771,Washer 6-200HV,32,GB/T5783-2000,Work platform 00773600130000000
3,00773400100260020,Protective cover,1,GB/T97.1-2002,Work platform 00773600130000000
4,00773400100261060,bolt,2,NaN,Work platform 00773600130000000
5,00773400100261050,Bearing,2,NaN,Work platform 00773600130000000
6,1040302480,Washer 8-200HV,4,NaN,Work platform 00773600130000000
7,1040200503,Nut M8-8,6,GB/T96.1-2002,Work platform 00773600130000000
8,1040200504,Nut M10-8,4,GB/T889.1-2000,Work platform 00773600130000000
9,1040302512,Washer 10-200HV,8,GB/T889.1-2000,Work platform 00773600130000000
10,1040004508,Bolt M10×45-8.8,4,GB/T96.1-2002,Work platform 00773600130000000
11,00773406300201030,Rubber pad,2,GB/T5783-2000,Work platform 00773600130000000
12,00773400130810003,Platform weldment weldment,1,NaN,Work platform 00773600130000000
13,00773400130600000,Hydraulic valve frame weldment,1,NaN,Work platform 00773600130000000
14,1040005852,Bolt M12×20-8.8,2,NaN,Work platform 00773600130000000
15,00773400130401040,Pad I,8,GB/T5787-2000,Work platform 00773600130000000
16,1054600077,Needle Roller Bearings,8,NaN,Work platform 00773600130000000
17,02564400100420000,Bracket weldment,1,NaN,Work platform 00773600130000000
18,1040200507,Nut M12-8,4,NaN,Work platform 00773600130000000
19,1040302821,Washer 12-200HV,6,GB/T889.1-2000,Work platform 00773600130000000
20,1040004556,Bolt M12×35-8.8,4,GB/T96.1-2002,Work platform 00773600130000000
21,00773400100401040,Block,1,GB/T16674.1-2016,Work platform 00773600130000000
22,1040301515,Washer 8-200HV,7,NaN,Work platform 00773600130000000
23,1040103112,Screw M8×25-8.8,7,GB/T97.1-2002,Work platform 00773600130000000
24,00773400130401060,Block III,2,GB/T70.1-2000,Work platform 00773600130000000
25,1040001703,Bolt M12×65-10.9,2,NaN,Work platform 00773600130000000
26,1040201163,Nut M12-10,2,GB/T5782-2000,Work platform 00773600130000000
27,1040302490,Washer 12-200HV,4,GB/T889.1-2000,Work platform 00773600130000000
28,02564400100401020,axis,4,GB/T97.1-2002,Work platform 00773600130000000
29,1080000005,Oil cup M6×1,8,NaN,Work platform 00773600130000000
30,02564400100401030,Axis plate,4,JB_T7940.1_1995,Work platform 00773600130000000
31,1040004646,Bolt M10×15-8.8,4,NaN,Work platform 00773600130000000
32,00773400130410000,Transition seat,1,GB/T5783-2000,Work platform 00773600130000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040201111,Nut M24-10,1.0,NaN,Work platform 00773600130000000
1,1040301511,Washer 24-200HV,1.0,GB/T889-1986,Work platform 00773600130000000
2,00773400100401030,Adjustment pad,2.0,GB/T97.1-2002,Work platform 00773600130000000
3,1040006524,Bolt M10×25-10.9,8.0,NaN,Work platform 00773600130000000
4,1040004505,Bolt M24×280-10.9,1.0,NaN,Work platform 00773600130000000
5,02564400100401010,Connecting rod,2.0,GB/T5782-2000,Work platform 00773600130000000
6,1040201381,Nut M12-8,1.0,NaN,Work platform 00773600130000000
7,1040006458,Strengthened semicircular head square bolt...,1.0,GB/T6170-2000,Work platform 00773600130000000
8,1040102372,Hexagon socket head screws\r\nM6×20-A2-70,6.0,NaN,Work platform 00773600130000000
9,1999904986,Document Box,1.0,GB/T70.1-2000,Work platform 00773600130000000
10,00771600100201021,Baffle I,1.0,NaN,Work platform 00773600130000000
11,1040102017,Screw M6×45-A2-70,6.0,NaN,Work platform 00773600130000000
12,1040201896,Nut M6-8,16.0,NaN,Work platform 00773600130000000
13,1040006017,Screw M6×25-A2-70,4.0,GB/T889.1-2015,Work platform 00773600130000000
14,00773400100261110,Stopper,2.0,NaN,Work platform 00773600130000000
15,00773400100261080,Baffle,2.0,NaN,Work platform 00773600130000000
16,1022397103,Open bellows,NaN,NaN,Work platform 00773600130000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773400100260020 Protective cover,NaN,1,NaN,Work p latform 00773600100000000
1,00773400100261030 Plate ÿ,NaN,1,NaN,Work p latform 00773600100000000
2,1040005844,bolt,4,GB/T5783-2000,Work p latform 00773600100000000
3,1040300771,Washer 6-200HV,36,GB/T97.1-2002,Work p latform 00773600100000000
4,00773400100261060 Bolt,NaN,2,NaN,Work p latform 00773600100000000
5,00773400100261050 Bearing,NaN,2,NaN,Work p latform 00773600100000000
6,1040302480,Washer 8-200HV,4,GB/T96.1-2002,Work p latform 00773600100000000
7,1040200503,Nut M8-8,7,GB/T889.1-2000,Work p latform 00773600100000000
8,1040200504,Nut M10-8,4,GB/T889.1-2000,Work p latform 00773600100000000
9,1040302512,Washer 10-200HV,8,GB/T96.1-2002,Work p latform 00773600100000000
10,1040004508,Bolt M10×45-8.8,4,GB/T5783-2000,Work p latform 00773600100000000
11,00773406300201030,Rubber pad,2,NaN,Work p latform 00773600100000000
12,00773600130210000 Platform weldment,NaN,1,NaN,Work p latform 00773600100000000
13,1040201896,Nut M6-8,18,GB/T889.1-2015,Work p latform 00773600100000000
14,1040006017,Screw M6×25-A2-70,4,NaN,Work p latform 00773600100000000
15,00773400100261110 Block,NaN,2,NaN,Work p latform 00773600100000000
16,1040102372,Hexagon socket head screws\r\nM6×20-A2-70,6,GB/T70.1-2000,Work p latform 00773600100000000
17,1999904986,Document Box,1,NaN,Work p latform 00773600100000000
18,00773600130201010 Anti-collision block,NaN,1,NaN,Work p latform 00773600100000000
19,1040103173,Screw M6×50-8.8,2,NaN,Work p latform 00773600100000000
20,1040300514,Washer 5-200HV,12,GB/T97.1-2002,Work p latform 00773600100000000
21,00773400100230000 Revolving door,NaN,1,NaN,Work p latform 00773600100000000
22,1029904911,Spring pad,12,GB93-304,Work p latform 00773600100000000
23,1101000163,Spring hinge,2,NaN,Work p latform 00773600100000000
24,1040004672,Bolt M5×10-8.8,12,GB/T5783-2000,Work p latform 00773600100000000
25,1080000005,Oil cup M6×1,8,JB_T7940.1_1995,Work p latform 00773600100000000
26,1040004646,Bolt M10×15-8.8,4,GB/T5783-2000,Work p latform 00773600100000000
27,00773400130401090 Axis plate,NaN,4,NaN,Work p latform 00773600100000000
28,02564400100401020 Axis,NaN,4,NaN,Work p latform 00773600100000000
29,1054600077,Needle Roller Bearings,8,NaN,Work p latform 00773600100000000
30,02564400100401010 Connecting rod,NaN,1,NaN,Work p latform 00773600100000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773400130401040 Pad I,NaN,8,NaN,Work p latform 00773600100000000
1,1040006458,Strengthened semicircular head square bolt...,1,NaN,Work p latform 00773600100000000
2,1040201381,Nut M12-8,1,GB/T6170-2000,Work p latform 00773600100000000
3,1040001703,Bolt M12×65-10.9,2,GB/T5782-2000,Work p latform 00773600100000000
4,1040302490,Washer 12-200HV,4,GB/T97.1-2002,Work p latform 00773600100000000
5,1040201163,Nut M 12-10,2,GB/T889.1-2000,Work p latform 00773600100000000
6,00773400100401040 Block,NaN,1,NaN,Work p latform 00773600100000000
7,1040103112,Screw M8×25-8.8,7,GB/T70.1-2000,Work p latform 00773600100000000
8,00773400130401060 Block III,NaN,2,NaN,Work p latform 00773600100000000
9,1040004556,Bolt M12×35-8.8,8,GB/T16674.1-2016,Work p latform 00773600100000000
10,1040005852,Bolt M12×20-8.8,2,GB/T5787-2000,Work p latform 00773600100000000
11,00773400130600000 Hydraulic valve frame we...,NaN,1,NaN,Work p latform 00773600100000000
12,00771400120420001,Bracket weldment,1,NaN,Work p latform 00773600100000000
13,02564400100401010 Connecting rod,NaN,1,NaN,Work p latform 00773600100000000
14,1040201111,Nut M24-10,1,GB/T889-1986,Work p latform 00773600100000000
15,1040301511,Washer 24-200HV,1,GB/T97.1-2002,Work p latform 00773600100000000
16,1040004505,Bolt M24×280-10.9,1,GB/T5782-2000,Work p latform 00773600100000000
17,00773400100401030 Adjustment pad Tp1,NaN,2,NaN,Work p latform 00773600100000000
18,00773400130410000 Transition seat,NaN,1,NaN,Work p latform 00773600100000000
19,1040006524,Bolt M10×25-10.9,8,NaN,Work p latform 00773600100000000
20,1040004522,Bolt M8×50-8.8,1,GB/T5783-2000,Work p latform 00773600100000000
21,1040301515,Washer 8-200HV,9,GB/T97.1-2002,Work p latform 00773600100000000
22,00775600101801020,spring,1,NaN,Work p latform 00773600100000000
23,00775600101801010 Lock cylinder,NaN,1,NaN,Work p latform 00773600100000000
24,00773400100261080 Baffle,NaN,2,NaN,Work p latform 00773600100000000
25,1040102017,Screw M6×45-A2-70,6,NaN,Work p latform 00773600100000000
26,00771400100201050 Baffle,NaN,1,NaN,Work p latform 00773600100000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773400200001020 Bearing,NaN,2,NaN,Flying a rm 0 0773700200000000
1,00773700200200000 Support,NaN,1,NaN,Flying a rm 0 0773700200000000
2,00773400200001010 Bearing,NaN,10,NaN,Flying a rm 0 0773700200000000
3,00773700200001060 Pin,NaN,2,NaN,Flying a rm 0 0773700200000000
4,1040002433,Bolt M10×20-8.8,6,GB/T5783,Flying a rm 0 0773700200000000
5,00773400300001200 Stop pin,NaN,6,NaN,Flying a rm 0 0773700200000000
6,1040004619,Bolt M8×35-8.8,4,GB/T5783,Flying a rm 0 0773700200000000
7,1040301515,Washer 8-200HV,4,GB/T97.1,Flying a rm 0 0773700200000000
8,00773700200001082 Pipeline guard plate,NaN,1,NaN,Flying a rm 0 0773700200000000
9,1040103133,Screw M6×30,8,GB/T70.3,Flying a rm 0 0773700200000000
10,00773700200001100 Pipeline pressure plate,NaN,2,NaN,Flying a rm 0 0773700200000000
11,00773700200001090 Pipeline slot,NaN,2,NaN,Flying a rm 0 0773700200000000
12,00773700200400001 Upper connecting rod,NaN,1,NaN,Flying a rm 0 0773700200000000
13,00773700200001050 Pin ÿ35,NaN,2,NaN,Flying a rm 0 0773700200000000
14,00773700200600000 Lower connecting rod,NaN,2,NaN,Flying a rm 0 0773700200000000
15,1010201471,Swing Cylinder,1,NaN,Flying a rm 0 0773700200000000
16,00773700200810000 Flying arm cylinder,NaN,1,NaN,Flying a rm 0 0773700200000000
17,00773700200001010 Bearing,NaN,2,NaN,Flying a rm 0 0773700200000000
18,00773700200001070 Pin,NaN,1,NaN,Flying a rm 0 0773700200000000
19,1040103076,Screw M8×16-8.8,4,GB/T70.3,Flying a rm 0 0773700200000000
20,00773700400001290 Card board,NaN,2,NaN,Flying a rm 0 0773700200000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773400312200000 Slider assembly,NaN,4,NaN,No.1 a rm a ssembly 00773700300000002
1,00773400300001101 Adjusting gasket,NaN,4,NaN,No.1 a rm a ssembly 00773700300000002
2,1040302410,Washer 4-200HV,4,GB/T97.1,No.1 a rm a ssembly 00773700300000002
3,1040004591,Bolt M4×8-8.8,4,GB/T5783,No.1 a rm a ssembly 00773700300000002
4,1040302489,Washer 10-200HV,36,GB/T97.1,No.1 a rm a ssembly 00773700300000002
5,00771400340001090 Sensor cover,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
6,00773700303000001 Slider assembly,NaN,12,GB/T96.1,No.1 a rm a ssembly 00773700300000002
7,00773400300001131 Adjusting gasket IV,NaN,20,NaN,No.1 a rm a ssembly 00773700300000002
8,1040004565,Bolt M10×30-8.8-DKL,14,GB/T5783,No.1 a rm a ssembly 00773700300000002
9,1040002433,Bolt M10×20-8.8,16,GB/T5783,No.1 a rm a ssembly 00773700300000002
10,00773700300001020 Pin II,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
11,00773400300001140 Adjusting gasket V,NaN,4,NaN,No.1 a rm a ssembly 00773700300000002
12,1010306060,Telescopic balancing valve,1,NaN,No.1 a rm a ssembly 00773700300000002
13,00773700300001051 Telescopic cylinder pin,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
14,1040002434,Bolt M10×25-8.8,2,GB/T5783,No.1 a rm a ssembly 00773700300000002
15,00773400300001200 Stop pin,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
16,1040004518,Bolt M8×20-8.8,4,GB/T5783,No.1 a rm a ssembly 00773700300000002
17,1040301515,Washer 8-200HV,6,GB/T97.1,No.1 a rm a ssembly 00773700300000002
18,00773700300001181 Cylinder adjustment gaske...,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
19,00773700300001171 Cylinder adjustment gaske...,NaN,8,NaN,No.1 a rm a ssembly 00773700300000002
20,00773700302000000 Right card board,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
21,00773700302200000 Left card,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
22,00773700300991040 Travel switch,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
23,00773700300001090 Long screw M12×260,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
24,1040302490,Washer 12-200HV,4,GB/T97.1,No.1 a rm a ssembly 00773700300000002
25,00773700300001080 Pipe stop,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
26,1040201381,Nut M12-8,2,GB/T6170,No.1 a rm a ssembly 00773700300000002
27,1040103076,Screw M8×16-8.8,4,GB/T70.3,No.1 a rm a ssembly 00773700300000002
28,00773700400001290 Card board,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
29,00773700300001040 Pin IV,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
30,00773400300001210 Bearing,NaN,8,NaN,No.1 a rm a ssembly 00773700300000002
31,00773700300400004 Telescopic arm,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
32,00773700301000000 Upper leveling cylinder,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
33,00773700301200000 Telescopic cylinder,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773700300001100 Telescopic cylinder suppo...,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
1,1040004520,Bolt M8×30-8.8,2,GB/T5783,No.1 a rm a ssembly 00773700300000002
2,00773700301400000 Upper dust brush,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
3,1040300771,Washer 6-200HV,39,GB/T97.1,No.1 a rm a ssembly 00773700300000002
4,1040001640,Bolt M6×25-A2-70,8,GB/T5783,No.1 a rm a ssembly 00773700300000002
5,00773700301800000 Side dust brush,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
6,00773700301600000 Lower dust brush,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
7,1040201896,Nut M6-8,8,GB/T889.1,No.1 a rm a ssembly 00773700300000002
8,00773700300200004 Basic arm,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
9,00773400300001070 Bearing,NaN,6,NaN,No.1 a rm a ssembly 00773700300000002
10,00773700300600000 No.1 boom luffing cylinder,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
11,1040002446,Bolt M16×40-8.8,1,GB/T5783,No.1 a rm a ssembly 00773700300000002
12,00773400400001250 Stop pin,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
13,00773700300001030 Pin III,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
14,1040004553,Bolt M6×35-8.8,4,GB/5783,No.1 a rm a ssembly 00773700300000002
15,1040300735,Washer 6-200HV,8,GB/T96.1,No.1 a rm a ssembly 00773700300000002
16,00773700300001190 Wire tube cover,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
17,1040103133,Screw M6×30-A2-70,8,GB/T70.3,No.1 a rm a ssembly 00773700300000002
18,00773700300001140 Pipeline pressure plate,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
19,00773700300001240 Hose holder,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
20,1040005844,Bolt M6×10-A2-70,20,GB/T5783,No.1 a rm a ssembly 00773700300000002
21,1040300771,Washer 6-200HV,39,GB/T97.1,No.1 a rm a ssembly 00773700300000002
22,00773700300001210 Main arm sealing plate,NaN,5,NaN,No.1 a rm a ssembly 00773700300000002
23,1040002738,Bolt M6×12-A2-70,4,GB/T5783,No.1 a rm a ssembly 00773700300000002
24,00773700302400001 Protective cover,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
25,1040102778,Screw M6×10-8.8,3,GB/T70.1,No.1 a rm a ssembly 00773700300000002
26,1040002437,Bolt M12×35-8.8,2,GB/T5783,No.1 a rm a ssembly 00773700300000002
27,00773400200001070 Stop pin,NaN,2,NaN,No.1 a rm a ssembly 00773700300000002
28,00773700300001010 Pin I,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002
29,00773700300800000 Lower leveling cylinder,NaN,1,NaN,No.1 a rm a ssembly 00773700300000002

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040201904,Nut M5-8,8,GB/T889.1,Drag c hain s ystem 0 0773700700000002
1,1040300514,Washer 5-200HV,8,GB/T97.1,Drag c hain s ystem 0 0773700700000002
2,00773700700001070 Transition plate,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
3,00773700700001012 Rectangular tube,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
4,00773700700001100 Pad,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
5,1040103076,Screw M8×16-8.8,4,GB/T70.3,Drag c hain s ystem 0 0773700700000002
6,00773700700000002 Drag chain mechanism,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
7,1109900986,Drag chain connector I E4.421.12.1.1,1,NaN,Drag c hain s ystem 0 0773700700000002
8,1109900987,Drag chain connector II E4.421.12.1.2,1,NaN,Drag c hain s ystem 0 0773700700000002
9,1109900988,Drag chain outer plate E4.42.01,35,NaN,Drag c hain s ystem 0 0773700700000002
10,1109900990,Drag chain inner plate E4.42.02.075.0,35,NaN,Drag c hain s ystem 0 0773700700000002
11,1109900991,Drag chain crossbar 385.12,70,NaN,Drag c hain s ystem 0 0773700700000002
12,1109900993,Drag chain separator 42.1,35,NaN,Drag c hain s ystem 0 0773700700000002
13,1040102751,Screw M5×25-8.8,4,GB/T70.1,Drag c hain s ystem 0 0773700700000002
14,1040004519,Bolt M8×25-8.8,4,GB/T5783,Drag c hain s ystem 0 0773700700000002
15,1040301515,Washer 8-200HV,10,GB/T97.1,Drag c hain s ystem 0 0773700700000002
16,1040302480,Washer 8-200HV,4,GB/T96.1,Drag c hain s ystem 0 0773700700000002
17,1040200503,Nut M8-8,11,GB/T889.1,Drag c hain s ystem 0 0773700700000002
18,00773700700400000 Bracket,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
19,00773400700001030 Nylon block,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
20,1040102737,Screw M8×30-8.8,3,GB/T70.1,Drag c hain s ystem 0 0773700700000002
21,00773400700001020 Hose holder,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
22,00773400700001050 Bend mounting plate,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
23,1040004557,Bolt M8×50-8.8,2,GB/T16674.1,Drag c hain s ystem 0 0773700700000002
24,1040005925,Bolt M5×80,4,GB/T5782,Drag c hain s ystem 0 0773700700000002
25,00773700700001060 Pipe jacking,NaN,4,NaN,Drag c hain s ystem 0 0773700700000002
26,00773700700001091 Drag chain rectangular p...,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
27,00773700700001021 Drag chain rectangular t...,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
28,00773700700001030 Bent plate,NaN,1,NaN,Drag c hain s ystem 0 0773700700000002
29,1040004603,Bolt M8×75-8.8,2,GB/T5782,Drag c hain s ystem 0 0773700700000002

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773700401600000 Upper column,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
1,00773700400001090 Pin IX,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
2,00773400400001250 Stop pin,NaN,7,NaN,No.2 arm a ssembly 00773700400000001
3,1040002446,Bolt,5,GB/T5783,No.2 arm a ssembly 00773700400000001
4,1040002437,Bolt M12×35-8.8,1,GB/T5783,No.2 arm a ssembly 00773700400000001
5,00773400200001070 Stop pin,NaN,5,NaN,No.2 arm a ssembly 00773700400000001
6,00773700400001100 Pin shaft X,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
7,00773700400800000 Upper pressure rod,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
8,1040004517,Bolt M8×16-8.8,8,GB/T5783,No.2 arm a ssembly 00773700400000001
9,1040301515,Washer,20,GB/T97.1,No.2 arm a ssembly 00773700400000001
10,1040004522,8-200HV Bolt M8×50-8.8,4,GB/T5783,No.2 arm a ssembly 00773700400000001
11,00773700400001400 Baffle II 13,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
12,00773700400001370 Pipe clamp III 14,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
13,00773700400600000 Upper tie rod 15,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
14,00773700400400000 Lower tie rod 16,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
15,00773700400001130 Bearing 17,NaN,4,NaN,No.2 arm a ssembly 00773700400000001
16,00773700400001520 Screw I M12×240 18,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
17,00773700400001380 Baffle washer,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
18,1040302490,12-200HV Nut,1,GB/T97.1,No.2 arm a ssembly 00773700400000001
19,1040200507,M12-8 21,1,GB/T889.1,No.2 arm a ssembly 00773700400000001
20,00773700400001050 Pin shaft V 22,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
21,00773700400001480 Cover plate 23,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
22,00773700400001150 Bearing 24,NaN,4,NaN,No.2 arm a ssembly 00773700400000001
23,00773700400001341 Pipeline Cover IV Screw,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
24,1040103140,M12×25-8.8 26,8,NaN,No.2 arm a ssembly 00773700400000001
25,00773700400001500 Guide Block II 27,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
26,00773700400001490 Guide Block I 28,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
27,00773700400001070 Pin VII 29,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
28,00773700400001140 Bearing 30,NaN,4,NaN,No.2 arm a ssembly 00773700400000001
29,00773700400001280 Protective Plate II 31,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
30,00773700400001471 Adjusting Washer II 32,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
31,00773700400001461 Adjusting Washer I 33,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
32,00773700400001451 Spacer 34,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
33,00773700400001361 Pipe clamp II,NaN,2,NaN,No.2 arm a ssembly 00773700400000001

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040302529,Washer,6,GB/T96.1,No.2 arm a ssembly 00773700400000001
1,1040004672,5-200HV Bolt,6,GB/T5783,No.2 arm a ssembly 00773700400000001
2,00773700400001550 Adjusting,NaN,2,M5×10-8.8,No.2 arm a ssembly 00773700400000001
3,00773700400001270 Protective,NaN,2,washer 38,No.2 arm a ssembly 00773700400000001
4,00773700401000001 Lower column,NaN,1,plate I,No.2 arm a ssembly 00773700400000001
5,1040004599,Bolt M8×60-8.8,8,GB/T5782,No.2 arm a ssembly 00773700400000001
6,00773700400001390 Baffle I 42,NaN,4,NaN,No.2 arm a ssembly 00773700400000001
7,00773700400001351 Pipe clamp I 43,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
8,00773700400200001 Lower pressure rod,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
9,00773400300001070 Bearing bolt,NaN,8,NaN,No.2 arm a ssembly 00773700400000001
10,1040002445,M16×35-8.8,2,GB/T5783,No.2 arm a ssembly 00773700400000001
11,00773700400001020 Pin II,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
12,1040101492,Screws,16,NaN,No.2 arm a ssembly 00773700400000001
13,00773700400001010 Pin I 49,NaN,4,NaN,No.2 arm a ssembly 00773700400000001
14,00773700401400000 No. 2 boom luffing cyli...,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
15,00773700400001541 Cover plate 51,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
16,00773700400001290 Clamp plate 52,NaN,6,NaN,No.2 arm a ssembly 00773700400000001
17,00773700400001080 Pin VIII Screw,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
18,1040103164,M10×30-8.8 54,6,GB/T70.3,No.2 arm a ssembly 00773700400000001
19,00773400400001020 Bearing 55,NaN,16,NaN,No.2 arm a ssembly 00773700400000001
20,00773700400001060 Pin VI 56,NaN,1,NaN,No.2 arm a ssembly 00773700400000001
21,00773700401200000 Synchronous pull rod,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
22,00773700400001180 Pin fixing plate 58,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
23,00773700400001030 Pin III,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
24,1040004499,Bolt M20×45-8.8,2,GB/T5783,No.2 arm a ssembly 00773700400000001
25,00773400400001170 Stop pin 61,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
26,00773700400001040 Pin IV 62,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
27,00771400600001070 Self-lubricating bearing,NaN,8,NaN,No.2 arm a ssembly 00773700400000001
28,00773700400001261 Spacer T,NaN,2,NaN,No.2 arm a ssembly 00773700400000001
29,1040002436,Bolt M12×25-8.8,4,NaN,No.2 arm a ssembly 00773700400000001

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773400800001200 Switch support,NaN,1,NaN,Turntable 00773600800000000
1,1040001631,Bolt M6×20-A2-70,2,GB/T5783-2000,Turntable 00773600800000000
2,00773400800001042 Battery tray,NaN,1,NaN,Turntable 00773600800000000
3,00773400800001171 Battery separator,NaN,1,NaN,Turntable 00773600800000000
4,1040201896,Nut M6-8,6,GB/T889.1-2015,Turntable 00773600800000000
5,1040300771,Washer 6-200HV,6,GB/T97.1-2002,Turntable 00773600800000000
6,00773400800001280 Battery pressure plate,NaN,2,NaN,Turntable 00773600800000000
7,00773400800001131 Battery pull rod,NaN,4,NaN,Turntable 00773600800000000
8,1040004517,Bolt M8×16-8.8 Bolt,14,GB/T5783-2000,Turntable 00773600800000000
9,1040002435,M10×35-8.8,1,GB/T5783-2000,Turntable 00773600800000000
10,1040004520,Bolt M8×30-8.8,2,GB/T5783-2000,Turntable 00773600800000000
11,1040200503,Nut M8-8,4,GB/T889.1-2000,Turntable 00773600800000000
12,1040302821,Washer 12-200HV,12,GB/T96.1-2002,Turntable 00773600800000000
13,1040002436,Bolt M12×25-8.8 15,12,GB/T5783-2000,Turntable 00773600800000000
14,00773600800600001 Hydraulic oil tank bracket,NaN,1,NaN,Turntable 00773600800000000
15,1040004590,Bolt M8×14-8.8,8,GB/T5783-2000,Turntable 00773600800000000
16,00773600801600000 Wire bracket 18,NaN,1,NaN,Turntable 00773600800000000
17,00773600800800000 Fuel tank bracket,NaN,1,NaN,Turntable 00773600800000000
18,00773600802201010 Electric control cabinet ...,NaN,1,NaN,Turntable 00773600800000000
19,00773600801200000 Door contact bracket I,NaN,1,NaN,Turntable 00773600800000000
20,1040002433,Bolt M10×20-8.8 Nut,12,GB/T5783-2000,Turntable 00773600800000000
21,1040201089,M8-8,4,GB/T6170-2000,Turntable 00773600800000000
22,00773700800001030 Pin ÿ,NaN,2,NaN,Turntable 00773600800000000
23,00773400400001250 Stop pin,NaN,4,NaN,Turntable 00773600800000000
24,1040004570,Bolt M16×30-8.8 26,4,GB/T5783-2000,Turntable 00773600800000000
25,00773600801800000 Limit support I 27,NaN,1,NaN,Turntable 00773600800000000
26,00773600800001040 Shaft II,NaN,2,NaN,Turntable 00773600800000000
27,00773700830001301 Main valve mounting plate,NaN,1,NaN,Turntable 00773600800000000
28,00773600800001050 Travel control valve mou...,NaN,1,NaN,Turntable 00773600800000000
29,1040004519,Bolt M8×25-8.8,10,GB/T5783-2000,Turntable 00773600800000000
30,00773600802000000 Limit support II,NaN,2,NaN,Turntable 00773600800000000
31,1040004678,Door stop,4,NaN,Turntable 00773600800000000
32,1040200113,bolt nut M10-8,9,GB/T6170-2000,Turntable 00773600800000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773600801400000 Door stop bracket II,NaN,1,NaN,Turntable 00773600800000000
1,00773400800001180 Rotation limit pin,NaN,1,NaN,Turntable 00773600800000000
2,00773700800001600 Pipeline bracket,NaN,1,NaN,Turntable 00773600800000000
3,1040302512,Washer 10-200HV,14,GB/T96.1-2002,Turntable 00773600800000000
4,00773600800001080 Rotating body mounting p...,NaN,1,NaN,Turntable 00773600800000000
5,1040100714,Screw M12×130-8.8,1,GB/T70.1-2000,Turntable 00773600800000000
6,1040302490,Washer 12-200HV,3,GB/T97.1-2002,Turntable 00773600800000000
7,00773600800001100 Connector mounting plate,NaN,1,NaN,Turntable 00773600800000000
8,1040004511,Bolt M12×30-8.8,3,GB/T5783-2000,Turntable 00773600800000000
9,1040002738,Bolt M6×12-A2-70,2,GB/T5783-2000,Turntable 00773600800000000
10,00773700830400000 Pipeline guard,NaN,1,NaN,Turntable 00773600800000000
11,00773700830001020 Rotary limit support,NaN,1,NaN,Turntable 00773600800000000
12,00773700800001021 Adjustment plate,NaN,6,NaN,Turntable 00773600800000000
13,00773700800001210 Buffer pad,NaN,2,NaN,Turntable 00773600800000000
14,1040302480,Washer 8-200HV,34,GB/T96.1-2002,Turntable 00773600800000000
15,1040302489,Washer 10-200HV,6,GB/T97.1-2002,Turntable 00773600800000000
16,1040102741,Screw M10×40-8.8,6,GB/T70.1-2000,Turntable 00773600800000000
17,1040301515,Washer 8-200HV,10,GB/T97.1-2002,Turntable 00773600800000000
18,00773700830001200 Pipeline bracket,NaN,1,NaN,Turntable 00773600800000000
19,00773700830200000 Turntable welding parts,NaN,1,NaN,Turntable 00773600800000000
20,00773400800001150 Friction plate,NaN,1,NaN,Turntable 00773600800000000
21,00773400800001010 Bearing,NaN,2,NaN,Turntable 00773600800000000
22,00773400801400000 Tray latch,NaN,1,NaN,Turntable 00773600800000000
23,00773600800001060 Limit plate,NaN,1,NaN,Turntable 00773600800000000
24,00773400830601020 Control box cover,NaN,1,NaN,Turntable 00773600800000000
25,1040002555,Bolt M6×16-A2-70,5,GB/T5783-2000,Turntable 00773600800000000
26,1040004619,Bolt M8×35-8.8,2,GB/T5783-2000,Turntable 00773600800000000
27,00773400830601010 Connecting plate,NaN,1,NaN,Turntable 00773600800000000
28,00773600800001090 Door stop mounting plate I,NaN,2,NaN,Turntable 00773600800000000
29,00773600800400000 Engine bracket,NaN,1,NaN,Turntable 00773600800000000
30,1040302410,Washer 4-200HV,7,GB/T97.1-2002,Turntable 00773600800000000
31,1040300735,Washer 6-200HV,5,GB/T96.1-2002,Turntable 00773600800000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773400300001200 Stop pin,NaN,1,NaN,Turntable 00773600800000000
1,1040004591,Bolt M4×8-8.8,7,GB/T5783-2000,Turntable 00773600800000000
2,00773400800001221 Adjustment pad,NaN,2,NaN,Turntable 00773600800000000
3,00773600800001010 Pallet spacer,NaN,1,NaN,Turntable 00773600800000000
4,1040101492,Screw M10×25-8.8,2,GB/T70.1-2000,Turntable 00773600800000000
5,1040002434,Bolt M10×25-8.8,1,GB/T5783-2000,Turntable 00773600800000000
6,00773600800001030 Pallet shaft,NaN,1,NaN,Turntable 00773600800000000
7,00773400830200000 Motor installation,NaN,1,NaN,Turntable 00773600800000000
8,1990300400,U-shaped rubber strip,1,NaN,Turntable 00773600800000000
9,00773400830201010 Cover,NaN,1,NaN,Turntable 00773600800000000
10,1040201743,Nut M6,2,QC/T608-2011,Turntable 00773600800000000
11,1040004549,Bolt M4×16-8.8,4,GB/T5783-2000,Turntable 00773600800000000
12,00773400830201020 Baffle,NaN,1,NaN,Turntable 00773600800000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040002458,Bolt M8×40-8.8,8,GB/T5783,Engine hood 00773601100000000
1,00773601100200000 Right hood welding,NaN,1,NaN,Engine hood 00773601100000000
2,00773601100001020 Adjustment pad,NaN,4,NaN,Engine hood 00773601100000000
3,1040201089,nut M8-8,24,GB/T6170,Engine hood 00773601100000000
4,00773401100700000 Hinge,NaN,4,NaN,Engine hood 00773601100000000
5,1040302480,Washer 8-200HV,52,GB/T96.1,Engine hood 00773601100000000
6,1040004520,Bolt M8×30-8.8,12,GB/T5783,Engine hood 00773601100000000
7,1040301515,Washer 8-200HV,8,GB/T97.1,Engine hood 00773601100000000
8,1040301510,Washer,28,GB/T93,Engine hood 00773601100000000
9,1040004519,8 Bolt M8×25-8.8 Nut,12,GB/T5783,Engine hood 00773601100000000
10,1040200503,Screw,12,GB/T889.1,Engine hood 00773601100000000
11,1040100105,M6×25-8.8 Washer,14,GB/T70.1,Engine hood 00773601100000000
12,1040300771,GB/T97.1-2002 Bolt,14,6-200HV,Engine hood 00773601100000000
13,1040004590,M8×14-8.8 15,4,GB/T5783,Engine hood 00773601100000000
14,00773601100800000 Right lock washer 10 Nut,NaN,1,NaN,Engine hood 00773601100000000
15,1040301502,M10-8,4,GB/T93,Engine hood 00773601100000000
16,1040200113,NaN,4,GB/T6170,Engine hood 00773601100000000
17,00773601100001030 right lock seat,NaN,1,NaN,Engine hood 00773601100000000
18,1040302512,Washer 10-200HV,4,GB/T96.1,Engine hood 00773601100000000
19,1040004565,Bolt M10×30-8.8-DKL Hydraulic,4,GB/T5783,Engine hood 00773601100000000
20,1109900765,door lock,1,50075-C37K,Engine hood 00773601100000000
21,1110100359,"gas spring extension length\r\n435mm,S=162m...",5,000816,Engine hood 00773601100000000
22,1100700163,Door,2,26983-09,Engine hood 00773601100000000
23,00773601100400000 Left hood welding,NaN,1,handle 24,Engine hood 00773601100000000
24,1109900766,Battery door,1,NaN,Engine hood 00773601100000000
25,00773601100600000 Left lock seat 27,NaN,1,lock 26,Engine hood 00773601100000000
26,00773601100001010 Left lock seat gas spring,NaN,1,NaN,Engine hood 00773601100000000
27,1020605390,NaN,1,NaN,Engine hood 00773601100000000

,No. 1,Material Code,Name and specifications,Number of pieces,Remark,Section
1,2.0,1109900921,rubber plug,2,NaN,Counterweight 0 0773701020000000
2,3.0,1040302483,M36 Washer,4,GB/T96.1,Counterweight 0 0773701020000000
3,54.0,1040004613,24-200HV Bolt M24×60-10.9,4,GB/T5782,Counterweight 0 0773701020000000
5,6.0,1040102757,M10×25-8.8,4,GB/T70.3,Counterweight 0 0773701020000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040004648,Bolt M16×90-10.9,20,GB/T1228,00773700900000000
1,1040300186,washer,40,GB/T1230,00773700900000000
2,1030202348,Rotary reducer,1,NaN,00773700900000000
3,1040005840,Bolt M16×100-10.9,20,GB/T1228,00773700900000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040004518,Bolt M8×20-8.8,15,GB/T5783,00773702820000001
1,1040301510,Washer 8,13,GB/T93,00773702820000001
2,1040301515,Washer 8-200HV,42,GB/T97.1,00773702820000001
3,00773602800001020 Cover,NaN,1,NaN,00773702820000001
4,00773602800600000 Floating cylinder,NaN,2,NaN,00773702820000001
5,1040302493,Washer 20-200HV,8,GB/T97.1,00773702820000001
6,1040003572,Bolt M20×55-10.9-DKL,8,GB/T5783,00773702820000001
7,1040004649,Screw 5/8-11UNC×45-10.9,24,ANSIB18.3,00773702820000001
8,1040302492,Washer 16-200HV,24,GB/T97.1,00773702820000001
9,1030202174,Reducer,4,NaN,00773702820000001
10,1030800696,Tire 33×12D610-R,2,NaN,00773702820000001
11,1040202297,Nut M16×1.5-10 (Spiral),36,GB/T6177.2,00773702820000001
12,00773402800001280 Chassis valve block moun...,NaN,1,NaN,00773702820000001
13,00771102810001110 Cover,NaN,4,NaN,00773702820000001
14,1040004517,Bolt M8×16-8.8,43,GB/T5783,00773702820000001
15,00771102800001130 Cover,NaN,1,NaN,00773702820000001
16,00771102810001100 Cover,NaN,2,NaN,00773702820000001
17,00771102810001120 Cover,NaN,2,NaN,00773702820000001
18,1030800695,Tire 33×12D610-L,2,NaN,00773702820000001
19,00773602800001010 Frame cover,NaN,1,NaN,00773702820000001
20,00773602800200001 Frame welding parts,NaN,1,NaN,00773702820000001
21,00773702821000000 Chassis weight I,NaN,1,NaN,00773702820000001
22,1040302483,Washer 20-200HV,4,GB/T96.1,00773702820000001
23,1040201884,Nut M24x3,4,GB/T6170,00773702820000001
24,00773702821200000 Chassis weight II,NaN,1,NaN,00773702820000001

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773602800001030 Steering knuckle upper c...,NaN,2.0,NaN,00773702820000001
1,1040004511,Bolt M6×16-A2-70,4.0,GB/T5783,00773702820000001
2,00773400200001070 Stop pin,NaN,4.0,NaN,00773702820000001
3,00773702800001150 Pin ÿ,NaN,2.0,NaN,00773702820000001
4,00773702800001020 Pin,NaN,2.0,NaN,00773702820000001
5,00773702800001201 Steering knuckle lower w...,NaN,2.0,NaN,00773702820000001
6,00773702800001031 Wear plate on steering ...,NaN,2.0,NaN,00773702820000001
7,00773700400001130 Bearing,NaN,4.0,NaN,00773702820000001
8,00773602800800000 Steering knuckle I,NaN,1.0,NaN,00773702820000001
9,00773402810001142 Motor oil pipe bracket I,NaN,2.0,NaN,00773702820000001
10,00773402810001151 Motor oil pipe fixing ring,NaN,2.0,NaN,00773702820000001
11,1040200503,Nut M8-8,4.0,GB/T889.1,00773702820000001
12,1040002437,Bolt M12×35-8.8,4.0,GB/T5783,00773702820000001
13,1040002555,bolt,4.0,GB/T5783,00773702820000001
14,00773702800400001 Front axle weldment,NaN,1.0,NaN,00773702820000001
15,00773602801400000 Steering cylinder,NaN,2.0,NaN,00773702820000001
16,00771600301001250 Stop pin,NaN,6.0,NaN,00773702820000001
17,00773402810001260 Bearing,NaN,6.0,NaN,00773702820000001
18,00773702800001340 Pin VI,NaN,6.0,NaN,00773702820000001
19,1040002433,Bolt M10×20-8.8,6.0,GB/T5783,00773702820000001
20,00773702802000000 Steering link,NaN,1.0,NaN,00773702820000001
21,00773702800001220 Lubrication-free bearing,NaN,2.0,NaN,00773702820000001
22,00773702800001330 Pin,NaN,1.0,NaN,00773702820000001
23,00773400400001250 Stop pin,NaN,1.0,NaN,00773702820000001
24,1040002446,Bolt M16×40-8.8,1.0,NaN,00773702820000001
25,00773602801200000 Steering knuckle II,NaN,1.0,NaN,00773702820000001
26,204050239,Mobil Synthetic Gear Oil,NaN,SHC220-P20L(New),00773702820000001

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040004519,bolt,12,GB/T5783,Exhaust s ystem 00773607101000000
1,1040301515,washer,24,GB/T97.1,Exhaust s ystem 00773607101000000
2,00773407141001240 Exhaust pipe I,NaN,1,NaN,Exhaust s ystem 00773607101000000
3,1040004619,bolt,12,GB/T5783,Exhaust s ystem 00773607101000000
4,1040200398,Nuts,12,GB/T6177.1,Exhaust s ystem 00773607101000000
5,00773407141020000 Muffler bracket,NaN,1,NaN,Exhaust s ystem 00773607101000000
6,00773407141001220 Muffler,NaN,2,GB/T97.1,Exhaust s ystem 00773607101000000
7,00773407151001060 Sealing gasket,NaN,2,NaN,Exhaust s ystem 00773607101000000
8,00773607101001040 Exhaust pipe ÿ,NaN,1,NaN,Exhaust s ystem 00773607101000000
9,1040200503,Nuts,8,GB/T889.1,Exhaust s ystem 00773607101000000
10,00773407101001030 Reinforcement plate,NaN,1,NaN,Exhaust s ystem 00773607101000000
11,00773607101001030 Exhaust tail pipe,NaN,1,NaN,Exhaust s ystem 00773607101000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773407140801050 Intake pipe,NaN,1,NaN,Intake system 00773607100800000
1,1990202290,Spiral turbine vortex rod,2,NaN,Intake system 00773607100800000
2,1000100391,clamp air filter assembly,1,NaN,Intake system 00773607100800000
3,1040200503,Nuts,4,GB/T889.1,Intake system 00773607100800000
4,1040301515,washer,4,GB/T97.1,Intake system 00773607100800000
5,1040004520,bolt,2,GB/T5783,Intake system 00773607100800000
6,00771107121001060 Double side pipe clamp,NaN,1,NaN,Intake system 00773607100800000
7,00773407140801030 Intake steel pipe,NaN,1,NaN,Intake system 00773607100800000
8,00773607100801020 Air intake hose ÿ,NaN,1,NaN,Intake system 00773607100800000
9,00773407140801040 Bend plate I,NaN,1,NaN,Intake system 00773607100800000
10,1040004517,bolt,2,GB/T5783,Intake system 00773607100800000
11,1040302480,washer,2,GB/T96.1,Intake system 00773607100800000
12,1040004519,bolt,2,GB/T5783,Intake system 00773607100800000
13,00773407140801020 Air intake hose II,NaN,1,NaN,Intake system 00773607100800000
14,1990202288,Spiral turbine shaft clamp,3,NaN,Intake system 00773607100800000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00771007100601060 Plate ÿ,NaN,2,NaN,Cooling s ystem 00773607100600000
1,1040004520,bolt,10,GB/T5783,Cooling s ystem 00773607100600000
2,1040301515,washer,30,GB/T97.1,Cooling s ystem 00773607100600000
3,00771007100601050 Plate II Bolt,NaN,2,NaN,Cooling s ystem 00773607100600000
4,1040004518,NaN,4,GB/T5783,Cooling s ystem 00773607100600000
5,00771007100601010 Windshield,NaN,1,NaN,Cooling s ystem 00773607100600000
6,1040200170,Nuts,4,GB/T889,Cooling s ystem 00773607100600000
7,00771007100601020 Bend plate ÿ,NaN,1,NaN,Cooling s ystem 00773607100600000
8,00773407140601040 Return pipe I,NaN,1,NaN,Cooling s ystem 00773607100600000
9,00773407100601140 Pad,NaN,6,NaN,Cooling s ystem 00773607100600000
10,1040302821,washer,4,GB/T96.1,Cooling s ystem 00773607100600000
11,00773407100601130 Sponge strip,NaN,2,NaN,Cooling s ystem 00773607100600000
12,1040002262,bolt,4,GB/T5783,Cooling s ystem 00773607100600000
13,00773407140601050 Return pipe II,NaN,1,NaN,Cooling s ystem 00773607100600000
14,1990202287,Spiral turbine shaft clamp,8,NaN,Cooling s ystem 00773607100600000
15,00773407140601070 Connector II,NaN,1,NaN,Cooling s ystem 00773607100600000
16,1990202282,Turbine worm rod clamp,2,NaN,Cooling s ystem 00773607100600000
17,00771007100601030 Bend plate ÿ,NaN,1,NaN,Cooling s ystem 00773607100600000
18,00773407140601080 Water supply pipe,NaN,1,NaN,Cooling s ystem 00773607100600000
19,1000200483,Radiator,1,NaN,Cooling s ystem 00773607100600000
20,00773407140601020 water outlet pipe I,NaN,1,assembly,Cooling s ystem 00773607100600000
21,00773407140601060 Connector I,NaN,1,NaN,Cooling s ystem 00773607100600000
22,00773407140601030 Water outlet pipe II,NaN,1,NaN,Cooling s ystem 00773607100600000
23,00773407140601090 Steam hose I,NaN,1,NaN,Cooling s ystem 00773607100600000
24,1000300735,Expansion tank,1,NaN,Cooling s ystem 00773607100600000
25,1990202279,Turbine shaft clamp,4,NaN,Cooling s ystem 00773607100600000
26,00773407140601100 Steam hose II,NaN,1,NaN,Cooling s ystem 00773607100600000
27,1040004619,bolt,4,GB/T5783,Cooling s ystem 00773607100600000
28,1040004517,bolt,12,GB/T5783,Cooling s ystem 00773607100600000
29,00773407140601010 Water tank mounting plate,NaN,1,NaN,Cooling s ystem 00773607100600000
30,1040200503,Nuts,18,GB/T889.1,Cooling s ystem 00773607100600000
31,00771007100601040 Bend plate ÿ,NaN,1,NaN,Cooling s ystem 00773607100600000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773407140401130 Throttle flexible shaft,NaN,1,NaN,Fuel s ystem 0 0773607100400000
1,1040102372,hexagon socket head screw,10,GB/T70.1,Fuel s ystem 0 0773607100400000
2,00773407140401140 Throttle lever,NaN,1,NaN,Fuel s ystem 0 0773607100400000
3,1040200304,Nuts,1,GB/T889,Fuel s ystem 0 0773607100400000
4,1040300771,washer,9,GB/T97.1,Fuel s ystem 0 0773607100400000
5,00773407140401120 Bend plate III,NaN,1,NaN,Fuel s ystem 0 0773607100400000
6,1040004619,bolt,4,GB/T5783,Fuel s ystem 0 0773607100400000
7,1040301515,washer,6,GB/T97.1,Fuel s ystem 0 0773607100400000
8,00773407140401070 Bending plate II,NaN,1,NaN,Fuel s ystem 0 0773607100400000
9,1040004519,bolt,2,GB/T5783,Fuel s ystem 0 0773607100400000
10,1990202279,Turbine shaft clamp,18,NaN,Fuel s ystem 0 0773607100400000
11,00773607100401060 Fuel pipe ÿ,NaN,1,NaN,Fuel s ystem 0 0773607100400000
12,00773607100401120 Fuel pipe VI,NaN,1,NaN,Fuel s ystem 0 0773607100400000
13,00773607100401080 Fuel pipe IV,NaN,1,NaN,Fuel s ystem 0 0773607100400000
14,00773607100401070 Fuel pipe ÿ,NaN,1,NaN,Fuel s ystem 0 0773607100400000
15,00773407140401090 Tee connector,NaN,1,NaN,Fuel s ystem 0 0773607100400000
16,00773607100401030 Fuel pipe ÿ,NaN,1,NaN,Fuel s ystem 0 0773607100400000
17,00773407140401060 Fuel pipe ÿ,NaN,1,NaN,Fuel s ystem 0 0773607100400000
18,00773407100401060 Hollow bolt,NaN,2,NaN,Fuel s ystem 0 0773607100400000
19,1081000673,Combined sealing gasket,4,NaN,Fuel s ystem 0 0773607100400000
20,00773407100401050 Connector II Plastic,NaN,2,NaN,Fuel s ystem 0 0773607100400000
21,1990200692,coated strip,5,NaN,Fuel s ystem 0 0773607100400000
22,1040201896,Nuts,2,GB/T889.1,Fuel s ystem 0 0773607100400000
23,1000400478,Oil-water separator,1,NaN,Fuel s ystem 0 0773607100400000
24,00773607100401020 Fuel pipe ÿ bolt,NaN,1,NaN,Fuel s ystem 0 0773607100400000
25,1040002434,NaN,4,GB/T5783,Fuel s ystem 0 0773607100400000
26,1040200503,Nuts,10,GB/T889.1,Fuel s ystem 0 0773607100400000
27,1040302480,washer,4,GB/T96.1,Fuel s ystem 0 0773607100400000
28,1040302512,washer,4,GB/T96.1,Fuel s ystem 0 0773607100400000
29,00773607100401040 Fuel pipe VIII,NaN,1,NaN,Fuel s ystem 0 0773607100400000
30,00773607100401050 Fuel pipe ÿ,NaN,1,NaN,Fuel s ystem 0 0773607100400000
31,00773607100401010 Fuel tank assembly,NaN,1,NaN,Fuel s ystem 0 0773607100400000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1000000823,specification diesel engine,1,NaN,Engine 00773607100200000
1,1040003912,bolt,4,GB/T5783,Engine 00773607100200000
2,1040302492,washer,4,GB/T97.1,Engine 00773607100200000
3,00773407140201060 Washer,NaN,16,NaN,Engine 00773607100200000
4,1040302490,washer,15,GB/T97.1,Engine 00773607100200000
5,1040002273,bolt,15,GB/T5786,Engine 00773607100200000
6,00773407140201040 Bend plate III,NaN,1,NaN,Engine 00773607100200000
7,00773407140201050 Bend plate V,NaN,4,NaN,Engine 00773607100200000
8,1009900979,engine shock absorber,8,NaN,Engine 00773607100200000
9,00773407100201050 Pad,NaN,1,NaN,Engine 00773607100200000
10,1040200161,Nuts,4,GB/T889,Engine 00773607100200000
11,00773407140201010 Coupling cover screw,NaN,1,NaN,Engine 00773607100200000
12,1040100097,NaN,8,GB/T70.1,Engine 00773607100200000
13,1040101692,bolt,3,GB/T5786,Engine 00773607100200000
14,1009900968,Elastic coupling assembly,1,NaN,Engine 00773607100200000
15,00773407140201020 Bend plate I,NaN,1,NaN,Engine 00773607100200000
16,00773407140201030 Bending plate II,NaN,1,NaN,Engine 00773607100200000
17,1040302489,washer,1,GB/T97.1,Engine 00773607100200000
18,1040003357,bolt,1,GB/T5786,Engine 00773607100200000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040101492,Screw M10×25-8.8,2,GB/T70.1,00773705240200000
1,1040301502,Washer 10,2,GB/T93,00773705240200000
2,1010601341,Return oil filter,1,NaN,00773705240200000
3,1140101628,Plug,1,NaN,00773705240200000
4,1040005852,Bolt M12×20-8.8,4,GB/T5787,00773705240200000
5,1140103362,Straight end connector,2,NaN,00773705240200000
6,1140101466,Straight end connector,1,NaN,00773705240200000
7,1140114040,Straight end connector,1,NaN,00773705240200000
8,1019901354,Liquid level and temperature gauge,1,NaN,00773705240200000
9,00773605200210000 Fuel tank,NaN,1,NaN,00773705240200000
10,00773405200230000 Sealing plate,NaN,1,NaN,00773705240200000
11,00773405200220001 Window cover,NaN,1,NaN,00773705240200000
12,1040301510,Washer 8,8,GB/T93,00773705240200000
13,1040103111,Screw M8×16-8.8,8,GB/T70.1,00773705240200000
14,1010500489,Air Filter,1,NaN,00773705240200000
15,1140113717,Straight end connector,1,NaN,00773705240200000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1010002352,Travel pump,1,NaN,00773705200400000
1,1140115078,Straight end connector,1,NaN,00773705200400000
2,1140114946,Straight end connector,1,NaN,00773705200400000
3,1140115370,Straight end connector,2,NaN,00773705200400000
4,1140103362,Straight end connector,1,NaN,00773705200400000
5,1010001908,Gear Pumps,1,NaN,00773705200400000
6,1040004653,Bolt M12×30-10.9,2,GB/T15783,00773705200400000
7,1140114045,Straight end connector,1,NaN,00773705200400000
8,1140111770,Straight end connector,2,NaN,00773705200400000
9,1040004029,Screw M12×35-10.9,2,GB/T5783,00773705200400000
10,1040301503,Washer 12,4,GB/T93,00773705200400000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1010101256,Travel motor,4,NaN,00773605200610000
1,1140113353,Straight end connector,4,NaN,00773605200610000
2,1149901795,Straight end connector,8,NaN,00773605200610000
3,00773605200601010 Gasket,NaN,8,ÿ24,00773605200610000
4,1040004029,Bolt M12×35-10.9,8,GB/T5783-2000,00773605200610000
5,1140114623,Straight end connector,4,NaN,00773605200610000
6,1140114622,Adjustable elbow joint,4,Motor X1 port,00773605200610000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140101534,Right angle combination connector,2,NaN,00773705220800000
1,1140114187,Pressure test connector,1,NaN,00773705220800000
2,1140101523,Straight end connector,2,NaN,00773705220800000
3,1140101461,Straight end connector,1,NaN,00773705220800000
4,11140101464,Straight end connector,8,NaN,00773705220800000
5,1040301515,Washer 8-200HV,4,GB/T97.1,00773705220800000
6,1040004517,Bolt M8×16-8.8,4,GB/T5783,00773705220800000
7,1019807528,Travel diverter valve,1,NaN,00773705220800000
8,1140101820,Straight end connector,1,NaN,00773705220800000
9,1140101478,Right angle combination connector,2,NaN,00773705220800000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040200503,Nut M8-8,2,GB/T889.1,00773705241000000-
1,1010307588,Travel control valve,1,NaN,00773705241000000-
2,1019900975,Plug,3,NaN,00773705241000000-
3,1140101461,Straight end connector,4,NaN,00773705241000000-
4,1040102738,Bolt M8×55-8.8,2,GB/T70.1,00773705241000000-
5,1140114187,Pressure test connector,2,NaN,00773705241000000-
6,1140114040,Straight end connector,1,NaN,00773705241000000-

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140101475,Straight end connector,2,NaN,00773705221200000
1,1140114948,Straight-through extension connector,1,NaN,00773705221200000
2,1140101476,Right angle combination connector,4,NaN,00773705221200000
3,1140111237,Straight end connector,1,NaN,00773705221200000
4,1140114620,Straight end connector,2,NaN,00773705221200000
5,1140101461,Straight end connector,2,NaN,00773705221200000
6,1040201904,Nut M5-8,2,GB/T889.1,00773705221200000
7,1040100438,Screw M5×55-8.8,2,GB/T70.1,00773705221200000
8,1010306016,Platform selector valve,1,NaN,00773705221200000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040002433,Bolt M10×20-8.8,4,GB/T5783,00773705241400000
1,1040302489,Washer 10,4,GB/T97.1,00773705241400000
2,1010601369,Low pressure filter,1,NaN,00773705241400000
3,1140101820,Straight end connector,2,NaN,00773705241400000
4,1140101489,Three-way combination connector,1,NaN,00773705241400000
5,1140101478,Right angle combination connector,2,NaN,00773705241400000
6,1140103282,Butt-jointed reducer,1,NaN,00773705241400000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140101476,Right angle combination connector,6,NaN,00773705251600000
1,1140114647,Straight-through extension connector,2,NaN,00773705251600000
2,1140101941,Straight end connector,3,NaN,00773705251600000
3,1149902022,Straight-through extension connector,1,NaN,00773705251600000
4,1010307824,Main valve,1,NaN,00773705251600000
5,1040302480,Washer 8,4,GB/T96.1,00773705251600000
6,1040004517,Bolt M8×16-8.8,4,GB/T578,00773705251600000
7,1140114187,Pressure test connector,1,NaN,00773705251600000
8,1140101477,Straight end connector,4,NaN,00773705251600000
9,1140101478,Right angle combination connector,2,NaN,00773705251600000
10,1149901685,Straight-through extension connector,1,NaN,00773705251600000
11,1140103282,Butt-jointed reducer,1,NaN,00773705251600000
12,1140114451,45 degree combination joint,1,NaN,00773705251600000
13,1140101462,Straight end connector,3,NaN,00773705251600000
14,1140101464,Straight end connector,1,NaN,00773705251600000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140101478,Right angle combination connector,1.0,NaN,00773605201800000
1,1140101464,Straight end connector,2.0,NaN,00773605201800000
2,1010601138,High pressure filter,1.0,NaN,00773605201800000
3,1140000098,Bolt M10×20-8.8,2.0,GB/T5783,00773605201800000
4,1040302489,Washer 10-200HV,2.0,GB/T97.1,00773605201800000
5,1010302829,Check valve,NaN,GB/T93,00773605201800000
6,1010302829,Washer 8-200HV,4.0,GB/T97.1,00773605201800000
7,1140101464,Straight end connector,2.0,NaN,00773605201800000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1010001903,Emergency motor pump,1,NaN,00773605202000000
1,1040302489,Washer 10,2,GB/T97.1,00773605202000000
2,1040004646,Screw M10×15-8.,2,GB/T5783,00773605202000000
3,1040114040,Straight end connector,1,NaN,00773605202000000
4,1040101461,Straight end connector,1,NaN,00773605202000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140114620,Straight end connector,1,NaN,00773705232200000
1,1140101461,Straight end connector,5,NaN,00773705232200000
2,1010306616,Platform selector valve,1,NaN,00773705232200000
3,1040100438,Screw M5×55-8.8,2,GB/T70.1,00773705232200000
4,1040201904,Nut M5-8,2,GB/T889.1,00773705232200000
5,1040302529,Washer 5,2,GB/T96.1,00773705232200000
6,1140101476,Right angle combination connector,2,NaN,00773705232200000
7,1140114451,45 degree right angle combination connector,2,NaN,00773705232200000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040101628,Screw plug,1,NaN,00773605202600000
1,1019807719,Integrated oil return block,1,NaN,00773605202600000
2,1040200503,Nut M8-8,2,GB/T889.1,00773605202600000
3,1140101463,Straight end connector,4,NaN,00773605202600000
4,1140101820,Straight end connector,1,NaN,00773605202600000
5,1040102037,Bolt M8×70-8.8,2,GB/T70.1,00773605202600000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140114451,elbow,1,NaN,00773705242800000
1,1140112827,Straight end connector,4,NaN,00773705242800000
2,1010306368,Cylinder control valve,1,NaN,00773705242800000
3,1040301510,Washer 8,2,GB/T93,00773705242800000
4,1040004522,Screw M8×50-8.8,2,GB/T5783,00773705242800000
5,1140101476,elbow,2,NaN,00773705242800000
6,1140114046,Tee Connector,1,NaN,00773705242800000
7,1140101793,Tee Connector,1,NaN,00773705242800000
8,1140112820,Straight end connector,1,NaN,00773705242800000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040103114,Screw M8×45-8.8,4,GB/T70.1,00773605203000000
1,1040301510,Washer 8,4,GB/T93,00773605203000000
2,1010306638,Upper leveling cylinder valve,1,NaN,00773605203000000
3,1140114700,Straight end connector,2,NaN,00773605203000000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1040100148,Screw M8×45-8.8,4,GB/T5783,00773605203200000
1,1040301510,Washer 8,4,GB/T93,00773605203200000
2,1010306020,Balancing valve,1,NaN,00773605203200000
3,1140114839,Articulated joints,2,NaN,00773605203200000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140101462,Straight end connector,1,NaN,00773605203400000
1,1140101462,Straight end connector,1,NaN,00773605203400000
2,1040102739,Screw M8×60-8.8,4,GB/T70.1,00773605203400000
3,1040301510,Washer 8,4,GB/T93,00773605203400000
4,1010306616,Luffing balancing valve,1,NaN,00773605203400000
5,1019900975,Plug,1,NaN,00773605203400000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140101477,Right angle combination elbow,1,NaN,00773605203600000
1,1140101462,Straight end connector,1,NaN,00773605203600000
2,1010306616,Luffing balancing valve,1,NaN,00773605203600000
3,1040301510,Washer 8,4,GB/T93,00773605203600000
4,1040102739,Screw M8×60-8.8,4,GB/T70.1,00773605203600000
5,1140101477,Straight end connector,1,NaN,00773605203600000
6,1140101462,Right angle combination elbow,1,NaN,00773605203600000
7,1019900975,Plug,1,NaN,00773605203600000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140101483,specification Tee combination joint,1,NaN,00773605203600000
1,1140101483,Three-way combination connector,1,NaN,00773605203600000
2,1149901685,Straight end connector,1,NaN,00773605203600000
3,1140101462,Straight end connector,1,NaN,00773605203600000
4,1010306616,Luffing balancing valve,1,NaN,00773605203600000
5,1019900975,Plug,1,NaN,00773605203600000
6,1149900295,tee combination joint,1,Explosion-proof valve solution only,00773605203600000
7,1140101475,Right angle combination elbow,2,Explosion-proof valve solution only,00773605203600000
8,1040301510,Washer 8,4,GB/T93,00773605203600000
9,1040102739,Screw M8×60-8.8,4,GB/T70.1,00773605203600000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1140108904,elbow,2,NaN,00773705245200000
1,1040114701,Straight-through extension connector,2,NaN,00773705245200000
2,1040101464,Straight end connector,3,NaN,00773705245200000
3,1040101461,Straight end connector,14,NaN,00773705245200000
4,1040004653,Bolt M12×30-10.9,4,GB/T5783,00773705245200000
5,1140101476,elbow,3,NaN,00773705245200000
6,1040302821,Washer 12,4,GB/T96.1,00773705245200000
7,1011200104,Center swivel joint,1,NaN,00773705245200000
8,1140101523,Straight end connector,2,NaN,00773705245200000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1010400309,heat sink,1,NaN,00773605205400000
1,1140101464,Straight end connector,2,NaN,00773605205400000
2,1140101478,Right angle combination connector,1,NaN,00773605205400000
3,1040301515,Washer 8,4,GB/T97.1,00773605205400000
4,1040004517,Bolt M8×16-8.8,4,GB/T5783,00773605205400000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,/,Turntable electric control box 1,/,NaN,Turntable c able h arness 00773706240630010
1,/,Turntable electric control box 2,/,NaN,Turntable c able h arness 00773706240630010
2,1020202125,Solenoid unloading valve,1,NaN,Turntable c able h arness 00773706240630010
3,/,Main boom retract valve,/,NaN,Turntable c able h arness 00773706240630010
4,/,Turntable right turn valve,/,NaN,Turntable c able h arness 00773706240630010
5,/,Front wheel right turn valve,/,NaN,Turntable c able h arness 00773706240630010
6,/,Platform action main control valve 1 rise,/,NaN,Turntable c able h arness 00773706240630010
7,/,Fuel level,/,NaN,Turntable c able h arness 00773706240630010
8,/,Tower Boom Lift Valve,/,NaN,Turntable c able h arness 00773706240630010
9,/,Turntable left turn valve,/,NaN,Turntable c able h arness 00773706240630010
10,/,Front wheel left turn valve,/,NaN,Turntable c able h arness 00773706240630010
11,/,Platform action main control valve 2 down,/,NaN,Turntable c able h arness 00773706240630010
12,/,Main boom lifting valve,/,NaN,Turntable c able h arness 00773706240630010
13,/,Main boom extension valve,/,NaN,Turntable c able h arness 00773706240630010
14,/,Tower arm stowed position limit switch 2,/,NaN,Turntable c able h arness 00773706240630010
15,/,heat sink,/,NaN,Turntable c able h arness 00773706240630010
16,/,Float control valve,/,NaN,Turntable c able h arness 00773706240630010
17,/,Two-speed valve,/,NaN,Turntable c able h arness 00773706240630010
18,/,Brake valve,/,NaN,Turntable c able h arness 00773706240630010
19,/,Body tilt sensor,/,NaN,Turntable c able h arness 00773706240630010
20,/,Angle limit switch,/,NaN,Turntable c able h arness 00773706240630010
21,1021404019,Alarm buzzer,NaN,NaN,Turntable c able h arness 00773706240630010
22,1020516032,Fuel Pump,1,NaN,Turntable c able h arness 00773706240630010
23,00773606200420000 Oil-water separator,NaN,1,NaN,Turntable c able h arness 00773706240630010
24,1020404399,Tower arm stowed position limit switch 1,1,NaN,Turntable c able h arness 00773706240630010
25,/,Working warning light,/,NaN,Turntable c able h arness 00773706240630010
26,/,Tower arm upper limit switch,/,NaN,Turntable c able h arness 00773706240630010
27,/,Battery positive,/,NaN,Turntable c able h arness 00773706240630010
28,/,Ground,/,NaN,Turntable c able h arness 00773706240630010
29,1020304982,Leveling selector valve,1,NaN,Turntable c able h arness 00773706240630010

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773606200410000 Turntable cable harness,NaN,1,NaN,ECU c able harness 0 0773606200420000
1,/,Back valve,/,NaN,ECU c able harness 0 0773606200420000
2,/,Forward valve,/,NaN,ECU c able harness 0 0773606200420000
3,/,dynamo,/,NaN,ECU c able harness 0 0773606200420000
4,/,Oil pressure,/,NaN,ECU c able harness 0 0773606200420000
5,/,Starter motor relay,/,NaN,ECU c able harness 0 0773606200420000
6,1020104107,Throttle motor,1,NaN,ECU c able harness 0 0773606200420000
7,/,Coolant temperature,/,NaN,ECU c able harness 0 0773606200420000
8,/,Glow plug,/,NaN,ECU c able harness 0 0773606200420000
9,1020305006,Preheat relay,1,NaN,ECU c able harness 0 0773606200420000
10,/,Air filter blockage alarm,/,NaN,ECU c able harness 0 0773606200420000
11,/,Start-Stop Valve,/,NaN,ECU c able harness 0 0773606200420000
12,/,Coolant level,/,NaN,ECU c able harness 0 0773606200420000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,/,Turntable electric control box,/,NaN,00773606200430000
1,/,Tower arm lowering valve left,/,NaN,00773606200430000
2,/,Tower arm lowering valve right,/,NaN,00773606200430000
3,/,Main boom lowering valve,/,NaN,00773606200430000
4,/,Terminal resistance,/,NaN,00773606200430000
5,1020516032,Boom length limit switch 2,1,NaN,00773606200430000
6,1020516032,Boom length limit switch 1,1,NaN,00773606200430000
7,1021404018,Dual angle tilt sensor,1,NaN,00773606200430000
8,00773606200610000 Drag chain cable,NaN,1,NaN,00773606200430000

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,00773406200210000 Platform electric control...,NaN,1,NaN,Platform cable harness 0 0773606200440000 Drag...
1,00773406200210000 Platform electric control...,NaN,0,NaN,Platform cable harness 0 0773606200440000 Drag...
2,1020521022,Foot switch,1,NaN,Platform cable harness 0 0773606200440000 Drag...
3,/,Platform rotary selector valve,/,NaN,Platform cable harness 0 0773606200440000 Drag...
4,1021404016,Load Cells,1,NaN,Platform cable harness 0 0773606200440000 Drag...
5,00773606200430000 Boom cable harness,NaN,0,NaN,Platform cable harness 0 0773606200440000 Drag...
6,/,Anti-crush switch,1,NaN,Platform cable harness 0 0773606200440000 Drag...

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1029905348,Battery,1,NaN,00773706230230040
1,1020605356,Ring insurance,2,NaN,00773706230230040
2,0067220632181001A-c,Ring safety bracket,2,NaN,00773706230230040
3,1020402443,Insulation nut,2,NaN,00773706230230040
4,00773606200450050 Auxiliary power pump and...,NaN,1,NaN,00773706230230040
5,00773606200450070 Battery positive pole an...,NaN,1,NaN,00773706230230040
6,00773406200450020 Battery negative terminal...,NaN,1,NaN,00773706230230040
7,1029900667,Manual switch,1,NaN,00773706230230040
8,00773406200450030 Manual switch to ground ...,NaN,1,NaN,00773706230230040
9,00773406200450060 Engine and negative grou...,NaN,1,NaN,00773706230230040
10,/,Grounding stud,1,NaN,00773706230230040
11,00773606200450080 Connection between starti...,NaN,/,NaN,00773706230230040
12,1020305006,DC contactor,1,NaN,00773706230230040
13,00773406200450010 Battery and starter moto...,NaN,1,NaN,00773706230230040
14,00773606200450010 Negative grounding and a...,NaN,1,NaN,00773706230230040

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1020810958,Rocker switch,1,Emergency power and enabling,Platform electric c ontrol b ox a ssembly 0 07...
1,1020521445,Rocker switch,1,Drive orientation,Platform electric c ontrol b ox a ssembly 0 07...
2,1020521444,Rocker switch,1,lighting,Platform electric c ontrol b ox a ssembly 0 07...
3,1020521443,Rocker switch,1,Walking speed control,Platform electric c ontrol b ox a ssembly 0 07...
4,1020405061,Alarm indicator panel,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
5,00773406200211050 Platform electric control...,NaN,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
6,1020502039,Emergency stop button,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
7,1020509007,Button seat,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
8,1020521445,Rocker switch,1,Platform leveling,Platform electric c ontrol b ox a ssembly 0 07...
9,1029802085,Nylon plug,5,NaN,Platform electric c ontrol b ox a ssembly 0 07...
10,1029804205,Clamp nut,5,NaN,Platform electric c ontrol b ox a ssembly 0 07...
11,1020520994,handle,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
12,1020520995,Potentiometer,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
13,1020521445,Toggle switch,1,Platform rotation switch,Platform electric c ontrol b ox a ssembly 0 07...
14,1020521445,Toggle switch,1,Flying arm lifting switch,Platform electric c ontrol b ox a ssembly 0 07...
15,1020521445,Toggle switch,1,Boom extension,Platform electric c ontrol b ox a ssembly 0 07...
16,1020521445,Toggle switch,1,Tower boom lifting,Platform electric c ontrol b ox a ssembly 0 07...
17,1020520993,handle,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
18,1020202105,IO Modules,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
19,1022399012,Cable Trough,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
20,1020404405,Flash Buzzer,1,NaN,Platform electric c ontrol b ox a ssembly 0 07...
21,1029498090,terminal,7,NaN,Platform electric c ontrol b ox a ssembly 0 07...
22,1029905392,terminal,4,NaN,Platform electric c ontrol b ox a ssembly 0 07...
23,1029498090,terminal,4,NaN,Platform electric c ontrol b ox a ssembly 0 07...
24,1020703394,DEUTSCH Connectors,1,Drag chain cable harness,Platform electric c ontrol b ox a ssembly 0 07...
25,1020703393,Round connector,1,Platform cable harness,Platform electric c ontrol b ox a ssembly 0 07...

,Material Code,Name and specifications,Number of pieces,Remark,Section
0,1020201651,Display,1,NaN,Turntable e lectric control b ox a ssembly 0 0...
1,1020520084,Toggle switch,1,Platform rotation,Turntable e lectric control b ox a ssembly 0 0...
2,1020520084,Toggle switch,1,Platform leveling,Turntable e lectric control b ox a ssembly 0 0...
3,1020520084,Toggle switch,1,Flying boom lift,Turntable e lectric control b ox a ssembly 0 0...
4,1020520084,Toggle switch,1,Boom extension,Turntable e lectric control b ox a ssembly 0 0...
5,1020520084,Toggle switch,1,Boom lifting,Turntable e lectric control b ox a ssembly 0 0...
6,1020519658,Emergency stop button,1,Emergency stop switch,Turntable e lectric control b ox a ssembly 0 0...
7,1020509007,Button seat,1,NaN,Turntable e lectric control b ox a ssembly 0 0...
8,1020520084,Toggle switch,1,Tower boom lifting,Turntable e lectric control b ox a ssembly 0 0...
9,1020520943,Key switch,1,NaN,Turntable e lectric control b ox a ssembly 0 0...
10,1020520084,Toggle switch,1,Turntable rotation,Turntable e lectric control b ox a ssembly 0 0...
11,1020520084,Toggle switch,1,Emergency power and enabling,Turntable e lectric control b ox a ssembly 0 0...
12,1020304559,Relay,1,Lighting relay,Turntable e lectric control b ox a ssembly 0 0...
13,1020304559,Relay,1,Parking valve relay,Turntable e lectric control b ox a ssembly 0 0...
14,1020604934,Terminal Blocks,11,NaN,Turntable e lectric control b ox a ssembly 0 0...
15,1020704265,Ground terminal block,3,NaN,Turntable e lectric control b ox a ssembly 0 0...
16,1020705826,Diode Terminals,2,NaN,Turntable e lectric control b ox a ssembly 0 0...
17,1029904980,Terminal Blocks,9,NaN,Turntable e lectric control b ox a ssembly 0 0...
18,1029903317,48 core sheath,1,Turntable cable harness,Turntable e lectric control b ox a ssembly 0 0...
19,1029902634,32 core sheath,1,Turntable cable harness,Turntable e lectric control b ox a ssembly 0 0...
20,1029902634,32 core sheath,1,Boom cable harness,Turntable e lectric control b ox a ssembly 0 0...
21,1020304584,Power relay,1,System power supply,Turntable e lectric control b ox a ssembly 0 0...
22,1020304584,Power relay,1,Start the motor,Turntable e lectric control b ox a ssembly 0 0...
23,1020304584,Power relay,1,Radiator,Turntable e lectric control b ox a ssembly 0 0...
24,1020304584,Power relay,1,Fuel pump,Turntable e lectric control b ox a ssembly 0 0...
25,1020103903,Controller,1,NaN,Turntable e lectric control b ox a ssembly 0 0...
26,1020103955,Connector components,1,NaN,Turntable e lectric control b ox a ssembly 0 0...

,Material Code,Name and specifications,Number of pieces,Remark,Section,No. 1,Name and specifications
0,00773400100261030,Plate II,1,NaN,Work platform 00773600130000000,NaN,NaN
1,1040005844,bolt,4,NaN,Work platform 00773600130000000,NaN,NaN
2,1040300771,Washer 6-200HV,32,GB/T5783-2000,Work platform 00773600130000000,NaN,NaN
3,00773400100260020,Protective cover,1,GB/T97.1-2002,Work platform 00773600130000000,NaN,NaN
4,00773400100261060,bolt,2,NaN,Work platform 00773600130000000,NaN,NaN
...,...,...,...,...,...,...,...
807,1020304584,Power relay,1,Start the motor,Turntable e lectric control b ox a ssembly 0 0...,NaN,NaN
808,1020304584,Power relay,1,Radiator,Turntable e lectric control b ox a ssembly 0 0...,NaN,NaN
809,1020304584,Power relay,1,Fuel pump,Turntable e lectric control b ox a ssembly 0 0...,NaN,NaN
810,1020103903,Controller,1,NaN,Turntable e lectric control b ox a ssembly 0 0...,NaN,NaN
811,1020103955,Connector components,1,NaN,Turntable e lectric control b ox a ssembly 0 0...,NaN,NaN

,Material No.,Item and Spec,Кол-во,Remark,Section,No. 1
0,00773400100261030,Plate II,1,NaN,Work platform 00773600130000000,NaN
1,1040005844,bolt,4,NaN,Work platform 00773600130000000,NaN
2,1040300771,Washer 6-200HV,32,GB/T5783-2000,Work platform 00773600130000000,NaN
3,00773400100260020,Protective cover,1,GB/T97.1-2002,Work platform 00773600130000000,NaN
4,00773400100261060,bolt,2,NaN,Work platform 00773600130000000,NaN

100%|██████████| 1/1 [00:01<00:00,  1.58s/it]

- Спросить у Миши про запчасти, в описании которых встречается ещё одна модель, помимо основной, в которой они встречаются
- Что делать с такими в описании (Cubota): ZT138J-ZT24JE-V Turntable Decal Assembly - что значит тире?

In [ ]:
df_all = pd.read_excel('df_all.xlsx')
test_1 = pd.read_excel('dfs.xlsx')
assert test_1.shape[0] == df_all.shape[0]

for col in ['Material No.', 'Код материалов', '物料编码']:
    if col in df_all.columns:
        df_all = df_all[df_all[col] != '']
        df_all = df_all[~df_all[col].astype(str).str.startswith('/')]
        df_all = df_all[~df_all[col].isna()]

display(df_all.head())

if 'Material No.' in df_all.columns and df_all['Material No.'].astype(str).str.contains('NO-NUMBER').any():
    df_all['Material No.'] = df_all['Material No.'].str.split('\n').str[0]
    df_all = df_all[~df_all['Material No.'].astype(str).str.startswith('NO-NUMBER')]

if 'Код материалов' in df_all.columns and df_all['Код материалов'].astype(str).str.contains('NO-NUMBER').any():
    df_all = df_all[~df_all['Код материалов'].astype(str).str.startswith('NO-NUMBER')]

cols = df_all.select_dtypes(include='object').columns
df_all[cols] = (df_all[cols].replace(r'\s*\n\s*', ' ', regex=True))
df_all[cols] = df_all[cols].replace(replacements, regex=True)

if 'Item and Spec' in df_all.columns:
    df_all['Item and Spec'] = df_all['Item and Spec'].replace('/', np.nan)

if '物料编码' in df_all.columns:
    mask = df_all['物料编码'].str.contains(r'^\d+\s+\D', na=False)
    extracted = df_all.loc[mask, '物料编码'].str.extract(r'^(\d+)\s+(.*)$')
    df_all.loc[mask, '物料编码'] = extracted[0]
    df_all.loc[mask, '名称及规格'] = extracted[1]
    
df_merged = merge_parts(df_all) 

assert (df_all.shape[0] - df_all.iloc[:, 0].duplicated().sum() - df_merged.shape[0]) == 0

lst = ['ZS1623RT', 'ZA10RJE', 'ZA14J', 'ZA14JE-Li', 'ZA14NJE', 'ZA16J', 'ZA16JERT', 'ZA18J', 'ZA20J', 'ZA20JE', 'ZA20JERT', 'ZA22J-V' ,'ZA22J', 'ZA24J', 'ZA32J(H-образ.)', 'ZA32J(X-образ.)', 'ZT42J-V', 'ZA42J', '', '', '', '', '', '', '', '', '' ,'', '', 'ZT20J', 'ZT22J-V', 'ZT26J', 'ZT26JS-V', 'ZT30J', 'ZT32J-V', 'ZT32J', 'ZT34J', 'ZT38J', 'ZT42J', 'ZT51J', 'ZT58J', 'ZT72J-V', 'ZT82J', 'ZTH3507', 'ZTH3513', 'ZTH3513', 'ZX23AE']
# df_merged['Models'] = lst[b]
df_merged

df_merged.to_excel(f'{filename}.xlsx', index=False)