In [51]:
import pandas as pd
df = pd.read_excel(r'C:\Users\Normc\OneDrive\Рабочий стол\Python\Работа\data\raw\Остатки и обороты.xlsx', skiprows=range(8), dtype=str)

for col in ["Расход", "Приход", "Конечный остаток", 'Начальный остаток']:
    df[col] = df[col].str.replace(",", "", regex=False).astype(float)

df[df['Конечный остаток'] < 0]

,Unnamed: 0,Номенклатура,Артикул,Оригинальный номер,Начальный остаток,Приход,Расход,Конечный остаток
23518,NaN,Кабель с разъемом от ВПУ,Я0383570,NaN,NaN,NaN,1.0,-1.0
30681,NaN,Кабель с разъемом от ВПУ,Я0383570,NaN,-1.0,NaN,NaN,-1.0

In [45]:
mask = df["Конечный остаток"].str.contains("-", na=False)
result = df[mask]
result

,Unnamed: 0,Номенклатура,Артикул,Оригинальный номер,Начальный остаток,Приход,Расход,Конечный остаток
23518,NaN,Кабель с разъемом от ВПУ,Я0383570,NaN,NaN,NaN,1.000,-1.000
30681,NaN,Кабель с разъемом от ВПУ,Я0383570,NaN,-1.000,NaN,NaN,-1.000